### ISSUE TITLE
请教一个关于你的vpn项目的问题

### ISSUE THREAD

**Issue by googleliyang** [yichengchen/clashX#1]
我的PacketTunnelProvider startTunnel 方法好像一直没执行，也没见日志输出，不知道怎么回事，有时间可以回复下我嘛

**Comment by yichengchen** [comment]
检查系统实时日志 再devices 页面。 同时可以使用rabbit vpn的basictest分支验证。很有可能你的extension在load的时候崩溃了所以没有调用start tunnel

**Comment by googleliyang** [comment]
非常感谢，已经成功了。
