### ISSUE TITLE
请问控制台中，怎么进行一键测速？

### ISSUE THREAD

**Issue by zt900403** [yichengchen/clashX#102]
不好意思， 我翻看更新日志， 发现一键测速移植到了控制台里，但是着了半天控制台中，没有找到按钮， 请告知在哪里， 谢谢。
![image](https://user-images.githubusercontent.com/7888336/52834469-f1f94000-311c-11e9-80f7-5fb3fedf7e27.png)

**Comment by yichengchen** [comment]
打开控制台就会进行测速

**Comment by zt900403** [comment]
@yichengchen 非常感谢您的回复，此外， 我的auto策略中url_test=http://www.gstatic.com/generate_204, 但是有的时候会选择到国内节点，我想问重新打开控制台，会导致他重新测速重新选择节点吗？ 谢谢
