### ISSUE TITLE
'ClashX.h' file not found

### ISSUE THREAD

**Issue by 494310051** [yichengchen/clashX#105]
cty to Build 

ClashX-bridging-Header.h
4  #import "ClashX.h"

failed to emit precompiled header '/Users/me/Library/Developer/Xcode/DerivedData/ClashX-ccqeexmhqtnfmuebnkrktorrqtyb/Build/Intermediates.noindex/PrecompiledHeaders/ClashX-Bridging-Header-swift_3VDTP9VL6A0PI-clang_2R07UPV97G866.pch' for bridging header '/Users/me/clashX-master/ClashX/ClashX-Bridging-Header.h'

**Comment by yichengchen** [comment]
go build -buildmode=c-archive

**Comment by giveup** [comment]
有类似的错误，先执行go build -buildmode=c-archive只会，Xcode再次编译就会报错

> ld: warning: directory not found for option '-L/Users/user/Documents/GitHub/clashX/ClashX/clash'
ld: warning: directory not found for option '-F/Users/user/Documents/GitHub/clashX/Carthage/Build/Mac'
ld: warning: ignoring file /Users/user/Documents/GitHub/clashX/ClashX/ClashX.a, file was built for archive which is not the architecture being linked (x86_64): /Users/user/Documents/GitHub/clashX/ClashX/ClashX.a
Undefined symbols for architecture x86_64:
  "_run", referenced from:
      ClashX.AppDelegate.startProxy() -> () in AppDelegate.o
  "_setUIPath", referenced from:
      ClashX.AppDelegate.startProxy() -> () in AppDelegate.o

尝试了go build -v -buildmode=c-shared也会出错
