### ISSUE TITLE
希望有更好的 AppleScript 支持

### ISSUE THREAD

**Issue by emdoe** [yichengchen/clashX#106]
当前可能仅能用 AppleScript 调出菜单，而无法进一步选择子项目？
即仅能：

```AppleScript
tell application "System Events"
    click menu bar item 1 of menu bar 2 of application process "ClashX"
end tell
```

而无法再进一步调用 AppleScript 来选择 `Proxy Mode` 或者 `Set as system proxy` 

---

暂时的解决方法只能是利用快捷键模拟按键（以 `⌘ + S` 对应的 `Set as system proxy` 为例 ）：

```AppleScript
ignoring application responses
    tell application "System Events"
        click menu bar item 1 of menu bar 2 of application process "ClashX"
    end tell
end ignoring
delay 0.1
do shell script "killall 'System Events'"
tell application "System Events"
    keystroke "s" using command down
end tell
```
或者请问是否有更好的方法来实现类似的功能（即在不同的网路环境下自动选择不同的代理模式）？

**Comment by yichengchen** [comment]
emmm 为什么不能选择呢…ClashX已经使用很标准的storyboard进行菜单栏的构建了…

**Comment by emdoe** [comment]
测试过 `click menu item "Set as system proxy" of menu 1 of menu bar item 1 of menu bar 2`（抱歉这个是凭借记忆写的，可能与检测得到的有稍许出入，但换做 `menu item 7 of menu of ...` 等等一样不可以，或者标准的语法是另外的样子？），并不能成功选择。用 UI Browser 来检测并测试时，在 `menu bar item 1 of menu bar 2` 之后，就没有有效且可以 press 的对象了。

或者是否可以支持设置系统全局的快捷键？

**Comment by Chandler-Lu** [comment]
@yichengchen 是想用alfred之类的东西进行快捷操作吧

**Comment by yichengchen** [comment]
想了想 其实 可以直接调用clash api……

**Comment by xtremforce** [comment]
> 想了想 其实 可以直接调用clash api……

求教 Clash API 怎样切换 “出站模式”？

**Comment by Chandler-Lu** [comment]
> > 想了想 其实 可以直接调用clash api……
> 
> 求教 Clash API 怎样切换 “出站模式”？

感觉没有，出站模式属于UI的控制内容
