### ISSUE TITLE
maxOS 10.14 中睡眠后软件崩溃，以及无法保存端口号

### ISSUE THREAD

**Issue by AlanDecode** [yichengchen/clashX#107]
* 长时间连续使用，电脑睡眠后 Clash 崩溃，重新开启后一段时间再次崩溃。
* 另外，设置 Socks5 端口号后重启应用不能记住上一次设置。

P.S. 感谢作者提供如此方便易用的软件！

**Comment by yichengchen** [comment]
Socks5 端口要在 config.yml 文件（而不是其他可选择的文件）中进行配置
崩溃问题需要在上游clash项目中提出。
