### ISSUE TITLE
添加多个节点之后 应用退出  然后重新打开 打不开

### ISSUE THREAD

**Issue by lieber68** [yichengchen/clashX#11]
日志如下：
![](https://ws1.sinaimg.cn/large/0069RVTdgy1fu84mqno0jj31ba0r6112.jpg)

**Comment by yichengchen** [comment]
Check if there is something wrong in your config file. Currently wrong config such as wrong encrypt method (AES-256-CFB √ aes-256-cfb ×) would cause upstream clash exit using "Log.fatal" and crash the ClashX

**Comment by yichengchen** [comment]
错误提示在1.3得到了加强
