### ISSUE TITLE
[bug]1.9.5 无法选择节点

### ISSUE THREAD

**Issue by BenjaminGao** [yichengchen/clashX#110]
![bug](https://user-images.githubusercontent.com/16028320/53554449-bded3880-3b7a-11e9-846c-0afaea5ee033.gif)

可以看到节点始终无法更改，唯一的方式就是在

![snipaste_2019-02-28_17-05-15](https://user-images.githubusercontent.com/16028320/53554613-1d4b4880-3b7b-11e9-9672-45437c290d5a.png)

**Comment by MF-x** [comment]
找到原因了ProxyMenuItem这个类，没有对proxyName初始化，导致actionSelectProxy这个方法里面的sender拿不到proxyName。

**Comment by BenjaminGao** [comment]
@MF-x 嗯，我还是等着更新吧 =。=

**Comment by yichengchen** [comment]
Fixed
