### ISSUE TITLE
托管配置里面的配置地址可以支持本地目录地址吗

### ISSUE THREAD

**Issue by HappyQuQu** [yichengchen/clashX#113]
托管配置里面的配置地址可以支持本地目录地址吗
想把配置放在onedrive里面
这样子win 和mac 可以使用同一个配置

**Comment by HappyQuQu** [comment]
![photo_2019-03-01_09-35-57](https://user-images.githubusercontent.com/4098823/53610346-6e078380-3c05-11e9-9c87-b16fe24eab30.jpg)
类似于 clash for win 这样子 
类似于 surge conf 放在 iCloud drive 里面 基本 ios 或着 mac 一边改了 另外一边 立马同步了

**Comment by yichengchen** [comment]
可以考虑

**Comment by MF-x** [comment]
@HappyQuQu 其实完全可以吧config放在iCloud里，然后建个硬连接到~/config/clash 就好了

**Comment by HappyQuQu** [comment]
> @HappyQuQu 其实完全可以吧config放在iCloud里，然后建个硬连接到~/config/clash 就好了
可以是可以 但是 iCloud 在win下面不怎么给力啊 ...

**Comment by yichengchen** [comment]
> @HappyQuQu 其实完全可以吧config放在iCloud里，然后建个硬连接到~/config/clash 就好了
> 可以是可以 但是 iCloud 在win下面不怎么给力啊 ...

那可以建个连接到onedrive ？

**Comment by MF-x** [comment]
> > @HappyQuQu 其实完全可以吧config放在iCloud里，然后建个硬连接到~/config/clash 就好了
> > 可以是可以 但是 iCloud 在win下面不怎么给力啊 ...
> 
> 那可以建个连接到onedrive ？

我没试过，不过应该可以吧，我只记得onedrive不认软链接

**Comment by cpaig** [comment]
要是支持WebDAV就更好了，想用坚果云

**Comment by Yes2Me** [comment]
syncthing 了解一下

**Comment by EvanQuCN** [comment]
> > > @HappyQuQu 其实完全可以吧config放在iCloud里，然后建个硬连接到~/config/clash 就好了
> > > 可以是可以 但是 iCloud 在win下面不怎么给力啊 ...
> > 
> > 
> > 那可以建个连接到onedrive ？
> 
> 我没试过，不过应该可以吧，我只记得onedrive不认软链接

试了下 建立一个软连接 目前没问题
