### ISSUE TITLE
不支持外部导入json文件生成config

### ISSUE THREAD

**Issue by bluecube13** [yichengchen/clashX#118]
之前的版本还支持外部导入json文件生成config，新版本为什么变得不支持了呢？

**Comment by aiddroid** [comment]
配置相当糟糕，不知道这软件到底怎么用，yml配置里似乎是json又不是，然后报错了查日志也没看到错在哪，晕头转向。

**Comment by yichengchen** [comment]
因为不知道如何生成规则  各家的json格式规范也不一样
pr is wellcome
