### ISSUE TITLE
扫描shadowsocks二维码，解析失败。

### ISSUE THREAD

**Issue by shunichio** [yichengchen/clashX#120]
从手机上Shadowrocket APP中导出shadowsocks账号二维码，再通过clashx的二维码扫描功能扫描，出现错误。

![2019-03-04 11 05 30](https://user-images.githubusercontent.com/23553358/53708469-a1008000-3e6e-11e9-84fe-96722f16272b.png)

**Comment by yichengchen** [comment]
现在最新版本暂时取消了扫描二维码功能
