### ISSUE TITLE
Remote Config URL 清空

### ISSUE THREAD

**Issue by gaorocks** [yichengchen/clashX#124]
Config -> Remote Config -> Set Url 里面设置过的URL不能被清空，尝试过修改/删除 \~/Library/Preferences/com.west2online.ClashX.plist，发现每次重启ClashX后这个plist文件都会被重置成包含旧设置的内容。甚至尝试过 brew cask zap clashx 以及删除 \~/.config，\~/Library/Application Support，\~/Library/Logs，\~/Library/Container 等路径下的残留文件，但是依旧不管用。有点强迫症，请问作者这是怎么回事呢？

**Comment by yichengchen** [comment]
defaults delete com.west2online.ClashX
UserDefault是苹果官方提供的配置文件存储方法

**Comment by gaorocks** [comment]
原来是因为配置文件有缓存，感谢指点！
