### ISSUE TITLE
时不时出现 tcp: i/o timeout

### ISSUE THREAD

**Issue by nanhezzb** [yichengchen/clashX#127]
![image](https://user-images.githubusercontent.com/32955697/54407565-42ae8980-4719-11e9-87e7-051a1873b0c0.png)
时不时出现连接超时的情况，比如 QQ 接收图片，QQ、微信查看好友头像时，其他情况也遇见过超时导致图片加载失败。

**Comment by yichengchen** [comment]
到上游clash项目提出这个问题？
