### ISSUE TITLE
IP-CIDR,IP地址,REJECT规则导致ClashX1.9.6崩溃

### ISSUE THREAD

**Issue by rTnrWE** [yichengchen/clashX#129]
- IP-CIDR,IP地址,REJECT
规则重载后无报错，但ClashX1.9.6随即崩溃，直到删除
 - IP-CIDR,IP地址,REJECT
规则后ClashX1.9.6才能启动

注：
 - DOMAIN,域名,REJECT
导入后一切正常

怎么在ClashX里编写正确的IP,REJECT规则？

谢谢！

**Comment by yichengchen** [comment]
IP-CIDR 规则在填写错误时崩溃的bug clash上游已修复
