### ISSUE TITLE
Telegram sending image error

### ISSUE THREAD

**Issue by ky0nch3ng** [yichengchen/clashX#13]
Use GLOBAL mode, unable to send image.

**Comment by yichengchen** [comment]
we had tried many times with different proxies and modes,telegram works fine......

**Comment by lieber68** [comment]
add "IP-CIDR6,2001:b28:f23f:f005::a,Proxy,no-resolve" to config.ini ,then try it

**Comment by ky0nch3ng** [comment]
@yichengchen @lieber68 
It doesn't work. I use GLOBAL mode, not use RULES mode, this rule is ignore.

**Comment by ky0nch3ng** [comment]
![Imgur](https://i.imgur.com/92PNZMZ.png)

![Imgur](https://i.imgur.com/xnITl8w.png)

![Imgur](https://i.imgur.com/fK2uCvc.png)

Telegram always sending request body.

And my dropbox always uploading, never complete.

**Comment by Tsahao** [comment]
It seems that Telegram could work after setting a SOCKS5 proxy for it.

My Dropbox can upload as normal without a proxy set inside the app.

**Comment by ky0nch3ng** [comment]
@Tsahao Setting socks proxy or not setting socks proxy, telegram can not receive and send image file.

**Comment by lieber68** [comment]
emmm.... you can try reboot Mac

**Comment by ky0nch3ng** [comment]
@yichengchen @lieber68 
Reboot and turn off tcp fast-open on server, still not solved right now.

**Comment by yichengchen** [comment]
Try latest 1.3.6. reopen the issue if still having any problem.
