### ISSUE TITLE
Set as system proxy not working

### ISSUE THREAD

**Issue by zeroinyang** [yichengchen/clashX#131]
您好，

在使用clashX的时候，遇到下面两个问题，麻烦有空的时候可以看一下，谢谢。
1. 打开clashX，选中"Set as system proxy"的以后，当前WIFI的Proxies中没有加入，https proxy，http_proxy和socks proxy，需要手动加入；取消选中的时候，proxy也没有清除，在log中没有找到相关的记录，不知道是哪里设置需要调整。
clashX的版本是1.9.8.1
Mac的版本是10.14.3
2. 每次重新打开clashX，都提示install a small tool到~/.config/clash，但是~/.config/clash目录上在第一次打开的时候已经输入过密码创建了目录，目录下也有文件了，这个也不知道是什么原因。

**Comment by jutkko** [comment]
I have the same problem on one of my machines. But not on all. Not sure why.

**Comment by zjdavid** [comment]
+1 同样问题
系统版本也是10.14.3

会不会是新系统改了什么机制？

**Comment by zhangda47** [comment]
+1

**Comment by xuhaoyang** [comment]
@jutkko @zjdavid @zhangda47 退到上一个版本，安装完助手，在升级上来

**Comment by zeroinyang** [comment]
@xuhaoyang Yes, I tried version 1.9.6 and it works, Thanks.

**Comment by jutkko** [comment]
Thanks.
