### ISSUE TITLE
自动设置网络代理失败

### ISSUE THREAD

**Issue by anythink-wx** [yichengchen/clashX#132]
为什么每次打开都提示我需要安装一个小工具到~.config/clash  ，然后点安装输入密码后并没有安装成功，也没有错误提示。我打开网络看代理也没有勾选自动配置

**Comment by anythink-wx** [comment]
直接到.config 下面运行 ProxyConfig 也报错.
`➜  clash ./ProxyConfig 
dyld: Library not loaded: @rpath/libswiftCore.dylib
  Referenced from: /Users/a2eam/.config/clash/./ProxyConfig
  Reason: image not found
[1]    75824 abort      ./ProxyConfig
➜  clash `

**Comment by xuhaoyang** [comment]
退到上一个版本，安装完助手，再升级上来

**Comment by yichengchen** [comment]
这个版本proxyconfig有问题

**Comment by yichengchen** [comment]
Will be fixed in the next version soon
