### ISSUE TITLE
升级1.9.81后，无法打开控制台

### ISSUE THREAD

**Issue by banpie** [yichengchen/clashX#133]
Hi：

## 问题描述

升级了1.9.81后，遇到两个问题：
1. 无法切换直接链接或者PAC模式，无论怎么修改都是在Global
![image](https://user-images.githubusercontent.com/9192763/55402907-28810200-5587-11e9-915c-e9d31c4b84e0.png)

2. 点击控制台，无法显示内容
![image](https://user-images.githubusercontent.com/9192763/55402918-3171d380-5587-11e9-8ea0-886e1a3ab5ff.png)

## 尝试的步骤
1. 卸载重装，无效；
2. 安装旧版（1.9.6，1.9.2），无效；
3. 重启，无效；

最后，感谢开发者的软件！

**Comment by siald** [comment]
一样的问题

**Comment by shooter119** [comment]
<img width="382" alt="屏幕快照 2019-04-05 下午3 57 54" src="https://user-images.githubusercontent.com/47934620/55612846-c78e3f80-57bb-11e9-8d6b-ffec1deaea88.png">

**Comment by kinosir** [comment]
同遇到这两个问题TAT

**Comment by yichengchen** [comment]
这是配置文件不正确造成clash启动失败？

**Comment by Chandler-Lu** [comment]
@yichengchen 我尝试复现了一下这个问题，当默认配置文件有错时，切换配置文件是无效的，会导致始终全局模式。需要删除默认配置文件，让程序重新创建

**Comment by canyu9512** [comment]
同样每天打开proxy mode没办法切换，控制台我是可以打开，但是设置里的端口显示都是0，然后也起不到效果，昨天重装删掉配置文件都没有用，时灵时不灵，求解，电脑系统10.14.4，软件版本1.9.8.2

**Comment by rosuH** [comment]
打开配置文件夹，然后退出 ClashX，接着删除默认的配置文件后重启即可。

**Comment by yichengchen** [comment]
closed. free to repoen if problem continue exists
