### ISSUE TITLE
每次退出并重新打开都要使用管理员权限安装小工具

### ISSUE THREAD

**Issue by ming-jock** [yichengchen/clashX#134]
详细内容见图，不管是重启电脑还是退出APP再次打开，点击安装并且输入密码确定，然后退出并再次打开应用就会弹如下框
![image](https://user-images.githubusercontent.com/14990759/55569535-53f51f80-5734-11e9-8899-6e3f27530568.png)

**Comment by samymyue** [comment]
你問題如何解決的？

**Comment by ming-jock** [comment]
> 
> 
> 你問題如何解決的？

木有解决,本来是打算将就用的,但是后面又没有再弹这个了,所以就把issue给close了

**Comment by samymyue** [comment]
> > 你問題如何解決的？
> 
> 木有解决,本来是打算将就用的,但是后面又没有再弹这个了,所以就把issue给close了

因為我現在都有這個問題，請問你的電腦是什麼？

**Comment by ming-jock** [comment]
> > > 你問題如何解決的？
> > 
> > 
> > 木有解决,本来是打算将就用的,但是后面又没有再弹这个了,所以就把issue给close了
> 
> 因為我現在都有這個問題，請問你的電腦是什麼？

2018 Mac mini,系统版本是10.14.4

**Comment by samymyue** [comment]
> > > > 你問題如何解決的？
> > > 
> > > 
> > > 木有解决,本来是打算将就用的,但是后面又没有再弹这个了,所以就把issue给close了
> > 
> > 
> > 因為我現在都有這個問題，請問你的電腦是什麼？
> 
> 2018 Mac mini,系统版本是10.14.4

我在想會不會是T2 Chips 的問題，我的都是一樣

**Comment by ming-jock** [comment]
> > > > > 你問題如何解決的？
> > > > 
> > > > 
> > > > 木有解决,本来是打算将就用的,但是后面又没有再弹这个了,所以就把issue给close了
> > > 
> > > 
> > > 因為我現在都有這個問題，請問你的電腦是什麼？
> > 
> > 
> > 2018 Mac mini,系统版本是10.14.4
> 
> 我在想會不會是T2 Chips 的問題，我的都是一樣

具体是啥原因我也不太清楚,issue提了几天可能作者也没看到,然后莫名其妙就好了,所以就没管了

**Comment by samymyue** [comment]
> > > > > > 你問題如何解決的？
> > > > > 
> > > > > 
> > > > > 木有解决,本来是打算将就用的,但是后面又没有再弹这个了,所以就把issue给close了
> > > > 
> > > > 
> > > > 因為我現在都有這個問題，請問你的電腦是什麼？
> > > 
> > > 
> > > 2018 Mac mini,系统版本是10.14.4
> > 
> > 
> > 我在想會不會是T2 Chips 的問題，我的都是一樣
> 
> 具体是啥原因我也不太清楚,issue提了几天可能作者也没看到,然后莫名其妙就好了,所以就没管了

我的還未好。。。
