### ISSUE TITLE
Cmd-L is required every time to display logs

### ISSUE THREAD

**Issue by clavichord93** [yichengchen/clashX#135]
In the dashboard, log view is empty until I press cmd-L or click 'display logs' from the menu bar, every time, no matter whether I click 'display logs' or not in the last time. Is this a bug or a feature?

**Comment by yichengchen** [comment]
yap. dashboard is actually made by webview. it can not read logs before you open it. it's recommended reading log using  'display logs' from the menu bar rather than dashboard
