### ISSUE TITLE
启动时自动更新订阅可以通过选项关闭吗

### ISSUE THREAD

**Issue by xtrats** [yichengchen/clashX#136]
我现在是通过脚本更新，会在更新完后加上我自己的 ignore list。

升级到 1.9.8.1 后，每次启动会按照订阅地址更新，我的 ignore list 就会失效，需要手动再次执行我的更新脚本才能使用。

有几种方式可以解决：

1. 订阅地址可以改成执行本地脚本，或者通过 HTTP 获取
2. 提供关闭自动更新订阅的选项
3. 软件中增加自定义ignore list的功能，这样就不用通过脚本更新了。。

**Comment by yichengchen** [comment]
will add an option in next version soon
