### ISSUE TITLE
建议把图标中的灰色背景去掉

### ISSUE THREAD

**Issue by clavichord93** [yichengchen/clashX#141]
把图标中的灰色背景去掉更符合目前macOS上app图标的设计风格，建议更新一下图标。

**Comment by yichengchen** [comment]
Designer @jas0ncn say no

**Comment by jas0ncn** [comment]
Clash 主 logo 是一只深蓝色的猫，直接做成 icon 不太合适，会容易混于深色底中，可以参考百度网盘和网易云音乐的 icon，都是如此
