### ISSUE TITLE
1.9.9 托管配置-点击更新，不进行网络请求。

### ISSUE THREAD

**Issue by van7ish** [yichengchen/clashX#143]
版本：1.9.9
ClashX -> 配置 -> 托管配置 -> 更新，点击之后不更新配置。
好像并没有进行网络请求，就直接弹窗显示“No update needed!”。

**Comment by yichengchen** [comment]
No update needed! 表示获取到了文件和本地文件是一模一样的……快速请求可能有系统缓存？

**Comment by CsHeng** [comment]
同表示，完全没有发起请求，本地和服务器也没看到有任何该url的任何记录。

服务端用nginx serve static file，加了`expires -1`，表示`no-cache`，但依然未请求？

求解

**Comment by CsHeng** [comment]
看了下remoteconfigmanager的代码，应该是网络请求库缓存了？

https://stackoverflow.com/questions/32199494/how-to-disable-caching-in-alamofire

试过把本地文件删了，update还是拿到旧的文件，而用postman或者浏览器直接请求则没问题。

**Comment by yichengchen** [comment]
Fix
