### ISSUE TITLE
保留用户自定义配置

### ISSUE THREAD

**Issue by diemus** [yichengchen/clashX#144]
订阅服务商给出的rule过于简单粗暴了，但是我自己添加的规则每次更新后又会被覆盖掉。能不能保留用户自定义配置？每次更新都覆盖服务商提供的。显然服务商应该专注于提供proxy，而不是决定用户的rule。

**Comment by durongzhang** [comment]
订阅proxy，订阅rule，用户rule应该分开

**Comment by yichengchen** [comment]
据说以后clash会支持类似rule set的规则 clashx这里不做更多处理
