### ISSUE TITLE
mac 如何配合 redir 透明代理?

### ISSUE THREAD

**Issue by xinshangshangxin** [yichengchen/clashX#146]
配置中存在

```
# Linux 和 macOS 的 redir 代理端口 (如需使用此功能，请取消注释)
# redir-port: 7892
```

用什么软件 配置 `redir-port` 进行 透明代理?
有 `demo` 吗?

谢谢!

**Comment by MonwF** [comment]
直接使用`pf`转发至clash，总是报错
后来参考[这篇文章](https://sony.work/blog/post/admin/%E5%9C%A8Mac-OS%E4%B8%8B%E5%81%9A%E9%80%8F%E6%98%8E%E4%BB%A3%E7%90%86-%E9%80%9A%E8%BF%87PF)，用redsocks转发，算是基本跑通，但有个问题: clash接收到的全是ip，没有host

**Comment by xinshangshangxin** [comment]
@MonwF 粗略的看了下, 有点复杂, 依赖过多
之前有发现过 有闭源软件 可以做到 通过加入 `Routing tables` 来实现 透明代理
但是我搜索开源的方案, 没有找到

**Comment by MonwF** [comment]
> @MonwF 粗略的看了下, 有点复杂, 依赖过多
> 之前有发现过 有闭源软件 可以做到 通过加入 `Routing tables` 来实现 透明代理
> 但是我搜索开源的方案, 没有找到

是指reborn吗？感觉它只是对 https://github.com/eycorsican/go-tun2socks 的封装？

**Comment by xinshangshangxin** [comment]
@MonwF 
是的, `reborn`,
 `clashX` 能做到 这样简洁的 开启透明代理吗?

**Comment by MonwF** [comment]
> @MonwF
> 是的, `reborn`,
> `clashX` 能做到 这样简洁的 开启透明代理吗?

不能，只能设置为系统代理使用，我这边`redir-port`都无效
我现在是 pf + redsocks2 + dnsmasq + clash(命令行) 来实现透明代理

**Comment by xinshangshangxin** [comment]
@MonwF 
多谢!

**Comment by yichengchen** [comment]
> > @MonwF
> > 是的, `reborn`,
> > `clashX` 能做到 这样简洁的 开启透明代理吗?
> 
> 不能，只能设置为系统代理使用，我这边`redir-port`都无效
> 我现在是 pf + redsocks2 + dnsmasq + clash(命令行) 来实现透明代理

clashx没有root权限 所以无法在53端口监听dns 只能开在8053类似高端口（5353倍系统占用）

**Comment by MonwF** [comment]
> > > @MonwF
> > > 是的, `reborn`,
> > > `clashX` 能做到 这样简洁的 开启透明代理吗?
> > 
> > 
> > 不能，只能设置为系统代理使用，我这边`redir-port`都无效
> > 我现在是 pf + redsocks2 + dnsmasq + clash(命令行) 来实现透明代理
> 
> clashx没有root权限 所以无法在53端口监听dns 只能开在8053类似高端口（5353倍系统占用）

dns 监听是想通过解析记录来反推域名吧？ 我试过在clashx的dns外层套一个dnsmasq，效果还行。主要是redir-port不能用，很不爽。
另外，能否考虑加入 ipset 的rule， linux可以读ipset，mac读 pftable

**Comment by yichengchen** [comment]
> > > > @MonwF
> > > > 是的, `reborn`,
> > > > `clashX` 能做到 这样简洁的 开启透明代理吗?
> > > 
> > > 
> > > 不能，只能设置为系统代理使用，我这边`redir-port`都无效
> > > 我现在是 pf + redsocks2 + dnsmasq + clash(命令行) 来实现透明代理
> > 
> > 
> > clashx没有root权限 所以无法在53端口监听dns 只能开在8053类似高端口（5353倍系统占用）
> 
> dns 监听是想通过解析记录来反推域名吧？ 我试过在clashx的dns外层套一个dnsmasq，效果还行。主要是redir-port不能用，很不爽。
> 另外，能否考虑加入 ipset 的rule， linux可以读ipset，mac读 pftable

clash的产生就是为了不使用ipset这种东西吧 有域名规则 有ip-cidr规则。

**Comment by MonwF** [comment]
如果能有增强模式，从ip反推域名是不需要，但现在mac下比较难用，没动态 cidr 这个也不强求

**Comment by yichengchen** [comment]
> 如果能有增强模式，从ip反推域名是不需要，但现在mac下比较难用，没动态 cidr 这个也不强求

增强模式还在咕咕咕中

**Comment by lou-lan** [comment]
@MonwF Reborn 不是对 https://github.com/eycorsican/go-tun2socks 的封装，他是原生语言，不过原理也是 tun2socks

**Comment by lou-lan** [comment]
@xinshangshangxin 没有创建出特殊 tun 网卡，光有 `Routing tables` 还不行
