### ISSUE TITLE
关于 StatusBar 内的网速显示

### ISSUE THREAD

**Issue by zsakvo** [yichengchen/clashX#148]
请问网速显示的字体能否稍微加粗或者放大些？与 Networker 以及 Surge 的网速显示相比，clashX 的有点过于纤细，看起来有些累，谢谢。
![image](https://user-images.githubusercontent.com/25399519/57346307-97eaa280-7180-11e9-91e3-b5d03a7c9b81.png)

**Comment by yichengchen** [comment]
要是能提供个字号就更好了……

**Comment by yichengchen** [comment]
Fixed
