### ISSUE TITLE
编译失败：Undefined symbol: _run Undefined symbol: _setUIPath

### ISSUE THREAD

**Issue by giveup** [yichengchen/clashX#150]
> ignoring file clashX/ClashX/ClashX.a, file was built for archive which is not the architecture being linked (x86_64): clashX/ClashX/ClashX.a

看起是这个文件编译的有问题，但是确实是使用go build -buildmode=c-archive
来编译的，请问是否有错误的步骤，谢谢。
环境：
macOS 10.14.4 (18E226)
Xcode 10.2.1 (10E1001)

**Comment by yichengchen** [comment]
所有的编译指令已经在ci文件中写的很明确了，可以根据ci文件步骤进行 .travis.yml 进行编译
