### ISSUE TITLE
Didn't match rule

### ISSUE THREAD

**Issue by myeveryheart** [yichengchen/clashX#152]
I have a rule like this
Rule:
- DOMAIN-KEYWORD,google,Proxy

But when I use the rule mode, I can't open google, the log shows:
www.google.com doesn't match any rule using DIRECT

The interesting thing is, I switch the mode to global and switch back to rule, I can open google, no log like above.

**Comment by yichengchen** [comment]
Proxy doesn't means using Proxy. It means using a named 'Proxy' which specified in the Proxy or Proxy Group section in the config file. If you don't have a proxy or a proxy group called 'Proxy', this rule would be auto ignored
