### ISSUE TITLE
忽略的主机设置

### ISSUE THREAD

**Issue by bviews** [yichengchen/clashX#153]
设置成系统代理后，会自动将这些网段设置成忽略的主机与域：
<img width="564" alt="WX20190519-005952@2x" src="https://user-images.githubusercontent.com/2810579/57972781-b139ed00-79d1-11e9-9b9e-79bc9d4761ce.png">

希望这个可以在配置文件中读取设置，由于某些原因配置里也有这些 IP 段的规则，自动设置了这些参数以后，会使得规则失效。

**Comment by yichengchen** [comment]
查看主页readme 可以修改配置文件
