### ISSUE TITLE
每次重開都要打管理員權限

### ISSUE THREAD

**Issue by samymyue** [yichengchen/clashX#154]
詳細內容見圖，不管是重啓電腦還是退出APP再次打開，點擊安裝並且輸入密碼確定，然後退出並再次打開應用就會彈如下框
<img width="409" alt="Screenshot 2019-05-22 at 9 45 36 PM" src="https://user-images.githubusercontent.com/49505642/58179665-39bed300-7cdb-11e9-905a-dd9e90e77427.png">

**Comment by yichengchen** [comment]
closed. Create a new issue if problem continue exists
