### ISSUE TITLE
clashx 的一些建议

### ISSUE THREAD

**Issue by uwings** [yichengchen/clashX#157]
1. 默认打开clash X 的分支是rm， 什么都没有，要手动切换 master。 不知为何，可能导致错过clashx
2. README 完全是写给程序猿啊， 还需要查issue 才知道怎么用。  如果写的通俗易懂一些，肯定会大受欢迎。     比如完整的配置过程，和一些参数说明， 简单的 getstart， 简单配置就可以开始用。  因为软件本身功能很棒

**Comment by uwings** [comment]
傻傻的问个问题， 这里测速的 interval: 300  是指300 毫秒么？  如果按300 算，一般情况一月测速需要多少流量支出？

**Comment by Fndroid** [comment]
300单位是秒，5分钟一次。如果URL写的``http://www.gstatic.com/generate_204``那么测速基本不会费什么流量的

**Comment by Chandler-Lu** [comment]
默认分支是rm难道你不懂为什么么。。

**Comment by deanwangkt** [comment]
哈哈哈哈哈哈哈xs

**Comment by uwings** [comment]
> 默认分支是rm难道你不懂为什么么。。

真不知道，我不是程序猿

**Comment by uwings** [comment]
> 哈哈哈哈哈哈哈xs

？？？
