### ISSUE TITLE
能否增加一个自动根据网速选择节点的功能？

### ISSUE THREAD

**Issue by jetma** [yichengchen/clashX#160]
定时自动测试并选择速度最快的节点，而不是像现在这样手动选择。

**Comment by Fndroid** [comment]
不可能有自动选择速度最快的，只有选择延迟最低的，现在已经有了

**Comment by jetma** [comment]
> 不可能有自动选择速度最快的，只有选择延迟最低的，现在已经有了

效果是一样的，现在的版本可以自动选择延迟最低的节点？我没有找到在哪里设置。

**Comment by Fndroid** [comment]
速度和延迟当然不一样。。

根据延迟选择最低的策略叫做``url-test``，参考配置文件：https://github.com/Hackl0us/SS-Rule-Snippet/blob/master/LAZY_RULES/clash.yml

**Comment by jetma** [comment]
> 速度和延迟当然不一样。。
> 
> 根据延迟选择最低的策略叫做`url-test`，参考配置文件：https://github.com/Hackl0us/SS-Rule-Snippet/blob/master/LAZY_RULES/clash.yml

了解了，测试了下效果非常好，多谢！
