### ISSUE TITLE
没有代理邮箱993端口吗

### ISSUE THREAD

**Issue by alanhg** [yichengchen/clashX#162]
比如Mac安装后，打开全局，即使再加上surge做前置代理，还是没有解决mail客户端下，gmail问题。无法正常连接，收发邮件。

相关问题:
https://github.com/v2ray/v2ray-core/issues/522

**Comment by yichengchen** [comment]
经过验证 应该是你的代理服务器被gmail屏蔽了如阿里云海外ip 尝试更换代理服务器可以解决

**Comment by alanhg** [comment]
> 经过验证 应该是你的代理服务器被gmail屏蔽了如阿里云海外ip 尝试更换代理服务器可以解决

能推荐个服务吗

**Comment by alanhg** [comment]
确实是代理服务器ip被封的原因，感谢。
