### ISSUE TITLE
能否支持扫码添加config文件的feature？

### ISSUE THREAD

**Issue by Buffer2Disk** [yichengchen/clashX#165]
如题，现在的菜单隐藏的太深了，要单独去找配置文件夹很麻烦，
如果能扫码添加配置文件就好了，直接把按钮设置在一级菜单那里，
二维码的内容就是  配置文件的下载链接，扫码后自动添加配置，就像SS的客户端那样

**Comment by yichengchen** [comment]
扫码添加订阅？

**Comment by Buffer2Disk** [comment]
对的，最起码添加配置文件的菜单不要隐藏的那么深嘛

**Comment by yichengchen** [comment]
会在多订阅完成后实现

**Comment by yichengchen** [comment]
添加了使用链接的形式添加 clashx:///install-config?url=http%3A%2F%2Fexample.com 二维码以后再考虑吧 感觉用处不大
