### ISSUE TITLE
希望允许添加多个配置文件的更新地址

### ISSUE THREAD

**Issue by zhuxiaoxi** [yichengchen/clashX#167]
每次把新的更新地址贴上，之前的就不能更新了，希望增加对多个订阅链接的支持。
每次更新过来的文件都是以网址前的域名保存的，希望增加备注功能。

**Comment by littlebeandog** [comment]
+1s 
这个功能刚需啊,订阅多家的时候每个都要手动刷一遍,太不友好了.
另外有没有可能把自定义规则放在独立文件,优先级更高,现在每次订阅更新之后又要重新手写一遍自定义的规则.

**Comment by yichengchen** [comment]
已添加多重订阅
