### ISSUE TITLE
外部代理程序支持

### ISSUE THREAD

**Issue by nutinshell** [yichengchen/clashX#168]
出于压测和某些特殊关系，经常需要运行一个程序来提供 http 代理。不知道可不可以让 clashx 配置某个代理，可让其自动启动第三方程序， 并使用产生的 http 代理？

**Comment by yichengchen** [comment]
暂时不会有什么不过可以在设置系统代理的时候运行指定脚本

### Run custom custom scripts after set/unset system proxy.
    - set kProxyEnableHook and kProxyDisableHook in your termial

        defaults write com.west2online.ClashX kProxyEnableHook -string "Your commond"
        defaults write com.west2online.ClashX kProxyDisableHook -string "Your commond"

    - For Examole:

      defaults write com.west2online.ClashX KproxyEnableHook -string "/usr/local/bin/python3 /Users/username/.config/clash/proxy_up.py"
