### ISSUE TITLE
realod config fail

### ISSUE THREAD

**Issue by bankel** [yichengchen/clashX#170]

**Comment by bankel** [comment]
<img width="343" alt="Screen Shot 2019-06-26 at 10 17 09" src="https://user-images.githubusercontent.com/3132004/60147586-98a6c900-9800-11e9-89f1-a719d4c92ed7.png">

**Comment by bankel** [comment]
卸载之后，重装，订阅地址，还是碰到相同的问题

**Comment by yichengchen** [comment]
应该是订阅的服务端出现了问题
