### ISSUE TITLE
ClashX 1.10.0 Config loading Fail

### ISSUE THREAD

**Issue by TristenChenTao** [yichengchen/clashX#172]
ClashX 1.10.0 Config loading Fail
 Info:
Config loading Fail!
config.ymal: Rules [o] [domain,gs.apple.com,Proxyl error: proxy  [Proxy] not found

MacOS:10.14.5
ClashX 1.9.11 use same config url is working

**Comment by cwx0046** [comment]
Just **delete config.yaml** and restart ClashX.


In [release note](https://github.com/yichengchen/clashX/releases) of 1.10.0
> Any error in default config file config.yaml would cause ClashX launch fail. If you are having problem on launch after upgrade to this version, consider to delete config.yaml and let ClashX auto create it.

**Comment by Albych** [comment]
> Just **delete config.yaml** and restart ClashX.
> 
> In [release note](https://github.com/yichengchen/clashX/releases) of 1.10.0
> 
> > Any error in default config file config.yaml would cause ClashX launch fail. If you are having problem on launch after upgrade to this version, consider to delete config.yaml and let ClashX auto create it.

Also works well on MacOS:10.15 Beta

**Comment by TristenChenTao** [comment]
i have try to delete config.yaml and let ClashX auto create it, then i set config url , it shows  Download fail

**Comment by TristenChenTao** [comment]
i found the error in XXX.yaml
these url cause load fail  in clashx 1.10, but clashx 1.9.11 is fine
i can run clashx 1.10 after remove these url in XXX.yaml 
Rule:
  - 'DOMAIN,audio-ssl.itunes.apple.com,Apple Services'
  - 'DOMAIN,gspe1-ssl.ls.apple.com,Apple Services'
  - 'DOMAIN,itunes.apple.com,Apple Services'
  - 'DOMAIN-SUFFIX,aaplimg.com,Apple Services'
  - 'DOMAIN-SUFFIX,apple.co,Apple Services'
  - 'DOMAIN-SUFFIX,apple.com,Apple Services'
  - 'DOMAIN-SUFFIX,appstore.com,Apple Services'
  - 'DOMAIN-SUFFIX,cdn-apple.com,Apple Services'
  - 'DOMAIN-SUFFIX,crashlytics.com,Apple Services'
  - 'DOMAIN-SUFFIX,icloud-content.com,Apple Services'
  - 'DOMAIN-SUFFIX,icloud.com,Apple Services'
  - 'DOMAIN-SUFFIX,itunes.apple.com,Apple Services'
  - 'DOMAIN-SUFFIX,me.com,Apple Services'
  - 'DOMAIN-SUFFIX,mzstatic.com,Apple Services'

**Comment by wongkoo** [comment]
![image](https://user-images.githubusercontent.com/11880155/60479742-70641200-9cb9-11e9-92f1-58a5285847c3.png)

**Comment by Vdan123** [comment]
<img width="942" alt="屏幕快照 2019-07-02 11 40 12" src="https://user-images.githubusercontent.com/24421270/60481003-452ff180-9cbe-11e9-89c7-a13e92ac7c11.png">
where is config.yaml ?

**Comment by TristenChenTao** [comment]
> <img alt="屏幕快照 2019-07-02 11 40 12" width="942" src="https://user-images.githubusercontent.com/24421270/60481003-452ff180-9cbe-11e9-89c7-a13e92ac7c11.png">
> 
> where is config.yaml ?

/Users/yourname/.config/clash

**Comment by chuhaibo** [comment]
删除原来配置文件或者更改文件后缀名之后也无法使用

**Comment by leezhm** [comment]
> Just **delete config.yaml** and restart ClashX.
> 
> In [release note](https://github.com/yichengchen/clashX/releases) of 1.10.0
> 
> > Any error in default config file config.yaml would cause ClashX launch fail. If you are having problem on launch after upgrade to this version, consider to delete config.yaml and let ClashX auto create it.

It worked for me and many thx

**Comment by Baalvon** [comment]
我这里删除"~/.config/clash"里的config.yaml后问题解决

**Comment by yangningbo666** [comment]
@TristenChenTao It maybe that your [Proxy Group] don't have "PROXY".Check ?
```yaml
Proxy Group:
- { name: "PROXY", type: select, proxies: ['1', '2']}
```

**Comment by hilaryt999** [comment]
试了以上方法 均没解决
最后将mac格式化，重装后，再重新下载clash x可以用

**Comment by yichengchen** [comment]
新版加了自动删除旧的错误样例配置文件= =

**Comment by qiaoya95** [comment]
> 我这里删除"~/.config/clash"里的config.yaml后问题解决

删除了也不行= =

**Comment by qiaoya95** [comment]
> 我这里删除"~/.config/clash"里的config.yaml后问题解决

把所有的yaml文件删除就可以了耶，多谢
