### ISSUE TITLE
[Bug]?1.10版本DNS解析错误

### ISSUE THREAD

**Issue by wlhgtc** [yichengchen/clashX#173]
具体如下：
 公司有VPN,指定了特定网址时解析DNS的服务器。
![image](https://user-images.githubusercontent.com/16603773/60431443-68ad5a80-9c32-11e9-80bd-55b4000923bb.png)

在1.9版本，只要把公司的域名加入Doomestic策略组内里，即可正常访问
`- DOMAIN-SUFFIX,shannonai.com,Domestic`
但是在1.10版本时，无法网页访问该网址。
![image](https://user-images.githubusercontent.com/16603773/60431560-a4e0bb00-9c32-11e9-8aec-2e4eb897490b.png)
对DNS服务器的访问是没问题的，且ping网址也可通，但是无法网页访问。
看了ClashX的日志，错误如下：
`2019/07/01 19:03:43:361  [info] 127.0.0.1 --> git.shannonai.com match MATCH using Others
2019/07/01 19:03:44:295  [warning] Proxy[Others] connect [127.0.0.1 --> git.shannonai.com] error: All DNS requests failed
2019/07/01 19:03:45:287  [info] 127.0.0.1 --> git.shannonai.com match MATCH using Others
2019/07/01 19:03:46:235  [warning] Proxy[Others] connect [127.0.0.1 --> git.shannonai.com] error: All DNS requests failed`
Other 策略组为直接连接。
想问下是什么问题？

**Comment by wlhgtc** [comment]
@yichengchen

**Comment by beyondkmp** [comment]
> @yichengchen

把公司内网的dns服务器回到配置里面，就没有问题

**Comment by wlhgtc** [comment]
@beyondkmp  指的是写入配置文件中吗？

**Comment by beyondkmp** [comment]
是的 @wlhgtc

**Comment by wlhgtc** [comment]
@beyondkmp  thx

**Comment by zcong1993** [comment]
相同的问题

**Comment by wlhgtc** [comment]
如果是有托管，配置文件可能会随着更新而变化。
有什么方法可以直接读取原有的DNS吗？@yichengchen  
或者考虑下一个版本改动一下吗？@yichengchen 
thx！

**Comment by yichengchen** [comment]
> 如果是有托管，配置文件可能会随着更新而变化。
> 有什么方法可以直接读取原有的DNS吗？@yichengchen
> 或者考虑下一个版本改动一下吗？@yichengchen
> thx！

需要到 Clash Core 反馈哟~
