### ISSUE TITLE
1.10 内网站点有问题

### ISSUE THREAD

**Issue by eep2019** [yichengchen/clashX#174]
内网站点: github.xxx.com没更新前是正常。
更新后：
2019/07/03 09:45:30:087  [info] 127.0.0.1 --> github.xxx.com match DomainSuffix using DIRECT
2019/07/03 09:45:30:139  [warning] Proxy[DIRECT] connect [127.0.0.1 --> github.xxx.com] error: dial tcp 115.28.x.x:80: connect: connection refuse

为什么是访问了本地的ip。dns明明配置了一条，映射到内网的机器上的ip

**Comment by beyondkmp** [comment]
#173

**Comment by eep2019** [comment]
感谢
