### ISSUE TITLE
升级之后原来的配置都无法直接导入，重新导入之后又频繁报错

### ISSUE THREAD

**Issue by chuhaibo** [yichengchen/clashX#175]
请问如何解决？

**Comment by Skyepose** [comment]
我也遇到了同样的问题。

**Comment by Chandler-Lu** [comment]
关软件，删掉配置文件夹下默认的`config.yaml`，重新打开软件让软件生成，问题解决

**Comment by xinpengfei520** [comment]
非常感谢，解决了我的问题。

**Comment by bikun8901656** [comment]
> 关软件，删掉配置文件夹下默认的`config.yaml`，重新打开软件让软件生成，问题解决

确实有效果，删除之后就可以应用配置了。
