### ISSUE TITLE
打开某些网页会自动下载成html文件

### ISSUE THREAD

**Issue by FrankYip1020** [yichengchen/clashX#176]
好像没有规则的，某些网页会某些不会，关掉clash就正常
<img width="324" alt="Screenshot 2019-07-07 at 12 31 21 PM" src="https://user-images.githubusercontent.com/34473788/60764011-417fde80-a0b3-11e9-83e8-b06054f0a131.png">

**Comment by Chandler-Lu** [comment]
话说你是不是开了adguard

**Comment by FrankYip1020** [comment]
> 话说你是不是开了adguard

对的，他们有冲突吗？明天试试

**Comment by Chandler-Lu** [comment]
@FrankYip1020 Adguard 2.x版本有 bug，我已经提交 issue 给他们了。
这个版本导致网页乱码或者自动下载页面文件，尤其是对于非 https 网页。
https://github.com/AdguardTeam/CoreLibs/issues/986
https://github.com/AdguardTeam/CoreLibs/issues/951
我估计这个 bug 修好还要挺久，建议退回 [1.5.14](https://github.com/AdguardTeam/AdguardForMac/releases/download/v1.5.14/Adguard-1.5.14.release.dmg)，这个问题我这边测试应该无关于 clash

**Comment by FrankYip1020** [comment]
> @FrankYip1020 Adguard 2.x版本有 bug，我已经提交 issue 给他们了。
> 这个版本导致网页乱码或者自动下载页面文件，尤其是对于非 https 网页。
> [AdguardTeam/CoreLibs#986](https://github.com/AdguardTeam/CoreLibs/issues/986)
> [AdguardTeam/CoreLibs#951](https://github.com/AdguardTeam/CoreLibs/issues/951)
> 我估计这个 bug 修好还要挺久，建议退回 [1.5.14](https://github.com/AdguardTeam/AdguardForMac/releases/download/v1.5.14/Adguard-1.5.14.release.dmg)，我这边的测试显示这个问题无关于 clash

噢噢原来是这样，你这么说这个问题好像的确是我在升级了adguard之后才出现，那我降回去应该就可以了，谢啦

**Comment by Chandler-Lu** [comment]
没事～我一开始也一脸懵逼- -后来发现 adgurad 那边提交类似问题的人还不少，才发现原来是 adguard 的问题

**Comment by Chandler-Lu** [comment]
对了，如果你有自己配置的规则的话，记得先备份再回退

**Comment by FrankYip1020** [comment]
> 对了，如果你有自己配置的规则的话，记得先备份再回退

OK～

**Comment by Chandler-Lu** [comment]
2.1.2好像没这个问题了，可以试试：https://github.com/AdguardTeam/AdguardForMac/releases

**Comment by FrankYip1020** [comment]
好，我试试，谢谢跟进哈～

On 16 Aug 2019, at 9:13 AM, whatGhost <notifications@github.com<mailto:notifications@github.com>> wrote:


2.1.2好像没这个问题了，可以试试：https://github.com/AdguardTeam/AdguardForMac/releases
