### ISSUE TITLE
[Feature Request] 希望可以对订阅的配置文件进行合法性校验

### ISSUE THREAD

**Issue by Chandler-Lu** [yichengchen/clashX#177]
有时候订阅服务器由于各种原因，下载的文件并不是需要的 config，而是 404 页面，或者是其他错误的网页代码，同时，原 config 文件会被覆盖，导致 config 异常，无法正常使用。
因此希望对从订阅服务器下载下来的文件进行合法性校验，如果可以通过验证，才覆盖原 config，否则丢弃

**Comment by yichengchen** [comment]
已添加
