### ISSUE TITLE
从睡眠中恢复后偶发系统代理配置错误

### ISSUE THREAD

**Issue by geekdada** [yichengchen/clashX#179]
系统：10.14.5
ClashX 版本：Latest

有自定义 `proxyIgnoreList.plist`，不过看截图的样子都没有正确配置。确定没有其他代理软件影响。

![image](https://user-images.githubusercontent.com/3274850/61053196-ad4da880-a41f-11e9-9e5d-65892aacd224.png)

**Comment by yichengchen** [comment]
理论上休眠恢复后不会主动设置代理的，是重新点了设为系统代理后发生的吗？

**Comment by geekdada** [comment]
啥都没点。貌似是从最近的版本开始的。

**Comment by ky0nch3ng** [comment]
@yichengchen 

socks5 proxy port setting is wrong

```
port: 8886
socks-port: 8888
redir-port: 8887
```

In clash proxy displays socks port setting is `0`.

**Comment by ky0nch3ng** [comment]
![](https://i.imgur.com/LEzsFGh.png)
