### ISSUE TITLE
每次或打开都会把我的PAC配置都清空，源码怎么修改下，不要清理我的配置呢。只set三个http https 和 socks5

### ISSUE THREAD

**Issue by sunht6** [yichengchen/clashX#180]
RT 在公司每次打开 Clashx和退出都会 清空我的PAC配置，每次都要执行以下 alisa 有点麻烦。
alias gs='networksetup -setautoproxyurl  "USB 10/100 LAN" "http://127.0.0.1:100/proxy.pac"'

源码里怎么修改下 可以保留我的PAC配置呢

**Comment by yichengchen** [comment]
pac的作用是什么呢

**Comment by yichengchen** [comment]
可能要设置代理时备份原有配置

**Comment by XiaoTeemo** [comment]
不要勾选 "设置为系统代理"

**Comment by sunht6** [comment]
> pac的作用是什么呢

pac是网易云的那个解锁灰色歌曲的，现在发现退出也会清空所有proxy的配置。

**Comment by yichengchen** [comment]
其实你可以吧网易云的规则加到clash规则里

**Comment by yichengchen** [comment]
Done in master branch
