### ISSUE TITLE
reload config fail 是为什么？？

### ISSUE THREAD

**Issue by Frank1e0927** [yichengchen/clashX#181]
![image](https://user-images.githubusercontent.com/17680956/61432938-900b6380-a964-11e9-876c-1814afed7d9a.png)

**Comment by Frank1e0927** [comment]
版本是1.10.0

**Comment by Frank1e0927** [comment]
![image](https://user-images.githubusercontent.com/17680956/61442972-2b0f3800-a97b-11e9-88f1-0e9fb01d05d8.png)


![image](https://user-images.githubusercontent.com/17680956/61442989-2fd3ec00-a97b-11e9-90e9-69c289fe57c6.png)

**Comment by Frank1e0927** [comment]
求助

**Comment by Chandler-Lu** [comment]
https://github.com/yichengchen/clashX/issues/175#issuecomment-508996874

**Comment by Frank1e0927** [comment]
我发现这个好像没啥用，其实是我的服务器运营商的问题。

我总是set subscribe url 的时候download fail

原因是因为：我请求的太频繁导致了谷歌触发了人机验证...返回的yaml填充进去了一个谷歌验证的html页面文本

后来我用其他方法把数据拿回来重新填充就好了。
