### ISSUE TITLE
程序退出之后，不保存自定义的sock port和http port

### ISSUE THREAD

**Issue by SgtDaJim** [yichengchen/clashX#182]
在自定义配置文件中，设置了自定义的sock port和http port，但程序启动之后不会修改为配置文件中定义的port，而是保持为7890和7891。在控制台修改之后，退出程序，再启动，端口配置再次还原为7890和7891。这种逻辑不符合常规。

clashX version: 1.10.0

**Comment by yichengchen** [comment]
控制面板修改不会生效 只有在 config.yaml 中修改会生效。后续考虑关闭控制面板修改端口功能

**Comment by SgtDaJim** [comment]
一定要是config.yaml？不能是自定义的配置文件？

**Comment by chinanoahli** [comment]
> 一定要是config.yaml？不能是自定义的配置文件？ @yichengchen

同问，手动指定的yaml没有起作用，每次重启都要手动更改设置。
