### ISSUE TITLE
Mac OS 10.15无法打开Clashx.dmg

### ISSUE THREAD

**Issue by lucky0l** [yichengchen/clashX#184]
Mac OS 10.15无法打开Clashx.dmg，一打开就提示:

无法打开“ClashX.dmg”，因为Apple无法检查其是否包含恶意软件。
此软件需要更新。请联系开发者了解更多信息。
“Safari浏览器”于今天22:20从“github-production-release-asset-2e65be.s3.amazonaws.com”下载了此文件。

Mac OS 10.15 PB3

**Comment by yichengchen** [comment]
暂时没有10.15的机子测试 其他网站下的其他dmg没有问题吗

**Comment by yichengchen** [comment]
10.15需要对app进行Notarization操作，会在之后的打包流程中添加

**Comment by lucky0l** [comment]
@yichengchen 其他网站下的有些没问题，有的也有问题，但是大部分官网上下载的都没有这个问题。

**Comment by yichengchen** [comment]
已在ci添加Notarization配置 08b9ac7 会在今日发布 如果还有问题再打开次issue
