### ISSUE TITLE
bug反馈和一个问题

### ISSUE THREAD

**Issue by Chandler-Lu** [yichengchen/clashX#185]
## bug
当我在该界面手动进行更新并更新成功时
![WX20190729-104236](https://user-images.githubusercontent.com/18322610/62018534-aa0f3680-b1ed-11e9-850d-27be98bf6f33.png)
首先提示
![屏幕快照 2019-07-29 10 42 18](https://user-images.githubusercontent.com/18322610/62018569-c6ab6e80-b1ed-11e9-8466-138627e39e21.png)
关闭上述配置文件窗口后，提示
![屏幕快照 2019-07-29 10 42 08](https://user-images.githubusercontent.com/18322610/62018570-c7440500-b1ed-11e9-9eb1-8d8ebaf6ca69.png)
不知道此处是 bug 还是 feature，按理说更新后已经重载过了，为什么还会提示手动重载呢？

## 问题
当点击 配置->托管配置->更新 时，日志如下
```
2019/07/29 10:45:41:506  [info] [Auto Upgrade] Bypassing a.com due to time check
2019/07/29 10:45:41:506  [info] [Auto Upgrade] Bypassing b.com due to time check
```
看日志的意思应该是没有到自动更新时间所以跳过？所以想请问一下 feature 应该是每 12 小时自动更新吧，那这个“更新”按钮放在这里应该是没有意义的？
谢谢～

**Comment by yichengchen** [comment]
1 是bug 不过影响不大，下个版本可能解决
2 提供一个手动更新的入口（不受时间限制）

**Comment by Chandler-Lu** [comment]
可是 2 好像点击后没有什么实际意义，配置并不会更新

**Comment by yichengchen** [comment]
> 可是 2 好像点击后没有什么实际意义，配置并不会更新

会的啊

**Comment by Chandler-Lu** [comment]
ClashX 1.10.1
可以确定配置了两个可用的托管链接，删掉配置目录下对应的文件，点击更新，没有实际效果。
![2019-07-29 12 16 44](https://user-images.githubusercontent.com/18322610/62021661-e8f7b900-b1fa-11e9-9f3f-3717916bca7f.gif)

**Comment by Chandler-Lu** [comment]
第一行：clash 1.10.0 点击“更新”按钮时发起的连接
第二行：clash 1.10.1 开启时发起的连接
clash 1.10.1 手动点击“更新”按钮时没有任何连接发起
![WX20190729-122323](https://user-images.githubusercontent.com/18322610/62021799-b0a4aa80-b1fb-11e9-8d29-1470497a70d6.png)

**Comment by wlhgtc** [comment]
@yichengchen  似乎我重载配置文件这个功能也失效了，我修改后的配置文件并没有生效？

**Comment by wlhgtc** [comment]
@beyondkmp 想问下你有这个问题吗？

**Comment by Chandler-Lu** [comment]
重载配置我还是没问题的

**Comment by wlhgtc** [comment]
> 重载配置我还是没问题的
我是改了配置文件的一些策略，然后重载不生效。 @Chandler-Lu 可以帮我测试一下吗？

**Comment by yichengchen** [comment]
> 第一行：clash 1.10.0 点击“更新”按钮时发起的连接
> 第二行：clash 1.10.1 开启时发起的连接
> clash 1.10.1 手动点击“更新”按钮时没有任何连接发起
> ![WX20190729-122323](https://user-images.githubusercontent.com/18322610/62021799-b0a4aa80-b1fb-11e9-8d29-1470497a70d6.png)

已确认并修复 感谢提交
