### ISSUE TITLE
Mac OS 10.15 无法自动更新

### ISSUE THREAD

**Issue by elementlo** [yichengchen/clashX#187]
![image](https://user-images.githubusercontent.com/10020581/62178733-b07fe880-b37c-11e9-9348-7cb77366336d.png)
如图, 使用内置更新1.10.2时出现, 我看1.10.2还没有在release中.

**Comment by gssdromen** [comment]
same issue here

**Comment by Boycottangent** [comment]
10.14.6 尝试升级1.10.2时同样问题，应该不是macOS的问题？

**Comment by Baalvon** [comment]
macOS 10.3.6遇到相同问题。不过老大刚更新了1.10.3但没有提供dmg，可能老大还在调试。

**Comment by yichengchen** [comment]
昨天ci打的包邮问题 删掉了 现在应该好了
