### ISSUE TITLE
每次重開都要打管理員權限

### ISSUE THREAD

**Issue by samymyue** [yichengchen/clashX#191]
詳細內容見圖，不管是重啓電腦還是退出APP再次打開，點擊安裝並且輸入密碼確定，然後退出並再次打開應用就會彈如下框
<img width="409" alt="58179665-39bed300-7cdb-11e9-905a-dd9e90e77427" src="https://user-images.githubusercontent.com/49505642/62422824-1527a400-b6eb-11e9-8ea5-c3a9499d43aa.png">

**Comment by yichengchen** [comment]
备份配置后 执行 rm -r ~/.config/clash/ 然后重启试试？

**Comment by samymyue** [comment]
都是有問題

**Comment by yichengchen** [comment]
check this one https://github.com/yichengchen/clashX/releases/tag/1.10.5

**Comment by samymyue** [comment]
用了 beta 問題解決了 感謝
