### ISSUE TITLE
自己设置的规则不生效

### ISSUE THREAD

**Issue by baixiaodong** [yichengchen/clashX#193]
自己增加的规则不生效，并且会被自动清除

**Comment by DoubleAngle** [comment]
我也发现升级到最新版之后，自定义规则已经没法使用了

**Comment by baixiaodong** [comment]
> 我也发现升级到最新版之后，自定义规则已经没法使用了

我自定义的规则主要是为了让一些站点不走代理，目前已经解决了。 https://github.com/yichengchen/clashX。 搜索 Change default system ignore list. ， 在~/.config/clash/proxyIgnoreList.plist 增加自己忽略的配置试试

**Comment by yichengchen** [comment]
自定义规则是啥。。。。。

**Comment by yichengchen** [comment]
啥叫没法使用。。。。

**Comment by harryzjm** [comment]
@yichengchen 你好 能不能把Proxy 和 Rule分开 这样 更新Proxy的同时 不会变更自定义Proxy

**Comment by BigInventor** [comment]
> @yichengchen 你好 能不能把Proxy 和 Rule分开 这样 更新Proxy的同时 不会变更自定义Rule

确实存在这个问题

**Comment by zhangnew** [comment]
> @yichengchen 你好 能不能把Proxy 和 Rule分开 这样 更新Proxy的同时 不会变更自定义Rule

我是这样做的，自己用 subconverter 做一个订阅转换，然后就可以自己在 subconverter 里面维护规则，不知道有没有更好的方案

**Comment by BigInventor** [comment]
> > @yichengchen 你好 能不能把Proxy 和 Rule分开 这样 更新Proxy的同时 不会变更自定义Rule
> 
> 我是这样做的，自己用 subconverter 做一个订阅转换，然后就可以自己在 subconverter 里面维护规则，不知道有没有更好的方案

感觉有点复杂，不过还是感谢你提供思路
