### ISSUE TITLE
配置读取bug，http proxy端口绑定冲突导致API Connect Error

### ISSUE THREAD

**Issue by sunlianqiang** [yichengchen/clashX#194]
本人的问题解决了，是7890端口被占用了！但是clashx本身也有问题。
我的问题。我把clash代码拉下来跑了一下，发现clash端口绑定有问题，7890端口已被占用！在配置clash的时候我仍然开着ss，为了方便使用，ss的http proxy也是7890，和clash默认配置冲突了。ss程序中选择”关闭Shadowsocks“选项，端口仍然在绑定状态。
clashx的问题：

1. clashx启动时会读取config.yaml配置里http proxy的端口，而不是我试用的机场的配置dler.cloud.yaml里的http端口1234，启动后显示的配置是我选定的dler.cloud.yaml配置文件，导致我没有考虑config.yaml的配置。这个规则避免了使用机场托管配置导致配置被覆盖的问题，但是希望能有地方予以说明。
2.配置读取有些混乱之外，端口被占用也没有提示，导致一个小bug查了半天。
2. 在clashx控制台里http proxy端口可以编辑，但是不生效，以为是我自己环境的问题。~~建议改为只读，或者增加修改功能。~~ 又试了一下，是可以修改的，但是修改成功与否没有提示。

![image](https://user-images.githubusercontent.com/5087190/62870205-cfeb1e00-bd4b-11e9-988b-6e02bd40da0f.png)

2019.8.12 night
---------------------------
版本：1.10.3
现象：

1. 工具栏显示 API Connect Error
2. 配置重新加载不生效，重启客户端后生效
3. 控制台上可以测速，选择节点，但是不能更改外部控制设置的端口、http代理端口等配置
4. 一开始使用自己搭建的服务器，后来改用托管配置，都没有变化
5. restful API 正常
```
curl http://127.0.0.1:9090/configs         
{"port":0,"socks-port":7891,"redir-port":0,"authentication":[],"allow-lan":false,"mode":"Rule","log-level":"info"}
```

![image](https://user-images.githubusercontent.com/5087190/62851554-18d5af00-bd19-11e9-8052-44ddeea2261b.png)
![image](https://user-images.githubusercontent.com/5087190/62852426-f5603380-bd1b-11e9-81e6-d5625615e624.png)

**Comment by Chandler-Lu** [comment]
端口应该是以托管的配置文件为准的

**Comment by sunlianqiang** [comment]
> 端口应该是以托管的配置文件为准的

修改配置的端口external-controller: 0.0.0.0:1234，重启clashx也没有生效，还是绑定在原端口上

**Comment by sunlianqiang** [comment]
问题解决了，是7890端口被占用了！但是clashx本身也有问题。
1.我的问题。我把clash代码拉下来跑了一下，发现clash端口绑定有问题，7890端口已被占用！在配置clash的时候我仍然开着ss，为了方便使用，ss的http proxy也是7890，和clash默认配置冲突了。
2. clashx的问题。clashx启动时会读取config.yaml配置里http proxy的端口，而不是机场的配置dler.cloud.yaml里的http端口1234。配置读取有些混乱，端口占用也没有提示。
3. 在clashx控制台里不能修改http proxy端口。


![image](https://user-images.githubusercontent.com/5087190/62868409-2ce4d500-bd48-11e9-9d0c-0c6493cb618b.png)

**Comment by yichengchen** [comment]
所有端口配置要通过 config.yaml 进行配置

**Comment by hexd2019** [comment]
遇到同样的问题，ss关了也解决不了，请教上面这位怎么解决的，谢谢！

**Comment by hexd2019** [comment]
多说一句：我用最早的版本就不会有api的问题，所以是升级后产生的，谢谢你

**Comment by hexd2019** [comment]
感谢您很勤奋的的更新，beta装上之后没有解决api的问题。和上次的问题一样，所以我装回1.9,老版本格式不一样，但改一下尾缀就可以，只是1.9测速就退出的问题经常发生。总的来说这个软件很不错，希望您进一步完善。

**Comment by yichengchen** [comment]
> 多说一句：我用最早的版本就不会有api的问题，所以是升级后产生的，谢谢你

因为1.9生成的config.yml里面的端口好不一样吧 你改一下config.yml的端口就好了

**Comment by hexd2019** [comment]
>因为1.9生成的config.yml里面的端口好不一样吧 你改一下config.yml的端口就好了
谢谢你的指点。端口和最新版本端口一样的，没有问题。这个1.9的版本每逢测速退出可能和vess节点有关，因为导入ssr的节点测速，很稳定不退出，而测v2ray格式的节点几乎每次都退出，控制台显示刚测几个就退出了，很有趣现象。

**Comment by hexd2019** [comment]
谢谢您的指点。端口和最新版本端口一样的，没有问题。这个1.9的版本每逢测速退出可能和vmess节点有关，因为导入ssr的节点测速，很稳定不退出，而测v2ray格式的节点几乎每次都退出，控制台显示刚测几个就退出了，很有趣现象。

**Comment by sunlianqiang** [comment]
> 谢谢您的指点。端口和最新版本端口一样的，没有问题。这个1.9的版本每逢测速退出可能和vmess节点有关，因为导入ssr的节点测速，很稳定不退出，而测v2ray格式的节点几乎每次都退出，控制台显示刚测几个就退出了，很有趣现象。

你看下那个端口被占用了，或者换个别个端口。测速退出是什么意思，测速会导致软件崩溃吗？

**Comment by QiQiBiBi** [comment]
因为重启电脑时正版SS也一起启动，都是同一个端口，所以现在也提示 api error 了，并且怎么去改设置文件 + 重载 + 关掉再开 都还是显示那个错误。
代理没有问题，选的哪个就还继续能用，并且在控制台也能切换，但在外部菜单上就一直显示那个错误并且无法在菜单切换服务器。

后来是在配置夹里把我自定义的移走，重开clashX加载默认就正常了，接着把自定义配置移回去 + 使用，正常。
