### ISSUE TITLE
ClashX 与 macOS 邮件客户端冲突

### ISSUE THREAD

**Issue by realslimsea** [yichengchen/clashX#196]
你好，感谢你的贡献和付出。ClashX使用体验很好，就是有一个小问题不知该如何解决，在不翻墙或者用 ShadowsocksX NG-R8时，macOS 的自带邮件客户端的 iCloud 邮箱收发都没有问题。但是在使用 ClashX时，就会无法连接，显示“通过默认端口连接到服务器“p59-imap.mail.me.com”超时”，请问该如何设置？谢谢！

**Comment by Chandler-Lu** [comment]
`p59-imap.mail.me.com`加直连，不要配置 dns 设置不然貌似部分 apple 的服务会有问题

**Comment by yichengchen** [comment]
应该是代理的问题吧。。。没遇到过。。
