### ISSUE TITLE
[ENHANCEMENT] Restore original system proxy settings after disabling clash as system proxy 

### ISSUE THREAD

**Issue by vtta** [yichengchen/clashX#197]
In surge, if system proxy settings have already been set before enabling surge as system proxy those settings would be saved and restored after disabling surge.
But in clashX original system proxy settings would be ignored and wouldn't be restored upon disabling.
It's a bit annoying to have to manually type all those settings back, so I wish clashX could have the same behavior as surge upon toggling system proxy setting.

**Comment by yichengchen** [comment]
relate to https://github.com/yichengchen/clashX/issues/180

**Comment by yichengchen** [comment]
Done in master branch
