### ISSUE TITLE
macOS Mojave App Store 异常

### ISSUE THREAD

**Issue by Tsahao** [yichengchen/clashX#2]
开启代理后，App Store 部分应用无法下载 商店地区为HK 系统版本为 DP6
测试发现问题的有以下两个
https://itunes.apple.com/cn/app/spark-love-your-email-again/id1176895641?l=en&mt=12
https://itunes.apple.com/cn/app/toolbox-for-keynote-templates/id582635628?l=en&mt=12
https://itunes.apple.com/cn/app/autodesk-sketchbook/id863486266?l=en&mt=12

提示为：未知错误 项目暂时不可用
将代理规则修改为“FINAL,,DIRECT”仍然会出错
关闭代理后一切正常

Shadowsocks-X-NG 全局代理正常

**Comment by yichengchen** [comment]
问题已知晓，与Clash作者讨论后确实发现appstore下载某些应用会出现问题。麻烦同时提一个issue在Clash https://github.com/Dreamacro/clash/issues 。 clashX目前仅负责对clash项目Mac下的UI封装

**Comment by yichengchen** [comment]
https://github.com/Dreamacro/clash/issues/3

**Comment by yichengchen** [comment]
[go.tar.gz](https://github.com/yichengchen/clashX/files/2871852/go.tar.gz)
We using this fix go instead of official go to build clashX
