### ISSUE TITLE
apple.com/hk 无法访问

### ISSUE THREAD

**Issue by Tsahao** [yichengchen/clashX#20]
无论什么模式
Safari apple.com 可以访问 加了地区就不能访问 无论是 apple.com/cn /hk /us

添加 www. 后正常
关闭代理后正常
Chrome 正常

**Comment by yichengchen** [comment]
可复现 研究中

**Comment by yichengchen** [comment]
clash上游已修复 将跟随发布新版本

**Comment by Tsahao** [comment]
感谢，好快

**Comment by yichengchen** [comment]
Fixed in 1.3.5
