### ISSUE TITLE
proxyIgnoreList.plist 在升级到 1.10.5 后位置被移动

### ISSUE THREAD

**Issue by raychow** [yichengchen/clashX#200]
代理似乎是由 /Library/PrivilegedHelperTools/com.west2online.ClashX.ProxyConfigHelper 这个特权进程设置的, 这个进程获取到的用户根目录在 /var/root, 因此现在文件要放在 /var/root/.config/clash 下面才能识别出来了.

**Comment by yichengchen** [comment]
...bug 下个版本修

**Comment by raychow** [comment]
另外希望能加入由 config.yaml 来配置的全局忽略代理功能, 系统的忽略代理设置的功能不太灵活.

应用级别的白名单, 或者是一个比托管配置更高优先级的策略, 都可以.

**Comment by yichengchen** [comment]
@raychow Clash core 不支持这种操作所以无法实现
