### ISSUE TITLE
icon 问题

### ISSUE THREAD

**Issue by Pro-ima** [yichengchen/clashX#202]
Hello 啊 ， 我不知道是我的电脑还是什么问题，
但是我从升级 developer beta 开始， icon就不能正常显示....

原谅我一个强迫症患者真的忍不住了。 

虽然是个不是很要紧的问题
![ClashX Bar Icon](https://user-images.githubusercontent.com/51689741/63401816-4c949100-c40b-11e9-908c-d7fa14badd0d.png)

**Comment by yichengchen** [comment]
10.15 吗

**Comment by Pro-ima** [comment]
对， 我现在是 Beta 6. 但是其实第一版升级时候就有这个问题了。

**Comment by baiy** [comment]
我的也是 不过等一会就好了 至少出现过三次
系统 10.15 beta 5

**Comment by Pro-ima** [comment]
> 我的也是 不过等一会就好了 至少出现过三次
> 系统 10.15 beta 5

可是我的一只都这样.......没变过......

**Comment by elementlo** [comment]
same issue, 也可能是macOS的问题.
