### ISSUE TITLE
能否添加一个全局白名单功能/配置文件

### ISSUE THREAD

**Issue by baiy** [yichengchen/clashX#204]
由于使用的是机场节点订阅服务,无法在配置文件中添加相关的Rule,
能否添加一个全局白名单功能/配置文件,在白名单中的不走代理
方便在使用全局模式可以过滤掉内网域名和ip

**Comment by wangjunwei87** [comment]
同求，类似于 no_proxy 的配置？
公司内网的域名不要走代理，有时候走代理打不开。

**Comment by yichengchen** [comment]
目前可以参照 Readme 中的 Change default system ignore list. 方法修改系统代理中绕过的地址 不过不是很智能， 当前1.10.5版本中 home目录是 /root/.config  要下个版本修复

**Comment by baiy** [comment]
@yichengchen  优秀
