### ISSUE TITLE
端口似乎并不按照配置文件是所写的设置？

### ISSUE THREAD

**Issue by chinanoahli** [yichengchen/clashX#208]
我的配置文件如下：
```
port: 8080
socks-port: 1080
allow-lan: false
mode: Rule
log-level: warning
external-controller: 127.0.0.1:9090
```

但是每次打开clashX，http端口都会被配置到7890，而socks端口会被配置到7891，请问是什么情况？
我电脑配置了防火墙，拒绝了大部分端口的连线，每次打开都要重新打开gui控制台修改端口。
这个问题持续了好几个版本了。

**Comment by yichengchen** [comment]
修改配置文件文件夹中的config.yaml 文件里面的端口号
