### ISSUE TITLE
开机自启动关闭软件后，重新启动工具栏无 ClashX 图标

### ISSUE THREAD

**Issue by CheYuZhiZhi** [yichengchen/clashX#210]
设备：MacBook Pro Mid 2015 15-inch
系统：macOS 10.14.6 (18G87)
软件：ClashX v1.10.5
ClashX 我是设为开机自启动的，由于一些原因部分情况下需要退出软件。当我重新启动软件后，工具栏无 ClashX 图标以支持进行更改操作。重复退出再启动操作仍无法使得工具栏出现 Clash 图标。

**Comment by CheYuZhiZhi** [comment]
v1.10.6 中仍存在该问题。

**Comment by yichengchen** [comment]
不能理解 是不能开机启动吗 没有图标是什么意思

**Comment by CheYuZhiZhi** [comment]
<img width="529" alt="Jietu20190901-123656@2x" src="https://user-images.githubusercontent.com/31441866/64071845-af144980-ccb5-11e9-9303-f3972cc5a2c4.png">
意思是 ClashX 是设为开机自启动的，当我关闭软件再次手动启动后，工具栏不再出现图标。

**Comment by Chandler-Lu** [comment]
看你通知中心旁边的图标应该是 bartender 吧，bartender 对某些开机自启的软件图标控制有问题，你可以看看 clashx 是不是被收在 bartender 内部了。通常这种情况要么等它自己复位，要么就 kill 进程重新打开。
当然 bartender 还有几率把图标弄丢，就是进程还在，但是图标哪都没。那就只能 kill 然后重启

**Comment by Chandler-Lu** [comment]
![WX20190901-134409](https://user-images.githubusercontent.com/18322610/64072296-9a887f00-ccbe-11e9-8da3-e7689ea7ae77.png)
你可以检查一下确定 clashx 已经启动但是无图标的时候，bartender 控制中心的 clashx 位置是不是有感叹号

**Comment by CheYuZhiZhi** [comment]
确实是 Bartender 的问题欸，被收在内部了，双击三个点之后就图标就复现了。多谢 ：）

**Comment by Chandler-Lu** [comment]
好嘞，反正开了 bartender 以后，菜单栏的图标问题都甩给 bar 就对了233

**Comment by yichengchen** [comment]
😂😂😂😂
