### ISSUE TITLE
切换服务器地址不会立刻改变

### ISSUE THREAD

**Issue by easonjim** [yichengchen/clashX#211]
切换服务器地址不会立刻改变，还是原来的服务器，规则切换从全局改成直连，还是没有改变，使用的是全局。请问这个问题需要怎么解决？

**Comment by Chandler-Lu** [comment]
你要确定一下不是你那个网站的缓存问题。。

**Comment by easonjim** [comment]
@Chandler-Lu 非常确定不是缓存，你可以测试一下：
1、服务器列表多台服务器
2、切换为全局，并访问ipip.net
3、切换服务器1，查看IP
4、切换服务器2，查看IP

目前解决方法为：
每次切换服务器，关闭软件，再重新打开。

**Comment by Chandler-Lu** [comment]
@easonjim 我测试了一下，好像确实没有问题。。每次切换以后清浏览器缓存再次访问，ip显示是对的

**Comment by yichengchen** [comment]
clash core 不会打断当前已建立的连接 所以可能导致这个情况 如果重启浏览器或新tab就可以看到新的。 这个要clash core做了连接管理器后才会实现 优先级在tun之后短期不会做

**Comment by easonjim** [comment]
@yichengchen 短期的方案，可以这样实现：重新kill掉原来进程，重新启用新的进程，因为我看你的实现方式是UI与连接进程是分开的，那么此时能否kill连接进程，然后重新启动一个。

**Comment by easonjim** [comment]
> @easonjim 我测试了一下，好像确实没有问题。。每次切换以后清浏览器缓存再次访问，ip显示是对的

你这个思路不对吧，我一次开了几十个tab，每个tab有很多业务登录态，清除缓存那我这些登录态要重新登录一次，不太现实吧。

**Comment by Chandler-Lu** [comment]
> > @easonjim 我测试了一下，好像确实没有问题。。每次切换以后清浏览器缓存再次访问，ip显示是对的
> 
> 你这个思路不对吧，我一次开了几十个tab，每个tab有很多业务登录态，清除缓存那我这些登录态要重新登录一次，不太现实吧。

我只是说用这个来排除缓存的问题，没说实际上要这样使用
