### ISSUE TITLE
Bug report for version 1.10.6

### ISSUE THREAD

**Issue by sydney0zq** [yichengchen/clashX#213]
Firstly thanks for your contribution. In the version of 1.10.6, I  find several critical problems as follows:

- I cannot change the config file in the toggle menu bar, the software always choose `~/config/clash/config.yaml` which is just a template for extended configurations
- API load error, I am not clear about what is this

So that I roll back to 1.10.5. My system is macOS Catalina 10.15 Beta (19A536g). Thanks.

**Comment by yichengchen** [comment]
`API load error ` means clash core can not be started, casing clashx can not control config file selection. This usually happen when config.yaml has incorrect settings. Try to delete config.yaml manually and restart clashx

**Comment by sydney0zq** [comment]
Thanks for your reply. Minutes ago I tried to re-update clashX to ver 1.10.6. And it just works well, which is very strange. Anyway this wonderful software works fine and this small bug maybe negligible.
