### ISSUE TITLE
可以添加选择关闭自动测试节点延迟(Auto-Urltest)的选项吗

### ISSUE THREAD

**Issue by ang830715** [yichengchen/clashX#214]
有些网络比如校园网，设备的ip不是固定的，如果对所有节点进行一轮测试，会使用许多不同ip，触发设备数量限制，引发风控，谢谢。

**Comment by yichengchen** [comment]
可以自定义多个配置文件 把urltest组删除

**Comment by ang830715** [comment]
大佬你好 那这样做后每次跟随上游更新都要重新删除一次urltest组吗
