### ISSUE TITLE
dashboard中日志不显示内容

### ISSUE THREAD

**Issue by zt900403** [yichengchen/clashX#215]
你好，我的dashbaoard中日志不显示规则匹配的内容了，一直打开着用多久都是空白。
![image](https://user-images.githubusercontent.com/7888336/64219361-c5a9e300-cef7-11e9-8744-7f6c515ecb0f.png)

设置用的是规则模式，日志等级也是warnning

![image](https://user-images.githubusercontent.com/7888336/64219483-3c46e080-cef8-11e9-8f6f-afe774c8de7d.png)

版本是最新的1.10.6

感谢您的工作，谢谢。

**Comment by yichengchen** [comment]
试试日志等级info或者debug

**Comment by zt900403** [comment]
更改日志等级不行，重新安装clashx也不行，我吧～/.config/clash删掉重新打开软件后，日志恢复正常。

**Comment by bang919** [comment]
我这边是打开.yaml，然后log-level: silent改成log-level: info
