### ISSUE TITLE
复制终端代理命令错误

### ISSUE THREAD

**Issue by xmatwh** [yichengchen/clashX#219]
选择复制终端代理命令后，结果为：
export https_proxy=http://127.0.0.1:7890;export http_proxy=http://127.0.0.1:7890;export all_proxy=socks5h://127.0.0.1:7891
socks5 后多了一个h，我就奇怪为啥开了代理还半天都更新不动，原来命令错了。。

**Comment by yichengchen** [comment]
https://github.com/urllib3/urllib3/issues/1035

sock5h是对的
