### ISSUE TITLE
打开之后，无限通知

### ISSUE THREAD

**Issue by magaofei** [yichengchen/clashX#22]
![image](https://user-images.githubusercontent.com/3363787/45011171-c3424e00-b043-11e8-9eb1-fe9cff258933.png)
![image](https://user-images.githubusercontent.com/3363787/45011173-c63d3e80-b043-11e8-9529-5d1f38e08e94.png)

不能自动创建 `~/.config/clash/config.ini` 吗

**Comment by yichengchen** [comment]
This is a bug in the latest Clashx when config.ini is incorrect . You can use older version of clashX or copy a vaild config file into config folder to fix it now. 

It would be fixed in next version recently.
