### ISSUE TITLE
1.10.7哪去了？

### ISSUE THREAD

**Issue by 404cn** [yichengchen/clashX#221]
下着下着404了

**Comment by trysh** [comment]
![image](https://user-images.githubusercontent.com/4084529/65024621-cdda3780-d967-11e9-97de-f9ce3d22242a.png)
同

**Comment by Chandler-Lu** [comment]
有bug，节点切换有问题

**Comment by lcl2539** [comment]
emmm,那能不能更新下brew

**Comment by Chandler-Lu** [comment]
> emmm,那能不能更新下brew

已经提交了，其实brew每个人都可以直接pr的

**Comment by Chandler-Lu** [comment]
已更新

**Comment by ne1llee** [comment]
> 已更新

1.10.7  url-test自动切换没法用啊
