### ISSUE TITLE
无法订阅的自己 在谷歌云的建的V2ray节点

### ISSUE THREAD

**Issue by valens7** [yichengchen/clashX#222]
RT
![image](https://user-images.githubusercontent.com/35646496/65232394-a61fd680-db03-11e9-8a2e-6fcf8bed1705.png)
![image](https://user-images.githubusercontent.com/35646496/65232421-b1730200-db03-11e9-89f3-fdf4d80a9f1f.png)

**Comment by Chandler-Lu** [comment]
至少提供一下订阅链接或者屏蔽重要信息的base64编码吧？扔俩图鬼知道什么情况。。

**Comment by valens7** [comment]
已解决，谢谢~
