### ISSUE TITLE
How to test the Url matching?

### ISSUE THREAD

**Issue by sydney0zq** [yichengchen/clashX#223]
For example, if I have some domain xxx.com, I want to know clashX will choose which proxy. I tried to use log provided in clashX, however, it is slow and inconvenient. 

Could you please tell me how to test it, or some script to check it in other repos? Or could you give me some advices?

Thanks a lot.

**Comment by sydney0zq** [comment]
To be specify, given a url name, how could we know (in any means) its used dns server, its proxy path? It is possible to embed such a utility in clashX or separate as a individual useful tool?

**Comment by yichengchen** [comment]
i use the log..... set log level to debug can get a little more logs about the dns. currently  clash core does not provide so much log to do this. 

clash core may provide stream api in the near feature to allow us to do that.
