### ISSUE TITLE
日志等级是error。info还是会输出

### ISSUE THREAD

**Issue by dsky1990** [yichengchen/clashX#225]
![image](https://user-images.githubusercontent.com/1579516/65426382-ba850b80-de42-11e9-8779-1b01bca3a9f2.png)
![image](https://user-images.githubusercontent.com/1579516/65426440-d5f01680-de42-11e9-8dd8-52e805362866.png)

**Comment by Chandler-Lu** [comment]
没有理解错的话，panel 里的 log 是只有 panel 开启时才会开始记录，用于临时调试，不受 level 的影响。level 控制的是后台记录，并且写入 logs 文件夹 `~/Library/Logs/ClashX` 的日志【帮助 -> 显示日志】

**Comment by dsky1990** [comment]
@Chandler-Lu 明白了，感谢
