### ISSUE TITLE
能耗异常地过高

### ISSUE THREAD

**Issue by CoderChang65535** [yichengchen/clashX#227]
在极低负载使用的情况下（一小时使用量低于10MB），能耗过高：对能耗的影响约在8左右（和20窗口chrome齐平），平均影响见图，和docker对比见图

![image](https://user-images.githubusercontent.com/19420270/65563374-f1ab0800-df7b-11e9-8fd6-0d35266f2136.png)

**Comment by yichengchen** [comment]
can not reproduced
