### ISSUE TITLE
使用代理后siri无法使用

### ISSUE THREAD

**Issue by CostinYuan** [yichengchen/clashX#228]
macbook开了clashx代理（规则判断）以后Siri无法使用，关掉又可以用了？？

**Comment by Chandler-Lu** [comment]
在确保 apple 相关域名处于直连的情况下，siri 依然可能在代理开启的状态下无法使用，与此同时发生的是天气和地图无法定位。。
这个问题好像所有的代理软件都有（部分软件 pac 模式除外），而且是个玄学问题，有时候能用，有时候又不能用。。
无解

**Comment by yichengchen** [comment]
应该是苹果的问题
