### ISSUE TITLE
求助

### ISSUE THREAD

**Issue by ra0mb1er** [yichengchen/clashX#230]
<img width="415" alt="屏幕快照 2019-09-26 下午7 38 42" src="https://user-images.githubusercontent.com/10510621/65685790-66be3080-e095-11e9-847d-95b233b1c2ea.png">
这是一个什么错误 = = 官方默认配置文件也提示这个，如何修复

**Comment by yichengchen** [comment]
配置规则错误 检查规则中的指向的代理在上面代理组中是否存在
