### ISSUE TITLE
can I turn off update pop-ups please

### ISSUE THREAD

**Issue by shunqiiiz** [yichengchen/clashX#240]
hi there, i play COC mobile strategy video game on my mac, very great game, enjoyed it! However when there's an update, it simply pops-up to the top and sometimes this could be embarrassing. I mainly use my macbook for work purposes and have it connected to projector a lot,,, so the sudden pop-up about gaming might be a little bit imapporiate for work situation... I do check updates manually very often so I can get new features, new skins & stuff, but I do wish there could be a "**turn-off update reminder popup" button, so that it won't just jump on the screen randomly while I'm doing a presentation in front of my boss ;)** Thanks in advance

**Comment by yichengchen** [comment]
For app which using sparkle to do auto upgrade action, you can disable auto update check by editing the info plist file (located in `ClashX.app/Contents/Info.plist`), Change `SUEnableAutomaticChecks` to `NO`.

**Comment by yichengchen** [comment]
And for ClashX, will remove this default `YES` option in the further version Then sparkle will ask you to enable auto update check.
