### ISSUE TITLE
trojan 配置问题

### ISSUE THREAD

**Issue by jfdnet** [yichengchen/clashX#241]
trojan 配置完无法出现在选择菜单里。
如果把 trojan 放在代理顺序第一位 则会默认选中 可以使用。

![t0](https://user-images.githubusercontent.com/1990429/77141033-76538a80-6ab6-11ea-8d6f-a5b649d0fdcf.jpg)
![t1](https://user-images.githubusercontent.com/1990429/77141039-7b183e80-6ab6-11ea-8baa-a99d007e3759.jpg)

**Comment by LanbenGG** [comment]
> trojan 配置完无法出现在选择菜单里。
> 如果把 trojan 放在代理顺序第一位 则会默认选中 可以使用。
> 
> ![t0](https://user-images.githubusercontent.com/1990429/77141033-76538a80-6ab6-11ea-8d6f-a5b649d0fdcf.jpg)
> ![t1](https://user-images.githubusercontent.com/1990429/77141039-7b183e80-6ab6-11ea-8baa-a99d007e3759.jpg)

应该是ClashX的bug，在控制台里可以正常看到并点选trojan的节点，在修复问题之前可以使用控制台来选择节点

**Comment by yichengchen** [comment]
修复提交了，请帮忙验证。
可以切到appcenter更新通道（help->experimental->update channel）检查更新升级，或者前往 https://install.appcenter.ms/users/clashx/apps/clashx/distribution_groups/Public 下载最新beta版本

**Comment by jfdnet** [comment]
试过没问题了。手动切换不同地区的代理，都能打开对应地区的Google。

![1](https://user-images.githubusercontent.com/1990429/77230043-6f1ea080-6bcc-11ea-8e96-6f453e56d01f.jpg)
