### ISSUE TITLE
貌似有偶发的性能问题

### ISSUE THREAD

**Issue by 81pla** [yichengchen/clashX#242]
系统版本10.15.3 (19D76)   浏览器用的chrome

在使用最近的版本（1.18.3， 1.18.4），
偶尔会发生，第一次访问部分网站， 正在建立安全连接上面会非常慢。 
chrome的network里显示如下，stalled时间很长。 只有第一次访问部分网站，或者长时间不访问再次访问时出现。
Connection Start |   | DURATION
-- | -- | --
Stalled | ​ | 5.08 s
Initial connection | ​ | 5.08 s
SSL | ​ | 5.08 s

我换了多台设备（不使用代理工具），访问对应网站都没有复现这个问题。
或者关闭clashx后 就没有再复现过。  

重新找了个旧版1.18.0使用   目前没有复现。

不知道有木有人遇到过这种情况。。。

**Comment by yichengchen** [comment]
代理部分由[clash core](https://github.com/Dreamacro/clash) 实现。 ClashX只实现了UI部分。
建议到Clash Core 提issue，同时附上core版本号， 可在clashx的关于->帮助 中版本号信息的第二行查看。
