### ISSUE TITLE
建议增加选择代理节点后策略组自动切换的功能

### ISSUE THREAD

**Issue by zhuxt2015** [yichengchen/clashX#244]
每次都是测速完，看到哪一个代理节点比较快，然后在去策略组中去选择对应的节点，但是节点如果很多，且名字不容易分辨，找起来很费劲。
建议增减一个功能，例如下图选择了英国的这个节点，策略组中proxy就自动切换到英国的节点。
![image](https://user-images.githubusercontent.com/13765310/77229355-6b891a80-6bc8-11ea-885e-6cd866ae2d31.png)

**Comment by yichengchen** [comment]
dashboard相关问题移步 https://github.com/Dreamacro/clash-dashboard

不过这个问题大概率不会修改，因为可以有多个包含proxy的select group
