### ISSUE TITLE
关于【忽略这些主机与域的代理设置】能否设置为自定义

### ISSUE THREAD

**Issue by SuperNG6** [yichengchen/clashX#245]
我现在拿clashX当做VPN用，连接到我家中的网络，clashX会在【忽略这些主机与域的代理设置】每次都会把`192.168.0.0/16`添加进去，能否把这块设置成自定义。需要忽略的手动设置，否则每次打开clashX都需要手动修改
![1YcBzX](https://cdn.jsdelivr.net/gh/SuperNG6/pic@master/uPic/1YcBzX.png)

**Comment by yichengchen** [comment]
请参考clashx readme并配置proxyIgnoreList.plist

**Comment by SuperNG6** [comment]
不好意思没有注意到，已解决，谢谢
在 2020年3月23日 +0800 PM7:22，Yicheng <notifications@github.com>，写道：
