### ISSUE TITLE
配置管理中出现下载失败

### ISSUE THREAD

**Issue by WinnieCrazyUniverse** [yichengchen/clashX#247]
在1.18.4版本，配置管理中输入域名和yaml文件的路径后，显示下载失败，只能手动通过浏览器下载后放入配置文件文件夹内使用，同样的链接反而clash for windows没问题，但是在clashX下出现这个文tilt，同样的地址浏览器也可以下载，不知道这是什么原因，因此前来反馈

**Comment by Jevanzhu** [comment]
提示信息是啥？截图看看，我之前有遇到过类似问题，后来发现是放订阅文件的Nginx设置有问题。如果是和我一样的，修改下Nginx的配置文件就行了。应该是文件编码问题，我现在改用caddy了，之前的Nginx删掉了，我记得我后面强制utf-8就解决了。

**Comment by WinnieCrazyUniverse** [comment]
![截屏2020-03-2413 03 35](https://user-images.githubusercontent.com/62456649/77390218-4666f880-6dd0-11ea-8d99-0a7940a81284.png)
是这样的，之前试图使用过utf-8的编码，但是里面的汉字好像是乱码，我不行试一下吧

**Comment by WinnieCrazyUniverse** [comment]
> 提示信息是啥？截图看看，我之前有遇到过类似问题，后来发现是放订阅文件的Nginx设置有问题。如果是和我一样的，修改下Nginx的配置文件就行了。应该是文件编码问题，我现在改用caddy了，之前的Nginx删掉了，我记得我后面强制utf-8就解决了。
> 
> 之前也是在Github搜到的类似问题的解决方案，但是刚翻了翻所有的issues没找到，当时搜到关键字也不记得了。你可以试试我的办法。

好了好了，改了文件编码就OK了，之前用的Unicode，utf-8就没问题了！非常感谢

**Comment by Jevanzhu** [comment]
> > 提示信息是啥？截图看看，我之前有遇到过类似问题，后来发现是放订阅文件的Nginx设置有问题。如果是和我一样的，修改下Nginx的配置文件就行了。应该是文件编码问题，我现在改用caddy了，之前的Nginx删掉了，我记得我后面强制utf-8就解决了。
> > 之前也是在Github搜到的类似问题的解决方案，但是刚翻了翻所有的issues没找到，当时搜到关键字也不记得了。你可以试试我的办法。
> 
> 好了好了，改了文件编码就OK了，之前用的Unicode，utf-8就没问题了！非常感谢

没事，搞定了就行。我也不知道怎么回事，订阅文件直接用vscode写的，本身也是utf-8。win下是可以订阅了，到了mac就会出错。后面把Nginx配置里加了一行 charset utf-8;  就都可以了，可能是mac版这边下载过程中文件编码的问题。
