### ISSUE TITLE
[Bug]ClashX 配置中v2ray协议若直接填写SSL证书路径, 则无法ping通服务器

### ISSUE THREAD

**Issue by GeorgeChen0821** [yichengchen/clashX#249]
### 重现问题的具体布骤 Steps to Reproduce

1. V2ray信息如上填写完全正确，SSL证书处填入路径
2. Clashx ping fail
<img width="229" alt="Screen Shot 2020-03-23 at 5 54 20 PM" src="https://user-images.githubusercontent.com/59362011/77305122-73fc6500-6d30-11ea-927d-31a3ae495fd5.png">
3. 改为直接填写证书及内容后，可以ping通
4. V2ray config:

  {
      "listen": "0.0.0.0",
      "port": 49392,
      "protocol": "vmess",
      "settings": {
        "clients": [
          {
            "alterId": 64,
            "id": "fe5825e9-fake-uuid-here-a847ecf07811"
          }
        ],
        "disableInsecureEncryption": true
      },
      "sniffing": {
        "destOverride": [
          "http",
          "tls"
        ],
        "enabled": true
      },
      "streamSettings": {
        "network": "ws",
        "security": "tls",
        "tlsSettings": {
          "allowInsecure": false,
          "certificates": [
            {
              "certificateFile": "/www/server/panel/ssl/certificate.pem",
              "keyFile": "/www/server/panel/ssl/privateKey.pem"
            }
          ],
          "serverName": "example.xyz"
        },

**Comment by yichengchen** [comment]
这应该是core的issue，不过目测应该是clash中的config配置配置有错 尝试skip-cert-verify: true

**Comment by GeorgeChen0821** [comment]
> 这应该是core的issue，不过目测应该是clash中的config配置配置有错 尝试skip-cert-verify: true

请问跳过证书验证的话 会增加被墙的概率吗？谢谢
