### ISSUE TITLE
在配置文件中添加 external-ui 选项不生效

### ISSUE THREAD

**Issue by Billin9** [yichengchen/clashX#255]
在配置文件中已经配置了

```yaml
external-ui: ui
```

并将已经编译好的页面放在配置文件目录下的 `ui` 目录, 但是在状态栏的界面中点击 `Command + D` 显示的还是默认的 `clash-dashboard`, 记得之前的版本中可以自定义的, 配置什么也没改, 升级版本后就不能这么用了

**Comment by yichengchen** [comment]
clashx上好像确实有这个问题， 具体原因还不清楚

**Comment by yichengchen** [comment]
确认了一下在clashx上应该是一直不能配置的，配置会被override掉。只有独立启动二进制可以进行配置。不过可以参考 https://github.com/Dreamacro/clash-dashboard 设置clashx dashboard的网址

**Comment by Billin9** [comment]
感谢指点, 使用下面的命令已经替换成功了, 写一下命令给需要的人看

```shell
defaults write com.west2online.ClashX kEnableDashboard -bool YES
defaults write com.west2online.ClashX webviewUrl "file:///Users/{your-user-name}/.config/clash/ui/index.html"
```
