### ISSUE TITLE
请问为什么终端不走全局代理？

### ISSUE THREAD

**Issue by nanxiaobei** [yichengchen/clashX#256]
设置 ClashX 全局代理，打开终端 zsh 中运行 `brew update`，没有走代理，
请问是有限制吗？

**Comment by Billin9** [comment]
![image](https://user-images.githubusercontent.com/15778311/77717034-67bb2500-701a-11ea-9352-6fc02529ac3b.png)

在软件界面点击 `Copy shell command` 或者直接使用快捷键 `Command + C`, 会自动复制代理的环境变量配置, 将配置输入到终端中回车即可生效.

使用命令 `curl -L http://t1.re` 可以查看是否已经成功启用代理

![image](https://user-images.githubusercontent.com/15778311/77717360-34c56100-701b-11ea-9bfa-6ab4b6c9cb88.png)

红色的部分可以看到代理服务器的 IP

想要取消代理配置请输入命令:

```shell
unset http_proxy;unset https_proxy;unset all_proxy
```

**Comment by h0wardch3ng** [comment]
https://medium.com/@truong21/what-happens-where-you-type-ls-l-in-a-linux-shell-a-command-line-journey-7f4dbf051336

**Comment by nanxiaobei** [comment]
嗯，我知道如何开启代理了，不过疑问主要是为什么设置了全局代理而对终端没用~

**Comment by Billin9** [comment]
全局模式是修改系统设置中的代理，使所有 http/socks 数据经过代理服务器的转发送出，而只有支持 socks5 或者使用系统代理的软件才可以在不需要额外配置的情况下使用代理，一般的浏览器都会默认使用系统代理，而终端不会使用系统代理，有一些第三方 APP 也不使用系统代理所以才需要单独配置。

以上是我知道的原因，不一定是正确的。

**Comment by nanxiaobei** [comment]
好的，感谢回答~
