### ISSUE TITLE
升级 Catalina 10.15.4 后软件异常无法使用

### ISSUE THREAD

**Issue by isecret** [yichengchen/clashX#257]
今天中午升级了 Catalina 10.15.4 (19E266) 后，重新启动后 ClashX 没有开启自起，手动启动后提示错误：

```text
Config loading fail!
config.yaml: ProxyGroup[1]: `use` or `proxies` missing
```
软件 Proxy Model 栏为不可用状态（灰色），点击 reload config 后提示错误：
```text
Config loading fail!
config.yaml: stat /Users/username/.config/clash/Users/username/.config/clash/config.yaml: no such file or directory
```
如果我尝试创建 `/Users/username/.config/clash/Users/username/.config/clash/config.yaml` 重新加载后，错误提示的目录又会增加一层：
```text
Config loading fail!
config.yaml: stat /Users/username/.config/clash/Users/username/.config/clash/Users/username/.config/clash/config.yaml: no such file or directory
```
我已经通过 brew 重新安装过了，依然无法解决。

**Comment by yichengchen** [comment]
我这里没问题诶 尝试把整个.config目录中的clash文件夹删除看看？

**Comment by ChiaJune** [comment]
我这里升级到1.18.3版本以后提示配置文件拉取失败

**Comment by isecret** [comment]
我删除了 `.config/clash` 目录，使用新的配置文件发现能够成功，我比对我之前的配置发现是 `ProxyGroup` 中 `proxies` 丢失了。
