### ISSUE TITLE
使用clashX 机场监控会提示出现多个ip

### ISSUE THREAD

**Issue by Faithree** [yichengchen/clashX#260]
使用clashX 机场监控会提示出现多个ip设备登陆，但是使用v2rayU之类的客户端，机场监控只有一个ip设备，请问为什么会这样。

**Comment by Faithree** [comment]
我看了下原来的issue,有个类似的，https://github.com/yichengchen/clashX/issues/214 我怀疑也是这个问题，我想问一下现在能不能关闭掉延迟测速

**Comment by yichengchen** [comment]
延迟测速没有auto组你不点他就不会测速

建议向机场check ip的算法或者检查订阅是否泄漏

**Comment by Faithree** [comment]
> 延迟测速没有auto组你不点他就不会测速
> 
> 建议向机场check ip的算法或者检查订阅是否泄漏

机场是有 auto 组，我发现我的宽带是有多个 ip 造成的，类似动态 ip ? 跟机场反应了，这个机场那边解决不了，他们推荐用 v2rayU，但是我觉得 clashX 比较好用，还是倾向于问问能不能在 clashX 加上关闭延迟测速的功能，或者有其他解决办法。

**Comment by yichengchen** [comment]
clashx无法修改你的配置文件，可以尝试使用类似subconverter之类的工具自动转换配置文件去除auto组
