### ISSUE TITLE
打开clashx之后，mac系统配置的hosts就会失效 

### ISSUE THREAD

**Issue by zzuhan** [yichengchen/clashX#262]
由于是开发者，平时电脑里会有很多hosts的配置，并且会经常切换。

但是现在开启clashx后，这些配置会失效。

另外配置使用的是一个托管自动更新的配置。

想请问下，有什么样的快速先hack的处理方式，以及长远会处理这个问题吗？

**Comment by yichengchen** [comment]
关闭配置中的dns功能 或者在配置dns section中设置dns。具体可看clash core的配置文件readme
