### ISSUE TITLE
亲，可否下次更新的时候能兼容以前的配置了？

### ISSUE THREAD

**Issue by easonjim** [yichengchen/clashX#265]
因为每次更新大版本之前，配置文件都是跟着改，如果不改，就会造成API的错误

**Comment by yichengchen** [comment]
据我所知最近所有大版本更新配置文件都是向前兼容的。。。有问题可以到clash core去反馈

**Comment by easonjim** [comment]
亲，不要据我所知了，core测试过了没问题，clashx加载的时候有问题；

**Comment by yichengchen** [comment]
> 亲，不要据我所知了，core测试过了没问题，clashx加载的时候有问题；

clashx没有任何读config的操作。有问题请贴出错误内容

**Comment by easonjim** [comment]
亲，能不能测试一下啊，都搞这么久软件了。
