### ISSUE TITLE
可否增加类似于GEOSITE规则判断呢？

### ISSUE THREAD

**Issue by ixiaofeng** [yichengchen/clashX#266]
通过抓包发现，请求一个“非法”网站的时候，虽然通过本地规则对比后，远程解析返回了结果，但是本地DNS还是先直接请求了一遍，这样的话，本地的这次请求行为就会被运营商或者局域网的上网行为管理给监控到。如果可以增加GEOSITE这种判断的话，就不用在规则中发现ip规则时，先对域名解析成ip判断了，也就能尽可能少的留下痕迹了。（不要喷我类似于想要隐身用tor之类的，只是提一个想法）

**Comment by yichengchen** [comment]
只有触发非no-reslove的ip规则时会出发dns解析 请检查规则配置。
