### ISSUE TITLE
设置系统代理忽略 0.0.0.0

### ISSUE THREAD

**Issue by saup007** [yichengchen/clashX#267]
现在忽略代理是 192.168.0.0/16、10.0.0.0/8、172.16.0.0/12、127.0.0.1、localhost、*.local

需求修改代理为，否则每次开关都要手工再设置一下
```
192.168.0.0/16、10.0.0.0/8、172.16.0.0/12、127.0.0.1、localhost、*.local、0.0.0.0
```

<img width="652" alt="image" src="https://user-images.githubusercontent.com/1343717/78096386-fd382980-740b-11ea-99cf-48a91ba36609.png">

**Comment by yichengchen** [comment]
请查看master分支readme advance config 并配置proxyignore.plist

**Comment by saup007** [comment]
done, thanks.
