### ISSUE TITLE
更新至1.19.0后出现错误导致不能使用：blessError: kSMErrorInternalFailure

### ISSUE THREAD

**Issue by TK851441665** [yichengchen/clashX#269]
blessError: kSMErrorInternalFailure

**Comment by alexlee728** [comment]
同样问题！

**Comment by alexlee728** [comment]
<img width="420" alt="1" src="https://user-images.githubusercontent.com/3183748/78330580-dd913480-75b6-11ea-819c-8bf9c4d58609.png">
<img width="420" alt="2" src="https://user-images.githubusercontent.com/3183748/78330579-dc600780-75b6-11ea-96f8-c142129644ea.png">
一直重复该流程

**Comment by yichengchen** [comment]
这个看起来是个系统 bug。 系统版本是多少呢？重启有用吗？
尝试删除
`/Library/PrivilegedHelperTools/com.west2online.ClashX.ProxyConfigHelper`
试试？

**Comment by yichengchen** [comment]
find a apple radar https://openradar.appspot.com/20446733

**Comment by yichengchen** [comment]
同时 假设你的ClashX 放在 `/Applications/ClashX.app` 目录下 （不是的话对应修改文件中的path）

尝试保存以下内容为 fix.sh
``` bash
#!/bin/bash
set -xe

plistPath=/Library/LaunchDaemons/com.west2online.ClashX.ProxyConfigHelper.plist

if [ -e ${plistPath} ]; then
    launchctl unload -w ${plistPath}
    rm ${plistPath}
fi

rm -f /Library/PrivilegedHelperTools/com.west2online.ClashX.ProxyConfigHelper
cp /Applications/ClashX.app/Contents/Library/LaunchServices/com.west2online.ClashX.ProxyConfigHelper /Library/PrivilegedHelperTools/com.west2online.ClashX.ProxyConfigHelper

echo '
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>Label</key>
	<string>com.west2online.ClashX.ProxyConfigHelper</string>
	<key>MachServices</key>
	<dict>
		<key>com.west2online.ClashX.ProxyConfigHelper</key>
		<true/>
	</dict>
	<key>Program</key>
	<string>/Library/PrivilegedHelperTools/com.west2online.ClashX.ProxyConfigHelper</string>
	<key>ProgramArguments</key>
	<array>
		<string>/Library/PrivilegedHelperTools/com.west2online.ClashX.ProxyConfigHelper</string>
	</array>
</dict>
</plist>
' > /Library/LaunchDaemons/com.west2online.ClashX.ProxyConfigHelper.plist

launchctl load -w ${plistPath}
```
然后 
```
chmod +x fix.sh
sudo ./fix.sh
```
看是否修复

**Comment by alexlee728** [comment]
> 同时 假设你的ClashX 放在 `/Applications/ClashX.app` 目录下 （不是的话对应修改文件中的path）
> 
> 尝试保存以下内容为 fix.sh
> 
> ```shell
> #!/bin/bash
> set -xe
> 
> plistPath=/Library/LaunchDaemons/com.west2online.ClashX.ProxyConfigHelper.plist
> 
> if [ -e ${plistPath} ]; then
>     launchctl unload -w ${plistPath}
>     rm ${plistPath}
> fi
> 
> rm -f /Library/PrivilegedHelperTools/com.west2online.ClashX.ProxyConfigHelper
> cp /Applications/ClashX.app/Contents/Library/LaunchServices/com.west2online.ClashX.ProxyConfigHelper /Library/PrivilegedHelperTools/com.west2online.ClashX.ProxyConfigHelper
> 
> echo '
> <?xml version="1.0" encoding="UTF-8"?>
> <!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
> <plist version="1.0">
> <dict>
> 	<key>Label</key>
> 	<string>com.west2online.ClashX.ProxyConfigHelper</string>
> 	<key>MachServices</key>
> 	<dict>
> 		<key>com.west2online.ClashX.ProxyConfigHelper</key>
> 		<true/>
> 	</dict>
> 	<key>Program</key>
> 	<string>/Library/PrivilegedHelperTools/com.west2online.ClashX.ProxyConfigHelper</string>
> 	<key>ProgramArguments</key>
> 	<array>
> 		<string>/Library/PrivilegedHelperTools/com.west2online.ClashX.ProxyConfigHelper</string>
> 	</array>
> </dict>
> </plist>
> ' > /Library/LaunchDaemons/com.west2online.ClashX.ProxyConfigHelper.plist
> 
> launchctl load -w ${plistPath}
> ```
> 
> 然后
> 
> ```
> chmod +x fix.sh
> sudo ./fix.sh
> ```
> 
> 看是否修复

可以了

**Comment by paradiseduo** [comment]
看上去像签名的问题，我直接跑源码也报这个错误。
系统是最新的10.15.4

**Comment by yichengchen** [comment]
fixed
