### ISSUE TITLE
更新1.19后出现安装帮助程序失败情况

### ISSUE THREAD

**Issue by alexlee728** [yichengchen/clashX#271]
<img width="420" alt="1" src="https://user-images.githubusercontent.com/3183748/78330580-dd913480-75b6-11ea-819c-8bf9c4d58609.png">
<img width="420" alt="2" src="https://user-images.githubusercontent.com/3183748/78330579-dc600780-75b6-11ea-96f8-c142129644ea.png">
一直重复该流程，即使密码输入正确。

**Comment by yichengchen** [comment]
请问系统版本是多少呢? 重启/尝试 删除 `/Library/PrivilegedHelperTools/com.west2online.ClashX.ProxyConfigHelper` 有效果吗？

**Comment by yichengchen** [comment]
这个错误有些奇怪，请确认一下clashx是从github本repo下载的吗

**Comment by yichengchen** [comment]
同时 假设你的ClashX 放在 `/Applications/ClashX.app` 目录下 （不是的话对应修改文件中的path）

尝试保存以下内容为 fix.sh
``` bash
#!/bin/bash
set -xe

plistPath=/Library/LaunchDaemons/com.west2online.ClashX.ProxyConfigHelper.plist

if [ -e ${plistPath} ]; then
    launchctl unload -w ${plistPath}
    rm ${plistPath}
fi

rm -f /Library/PrivilegedHelperTools/com.west2online.ClashX.ProxyConfigHelper
cp /Applications/ClashX.app/Contents/Library/LaunchServices/com.west2online.ClashX.ProxyConfigHelper /Library/PrivilegedHelperTools/com.west2online.ClashX.ProxyConfigHelper

echo '
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>Label</key>
	<string>com.west2online.ClashX.ProxyConfigHelper</string>
	<key>MachServices</key>
	<dict>
		<key>com.west2online.ClashX.ProxyConfigHelper</key>
		<true/>
	</dict>
	<key>Program</key>
	<string>/Library/PrivilegedHelperTools/com.west2online.ClashX.ProxyConfigHelper</string>
	<key>ProgramArguments</key>
	<array>
		<string>/Library/PrivilegedHelperTools/com.west2online.ClashX.ProxyConfigHelper</string>
	</array>
</dict>
</plist>
' > /Library/LaunchDaemons/com.west2online.ClashX.ProxyConfigHelper.plist

launchctl load -w ${plistPath}
```
然后 
```
chmod +x fix.sh
sudo ./fix.sh
```
看是否修复

**Comment by alexlee728** [comment]
> 请问系统版本是多少呢? 重启/尝试 删除 `/Library/PrivilegedHelperTools/com.west2online.ClashX.ProxyConfigHelper` 有效果吗？

系统版本是：10.15.4 (19E266)

**Comment by alexlee728** [comment]
> 同时 假设你的ClashX 放在 `/Applications/ClashX.app` 目录下 （不是的话对应修改文件中的path）
> 
> 尝试保存以下内容为 fix.sh
> 
> ```shell
> #!/bin/bash
> set -xe
> 
> plistPath=/Library/LaunchDaemons/com.west2online.ClashX.ProxyConfigHelper.plist
> 
> if [ -e ${plistPath} ]; then
>     launchctl unload -w ${plistPath}
>     rm ${plistPath}
> fi
> 
> rm -f /Library/PrivilegedHelperTools/com.west2online.ClashX.ProxyConfigHelper
> cp /Applications/ClashX.app/Contents/Library/LaunchServices/com.west2online.ClashX.ProxyConfigHelper /Library/PrivilegedHelperTools/com.west2online.ClashX.ProxyConfigHelper
> 
> echo '
> <?xml version="1.0" encoding="UTF-8"?>
> <!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
> <plist version="1.0">
> <dict>
> 	<key>Label</key>
> 	<string>com.west2online.ClashX.ProxyConfigHelper</string>
> 	<key>MachServices</key>
> 	<dict>
> 		<key>com.west2online.ClashX.ProxyConfigHelper</key>
> 		<true/>
> 	</dict>
> 	<key>Program</key>
> 	<string>/Library/PrivilegedHelperTools/com.west2online.ClashX.ProxyConfigHelper</string>
> 	<key>ProgramArguments</key>
> 	<array>
> 		<string>/Library/PrivilegedHelperTools/com.west2online.ClashX.ProxyConfigHelper</string>
> 	</array>
> </dict>
> </plist>
> ' > /Library/LaunchDaemons/com.west2online.ClashX.ProxyConfigHelper.plist
> 
> launchctl load -w ${plistPath}
> ```
> 
> 然后
> 
> ```
> chmod +x fix.sh
> sudo ./fix.sh
> ```
> 
> 看是否修复

正常了
