### ISSUE TITLE
请问什么时候支持SSR，太重要了

### ISSUE THREAD

**Issue by duqn** [yichengchen/clashX#272]
非常感谢作者的贡献！
尽管v2ray已经非常热，但SSR确实从性能上来看，还是有相当大的优势的，大多数的机场还是SSR节点优于v2ray，非常希望作者能把SSR加入开发计划，目前使用ShadowsocksX-NG结合ClashX分流非常痛苦，Clash将成为真正的第一客户端

**Comment by yichengchen** [comment]
帮助完成clash core https://github.com/Dreamacro/clash/pull/519 这个pr即可
