### ISSUE TITLE
托管配置文件的问题

### ISSUE THREAD

**Issue by 821869798** [yichengchen/clashX#274]
当输入托管的url很长的时候，会弹出框“输入不合法”，windows版的clash就没问题

**Comment by yichengchen** [comment]
可以贴一下范例url吗

**Comment by 821869798** [comment]
> 可以贴一下范例url吗

https://x=tx.123456789.xyz:2550/sub?target=clash&url=vmess%3a%2f%2few0KICAidiI6ICIyIiwNCiAgInBzIjogInd1bGFiaW5nX2JmYmZub2RlLm1sIiwNCiAgImFkZCI6ICJiZmJmbm9kZS5tbCIsDQogICJwb3J0IjogIjQ0MyIsDQogICJpZCI6ICIzMzUwNDgxMS1iOGZmLTQxNDYtODBmZi0yNDNmZWY3NDMwZWIiLA0KICAiYWlkIjogIjMyIiwNCiAgIm5ldCI6ICJ3cyIsDQogICJ0eXBlIjogIm5vbmUiLA0KICAiaG9zdCI6ICJiZmJmbm9kZS5tbCIsDQogICJwYXRoIjogIi9hYjFkNzQ5My8iLA0KICAidGxzIjogInRscyINCn0K|vmess%3a%2f%2few0KICAidiI6ICIyIiwNCiAgInBzIjogInd1bGFiaW5nX2JmYmZub2RlLm1sIiwNCiAgImFkZCI6ICJiZmJmbm9kZS5tbCIsDQogICJwb3J0IjogIjQ0MyIsDQogICJpZCI6ICIzMzUwNDgxMS1iOGZmLTQxNDYtODBmZi0yNDNmZWY3NDMwZWIiLA0KICAiYWlkIjogIjMyIiwNCiAgIm5ldCI6ICJ3cyIsDQogICJ0eXBlIjogIm5vbmUiLA0KICAiaG9zdCI6ICJiZmJmbm9kZS5tbCIsDQogICJwYXRoIjogIi9hYjFkNzQ5My8iLA0KICAidGxzIjogInRscyINCn0K|vmess%3a%2f%2few0KICAidiI6ICIyIiwNCiAgInBzIjogInd1bGFiaW5nX2JmYmZub2RlLm1sIiwNCiAgImFkZCI6ICJiZmJmbm9kZS5tbCIsDQogICJwb3J0IjogIjQ0MyIsDQogICJpZCI6ICIzMzUwNDgxMS1iOGZmLTQxNDYtODBmZi0yNDNmZWY3NDMwZWIiLA0KICAiYWlkIjogIjMyIiwNCiAgIm5ldCI6ICJ3cyIsDQogICJ0eXBlIjogIm5vbmUiLA0KICAiaG9zdCI6ICJiZmJmbm9kZS5tbCIsDQogICJwYXRoIjogIi9hYjFkNzQ5My8iLA0KICAidGxzIjogInRscyINCn0K|vmess%3a%2f%2few0KICAidiI6ICIyIiwNCiAgInBzIjogInd1bGFiaW5nX2JmYmZub2RlLm1sIiwNCiAgImFkZCI6ICJiZmJmbm9kZS5tbCIsDQogICJwb3J0IjogIjQ0MyIsDQogICJpZCI6ICIzMzUwNDgxMS1iOGZmLTQxNDYtODBmZi0yNDNmZWY3NDMwZWIiLA0KICAiYWlkIjogIjMyIiwNCiAgIm5ldCI6ICJ3cyIsDQogICJ0eXBlIjogIm5vbmUiLA0KICAiaG9zdCI6ICJiZmJmbm9kZS5tbCIsDQogICJwYXRoIjogIi9hYjFkNzQ5My8iLA0KICAidGxzIjogInRscyINCn0K&config=https%3A%2F%2Fraw.githubusercontent.com%2FACL4SSR%2FACL4SSR%2Fmaster%2FClash%2Fconfig%2FACL4SSR_Online.ini

差不多是这个样子的。

**Comment by 821869798** [comment]
好像我的macbook 10.14.6也这样弄的就没问题，今天在一台mac mini 10.15.3上试就 “输入不合法”

**Comment by yichengchen** [comment]
实验了一下 macOS系统方法判断这个url不合法 主要是因为 url 中含有 ```|``` 你可能需要对他进行转义。 比如上面的那个链接 右键复制连接就会发现|被转义了。

**Comment by 821869798** [comment]
哦哦，我知道了，我这次是在markdown上复制的，markdown自动把`|` 还原了。
