### ISSUE TITLE
ip被忽略

### ISSUE THREAD

**Issue by kyoma95** [yichengchen/clashX#275]
想在浏览器打开这个10.61.2.118地址上的一个服务(一台实验室的内网服务器，用v2ray做了内网穿透)，但从日志看来，这个ip被忽略掉了，推测可能是被当成了内网ip，总之没通过clash建立连接。

我看到其他的讨论，从master分支下载并配置了proxyignore.plist，直接用的你那个sample，但还是不行。从系统设置里看，那个ip也没有被绕过：
![image](https://user-images.githubusercontent.com/36957212/78557609-ab483700-7843-11ea-85e5-15941d3457a8.png)

我推测ip被忽略掉，是从Proxifier这个软件上观察的，这个请求应该是从chrome直连了，把它截下来，重新发给clash，连接就可以成功建立。
![image](https://user-images.githubusercontent.com/36957212/78558158-b780c400-7844-11ea-9eb2-8c709cede442.png)

所以我应该如何配置才能让clash不忽略这个ip呢？

**Comment by yichengchen** [comment]
检查文件名 目录 内容是否正确 贴出配置的plist内容。配置成功时系统设置会更新。

**Comment by kyoma95** [comment]
都检查过了：
![image](https://user-images.githubusercontent.com/36957212/78559054-4b06c480-7846-11ea-99c4-27fbafcb3ce3.png)
plist内容和系统设置那边是一致的，也重启过软件了，但这个ip还是莫名其妙会被忽略。

**Comment by kyoma95** [comment]
和系统设置里是一致的：
![image](https://user-images.githubusercontent.com/36957212/78563517-b011e880-784d-11ea-9d3c-b48f9ce3a0e6.png)

**Comment by kyoma95** [comment]
看起来不是这处配置的原因吧？
不知道其他还有哪里的配置会导致ip被忽略？

**Comment by yichengchen** [comment]
...所以你要改plist吧10.0.0.0/8去掉啊
