### ISSUE TITLE
大佬，ClashX Pro 开增强模式出现闪退，macOS版本10.13.6

### ISSUE THREAD

**Issue by kai2ou** [yichengchen/clashX#276]

**Comment by yichengchen** [comment]
暂时还没有在10.13上测试过。 有崩溃日志吗  在 `~/Library/Logs/DiagnosticReports` 同时崩溃前最后的log输出是什么呢。

**Comment by kai2ou** [comment]
DiagnosticReports里没有生成崩溃日志；最后的log是：`2020/04/08 08:24:23:268  [debug] Auto selecting GLOBAL DIRECT
2020/04/08 08:24:23:268  [info] Setup TUN begin
2020/04/08 08:24:23:269  [debug] trafficWebSocket did Connect
2020/04/08 08:24:23:271  [info] Setup TUN createDeviceObservable
2020/04/08 08:24:23:271  [debug] loggingWebSocket did Connect
2020/04/08 08:24:23:272  [info] Setup TUN prepareTunAndRouteObservable
2020/04/08 08:24:23:313  [info] Setup TUN prepare deviec finsih
2020/04/08 08:24:23:313  [info] Setup TUN createClashTunObservable`

**Comment by yichengchen** [comment]
10.15也有人遇到了一样的情况…

**Comment by yichengchen** [comment]
@kai2ou 可以麻烦提供一下控制台输出看看有没有崩溃信息吗 操作步骤如下：
- 退出clashxpro
- 通过终端打开clashxpro包中的`Contents/MacOS/ClashX\ Pro` 例如 `/Applications/ClashX\ Pro.app/Contents/MacOS/ClashX\ Pro` 如图所示
<img width="1050" alt="Snipaste_2020-04-09_23-21-54" src="https://user-images.githubusercontent.com/11733500/78911492-f28b2d80-7ab8-11ea-8a51-4427a69dd85a.png">

 - 开启增强模式，在崩溃时查看终端中的信息

**Comment by kai2ou** [comment]
@yichengchen 
![屏幕快照 2020-04-10 上午9 28 11](https://user-images.githubusercontent.com/39549646/78954174-d8c80580-7b0d-11ea-8ae2-1e524c0f0fc8.png)

**Comment by yichengchen** [comment]
好的感谢

**Comment by yichengchen** [comment]
请问能把内容复制出来吗

**Comment by kai2ou** [comment]
@yichengchen 
`/Applications/ClashX\ Pro.app/Contents/MacOS/ClashX\ Pro 
panic: runtime error: index out of range [1] with length 0

goroutine 17 [running, locked to thread]:
main.createClashTun(0x7fff46fee178, 0x7fff46fee178, 0x10cbd3001, 0x0)
	/Users/ci/actions-runner/_work/ClashXPro/ClashXPro/ClashX/goClash/main.go:82 +0x3e6
main._cgoexpwrap_2ef65be39a7c_createClashTun(0x7fff46fee178, 0x7fff46fee178, 0x700001f29001, 0x0)
	_cgo_gotypes.go:86 +0x73`

**Comment by yichengchen** [comment]
请问你有在配置文件自定义dns相关的配置吗？ 如果有 去掉以后能正常启动吗

**Comment by kai2ou** [comment]
没有自定义dns，试了下默认的config也是一开增强模式就闪退。这是我的配置文件（删除了节点信息）
[clashx.yaml.zip](https://github.com/yichengchen/clashX/files/4460032/clashx.yaml.zip)

**Comment by 81pla** [comment]
Pro是什么版本，哪里有下啊

**Comment by yichengchen** [comment]
@kai2ou 我更新了一下1.19.3 加了一些log和保护 可以帮忙再看一下吗https://install.appcenter.ms/users/clashx/apps/clashx-pro/distribution_groups/public

**Comment by kai2ou** [comment]
@yichengchen 
`2020/04/10 21:04:25:815  [info] Setup TUN begin
2020/04/10 21:04:25:816  [info] Setup TUN createDeviceObservable
2020/04/10 21:04:25:816  [info] Setup TUN: get tuninfo TunInfo(tunName: "utun1", ip: "", netmask: "")
2020/04/10 21:04:25:816  [info] Setup TUN prepareTunAndRouteObservable
2020/04/10 21:04:25:816  [debug] loggingWebSocket did Connect
2020/04/10 21:04:25:819  [debug] trafficWebSocket did Connect
2020/04/10 21:04:25:840  [info] Setup TUN prepare deviec finsih
2020/04/10 21:04:25:840  [info] Setup TUN createClashTunObservable
2020/04/10 21:04:25:840  [info] SetupTun: createClashTunObservable done:
2020/04/10 21:04:25:844  [error] Setup TUN Fail:未能完成该操作。（ClashX_Pro.TunManager.TunError 错误 1。）
2020/04/10 21:04:25:844  [info] Stop Tun: Begin
2020/04/10 21:04:25:844  [info] Stop Tun: Clear system dns
2020/04/10 21:04:25:845  [info] Stop Tun: Close Clash dns
2020/04/10 21:04:25:845  [info] Stop Tun: Close fd
2020/04/10 21:04:25:860  [info] Stop Tun: Reload Clash dns config
2020/04/10 21:04:25:860  [info] Stop Tun: Done
2020/04/10 21:04:25:867  [debug] Auto selecting GLOBAL DIRECT
2020/04/10 21:04:25:867  [debug] Auto selecting 🌍 国外代理 SG ·5#35|1|2
2020/04/10 21:04:25:867  [debug] Auto selecting 🐟 漏网之鱼 SG ·5#35|1|2
2020/04/10 21:04:25:871  [debug] loggingWebSocket did Connect
2020/04/10 21:04:25:871  [debug] trafficWebSocket did Connect`

**Comment by kai2ou** [comment]
@yichengchen 
![屏幕快照 2020-04-10 下午9 07 58](https://user-images.githubusercontent.com/39549646/78993069-756ebf80-7b6f-11ea-99d8-4e02d7a6cc65.png)

**Comment by kai2ou** [comment]
@yichengchen 
系统网络设置这里有一个默认的局域网DNS服务器，不知道是不是应为这个？
![屏幕快照 2020-04-10 下午9 11 01](https://user-images.githubusercontent.com/39549646/78993305-05ad0480-7b70-11ea-84d5-102fb052a6d9.png)

**Comment by yichengchen** [comment]
很奇怪 tun和ip获取失败了
get tuninfo TunInfo(tunName: "utun1", ip: "", netmask: "")

**Comment by yichengchen** [comment]
我可能知道为什么了。请检查一下试验性功能中的使用内置api是否勾选。要勾选才能正常工作 @kai2ou

**Comment by kai2ou** [comment]
@yichengchen 
Nice，勾选内置api后可以了，👍

**Comment by wangxin6** [comment]
> Pro是什么版本，哪里有下啊

同问

**Comment by yichengchen** [comment]
> > Pro是什么版本，哪里有下啊
> 
> 同问

你们不看上面发的appcenter地址的吗。。。
