### ISSUE TITLE
两个问题

### ISSUE THREAD

**Issue by phpmaple** [yichengchen/clashX#277]
1. 设置了自定义 http port 和 socks port，重新启动软件又被设置为默认端口

 2. 是否可以设置启动代理后不覆盖系统代理，现在关闭系统代理后本身监听端口也关闭了

**Comment by yichengchen** [comment]
1. 请参照readme 修改 config.yaml 这个文件中的端口号 不要使用dashboard修改
2. ？你不开代理不就好了 监听端口不会关闭的

**Comment by phpmaple** [comment]
> 1. config.yaml

但是直接在 config.yaml 修改的话，我用的是订阅的配置，下次更新配置被覆盖这个怎么解决比较好呢

**Comment by yichengchen** [comment]
config.yaml 是独立clashx自己创建的文件 不是改订阅的配置里的端口 @phpmaple

**Comment by phpmaple** [comment]
Thanks
