### ISSUE TITLE
vmess的tcp+tls模式连接不上

### ISSUE THREAD

**Issue by phlinhng** [yichengchen/clashX#278]
使用`{ name: "v2ray", type: vmess, server: example.com, port: 443, uuid: UUID, alterId: 0, cipher: none, skip-cert-verify: true, tls: true }` 无法连上vmess的tcp+tls模式，同样设置在其他客户端是可以的。

**Comment by yichengchen** [comment]
好像core上有修复 在1.19.1中会跟进
