### ISSUE TITLE
无法使用 Proxifier

### ISSUE THREAD

**Issue by FaiChou** [yichengchen/clashX#279]
[Proxifier 不能用了吗？](https://www.v2ex.com/t/660590)

好久之前使用过 Proxifier，那时候是没问题的，但最近想给某进程设置代理，于是打开了 Proxifier，但是怎么配置都不成功。以为 Proxifier 有问题，于是安装了 [proximac](https://github.com/csujedihy/proximac), 但测试发现，它也不能用。

于是好奇，是不是 clashX 的原因导致冲突？

**Comment by yichengchen** [comment]
没有吧 应该是你系统出了什么问题。。
