### ISSUE TITLE
可否增加自定义的转发规则？

### ISSUE THREAD

**Issue by LeiQiao** [yichengchen/clashX#281]
官方的规则可以从远程下载，但是有没有可以增加自定义转发规则的地方？每次下载之后自己添加的规则就被覆盖没了很不方便

**Comment by yichengchen** [comment]
建议使用clash core的proxy-provider功能自己编写配置文件 或者使用其他配置文件转换api工具。clashx没有计划单独添加配置文件编辑相关功能
