### ISSUE TITLE
打开clashX控制台，代理设置什么都没有

### ISSUE THREAD

**Issue by wibin86** [yichengchen/clashX#283]
![image](https://user-images.githubusercontent.com/17491154/79060108-cab3e980-7cb3-11ea-9475-fe83b2e15248.png)

如图，打开clashX代理设置，什么都没有，找不到添加代理都入口，macOS是最新都10.15.4

**Comment by yichengchen** [comment]
clashx不支持通过界面设置代理，仅支持配置文件手动配置
