### ISSUE TITLE
安装失败，手动创建文件夹也不好使

### ISSUE THREAD

**Issue by cuiziboczb** [yichengchen/clashX#284]
ClashX 创建 ~/.config/clash 文件夹失败，请检查权限设置或者手动创建文件夹后重启 ClashX。
只有推出一个提示

**Comment by zhang19980107** [comment]
我也出现了个问题

**Comment by forzerobyone** [comment]
我也是 心态崩了

**Comment by yichengchen** [comment]
看到这个错误 我心态也崩了

**Comment by yichengchen** [comment]
下载 clash core https://github.com/Dreamacro/clash/releases/download/v0.19.0/clash-darwin-amd64-v0.19.0.gz 并且手动运行的话会提示什么？

**Comment by yichengchen** [comment]
Close due to no more feedback. If problem still happen with the latest version, please create a new issue and provide the log at the same time
