### ISSUE TITLE
退出时系统代理支持下自动去掉？

### ISSUE THREAD

**Issue by uxsi** [yichengchen/clashX#285]
### 系统
mac 10.15.4

### 版本
1.19.1

### 问题
退出时代理开关自动关闭了，但没有完全清空系统代理设置内容，能否顺带自动清空一下？

### 截图
![image](https://user-images.githubusercontent.com/4378939/79070648-d3cfa580-7d09-11ea-8b3a-8bdd40b5e9d9.png)

**Comment by yichengchen** [comment]
应该可以做…但是有什么特殊的需求场景吗

**Comment by uxsi** [comment]
> 应该可以做…但是有什么特殊的需求场景吗

切换到其它代理工具的时候，会有规则冲突，得回来设置里手动删掉，有点麻烦

**Comment by uxsi** [comment]
另外请教一下，退出的时候清空web代理的代码在哪里呢，我发现`networksetup -setwebprox <networkservice> empty`只能清空domain字段，端口会保持为0，clashx退出的时候可以直接清空，想看看是怎么处理的

**Comment by yichengchen** [comment]
其他代理工具应该实现这个填写才是正确的。。。

https://github.com/yichengchen/clashX/blob/bdbb345010cdf7f4eb2a879b5639dcd0c55302db/ProxyConfigHelper/ProxySettingTool.m#L172

**Comment by uxsi** [comment]
@yichengchen 优秀，已用上
