### ISSUE TITLE
配置文件自动更新

### ISSUE THREAD

**Issue by gaopeng-hz** [yichengchen/clashX#287]
我编辑完配置文件后一段时间内自定义的规则是有效的，但是过一晚上后配置文件就被覆盖了，原来自定义的一些规则丢了（查看文件修改时间可以知道文件被自动修改了）

**Comment by liujason212** [comment]
是否可以把规则和服务器订阅配置信息给分开管理啊？否则自己设定的规则一下就被重置了

**Comment by gaopeng-hz** [comment]
![image](https://user-images.githubusercontent.com/6285506/79212865-d4d41480-7e7a-11ea-9dbc-7eb29bd22280.png)
规则和服务器订阅配置信息不是在同一个yaml文件中的吗？

不是太明白怎么把规则和服务器订阅配置信息分开管理，新手，不太懂，还请指教！

**Comment by yichengchen** [comment]
分开管理 需要使用provider。 要取消自动更新 可以关闭托管配置->自动更新

provider的说明 https://lancellc.gitbook.io/clash/clash-config-file/proxy-provider
