### ISSUE TITLE
mac ClashX 关闭代理后上不了网

### ISSUE THREAD

**Issue by luistrong** [yichengchen/clashX#288]
已经打开自动还原代理了，但是只要一关闭 clashx 浏览器就无法上网，必须开启后才能上网，请问问题出在哪？谢谢

**Comment by yichengchen** [comment]
可能是 https://github.com/yichengchen/clashX/issues/243 造成的。。可能有什么vpn软件创建了隐藏的网络连接

**Comment by yichengchen** [comment]
在试验性功能中关闭自动还原代理 然后取消系统代理不行吗

**Comment by jimmymitlavigne** [comment]
你好。请问你的问题解决了吗。 我现在也是必须要打开clashx才能上网。可能是clashx和pro有冲突。我现在打开都会一定几率崩溃。删除也没解决问题

**Comment by jimmymitlavigne** [comment]
> 在试验性功能中关闭自动还原代理 然后取消系统代理不行吗

试过了。没有用

**Comment by luistrong** [comment]
我重新安装后解决了，以后不要轻易在线更新。

**Comment by yichengchen** [comment]
> 你好。请问你的问题解决了吗。 我现在也是必须要打开clashx才能上网。可能是clashx和pro有冲突。我现在打开都会一定几率崩溃。删除也没解决问题

pro的话检查一下dns

**Comment by yichengchen** [comment]
may fixed in 1.19.2

**Comment by WLyKan** [comment]
我的版本是1.50.0.1 ， 还是有这个问题，退出clashx 或者 关闭代理，浏览器就不能上网，但是聊天软件正常

**Comment by WLyKan** [comment]
退出 clashx 或者 clashx 不设置为代理，浏览器都不能打开网页，聊天软件这些能用。

我卸载了软件，重启，还是不能上网。

只能重新把 clashx 装上。。。。

打开Charles代理，提示`Charles cannot configure your proxy settings while it is on a read-only volume. ` 猜想是不是clashx把代理的配置文件设置了权限，导致系统其他程序没办法修改代理配置了。
