### ISSUE TITLE
clashX与Firefox有关Websocket的问题

### ISSUE THREAD

**Issue by imonace** [yichengchen/clashX#289]
Firefox代理选择“使用系统代理设置”，clashX启用设置为系统代理

问题表现为：使用Firefox时浏览斗鱼无法加载弹幕

经查发现斗鱼通过Websocket加载弹幕，firefox选择使用系统代理后ws连接发送0字节，无法加载。

之前一直以为是Firefox或者斗鱼的bug，因为Chrome是可以正常加载的，比较迷惑。

不是软件专业，对具体细节不太了解，描述可能不到位。希望作者可以关注一下这个问题，感谢！

**Comment by yichengchen** [comment]
这是firefox的bug，好像之前有人去给firfox社区提了 不知道后续
这是在clash core的issue https://github.com/Dreamacro/clash/issues/504
