### ISSUE TITLE
你好，Macox的clashx，domestic选择直连以后就失效，打开不了网址，必须选择代理

### ISSUE THREAD

**Issue by lwyzwd** [yichengchen/clashX#290]
domestic选择直连以后就失效，打开不了网址，必须选择代理

**Comment by yichengchen** [comment]
请检查配置文件。

**Comment by lwyzwd** [comment]
收到，谢谢



---原始邮件---
发件人: "Yicheng"<notifications@github.com&gt;
发送时间: 2020年4月16日(周四) 晚上8:15
收件人: "yichengchen/clashX"<clashX@noreply.github.com&gt;;
抄送: "lwyzwd"<zx1139822503@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题: Re: [yichengchen/clashX] 你好，Macox的clashx，domestic选择直连以后就失效，打开不了网址，必须选择代理 (#290)




 
请检查配置文件。
