### ISSUE TITLE
macos弹出应用程序clashx无法打开提示

### ISSUE THREAD

**Issue by hhuedu0512** [yichengchen/clashX#292]
下载了您的1.19.1和1.19.0两个版本的clashx，安装完成后都无法正常打开，弹出应用程序clashx无法打开的提示，我的imac系统版本是10.15.3.。同样的dmg文件在我的macbookair上可以安装并打开，版本是10.14. 请问是什么原因？

**Comment by yichengchen** [comment]
请确认文件只从本repo release页面下载的。10.15要求app经过苹果公正才能直接打开 否则需要右键打开
