### ISSUE TITLE
ClashX Dashboard无法加载

### ISSUE THREAD

**Issue by bill125** [yichengchen/clashX#293]
系统版本 macOS Mojave v10.14.6，ClashX版本v1.19.1
DashBoard不能正确加载，打开DashBoard显示的是黑屏，重新安装不能解决问题。

**Comment by joescon** [comment]
我今天也遇到同样的问题了。
系统版本 macOS Catalina v10.15.4 (19E287)。ClashX版本 v1.19.1

昨天还是正常使用的，今天突然就黑屏了
重新安装成v1.19.0也不行。

**Comment by yichengchen** [comment]
Try run `defaults delete com.west2online.clashx` in terminal then relogin the current system user account.

If still happens, right click the dashboard and open the `inspect(审查元素)`, take a screenshot and see what error happened.

**Comment by bill125** [comment]
Thanks for your advice. The command `defaults delete com.west2online.clashx` doesn't work for my case. I screenshot the dashboard after opening the `inspect element` option.
![WechatIMG774](https://user-images.githubusercontent.com/7195344/80120419-8979de80-85bd-11ea-9b7e-6724d7d6102d.png)

**Comment by bill125** [comment]
Hi, I fixed the problem by deleting the `config.yaml` in the config folder and reloading ClashX. I noticed that the `external-controller` changed from `127.0.0.1:6868` to `127.0.0.1:9090`. I am now able to visit the dashboard with a web browser with the url `127.0.0.1:9090/ui`. I guess some other software may be using the port 6668. Thanks again for your hint.

**Comment by yichengchen** [comment]
okey…but it’s still a little wired. Why the other functions works well except dashboard. I will continue investigate this problem when I have time.

**Comment by Ding-Fan** [comment]
I downloaded the latest ClashX(1.19.2) and ran into a similar problem. It keeps alerting "config loading fail .......", the Dashboard is also blank. Solved by comment out all the lines below `Rule:` in file `config.yaml` .
