### ISSUE TITLE
今天突然clashx无法代理上网了

### ISSUE THREAD

**Issue by skydavidshen** [yichengchen/clashX#294]
我的代理vps确认是正常的，因为我使用其他的代理app是可以正常访问外网的，但是clash x死活不可以，我用手机小火箭测试我的代理机器也是可以上网的，由此，可以判断是clash x有问题。
我昨天晚上都是可以正常使用clashx上网的，今天早上发现无法连接了，我关闭app重启，重启电脑，都尝试过，clashx 的配置一直没有改变过，没动过。

版本：1.19.1

![image](https://user-images.githubusercontent.com/2443687/79535028-d1c16a00-80ae-11ea-8537-516310608582.png)

**Comment by lianghx-319** [comment]
我也有同样的问题

**Comment by skydavidshen** [comment]
我找到解决方案了，把目前的配置文件改成如下：
https://github.com/V2RaySSR/Tools/edit/master/clash.yaml

仅仅替换掉代理配置那部分即可

**Comment by skydavidshen** [comment]
以上，方法可以解决该问题，我不知道是不是之前的配置方式现在的版本不兼容还是怎样，但是按照这个链接里面的配置，改掉代理配置部分即可

**Comment by skydavidshen** [comment]
已解决
