### ISSUE TITLE
trojan目前无法正常使用

### ISSUE THREAD

**Issue by Jacob-pixil** [yichengchen/clashX#298]
IOS端 相同订阅  QuantumultX 外网正常连接,   Mac端无法打开外网.

**Comment by U201413497** [comment]
trojan需要最新版的ClashX,订阅地址需要转换。

**Comment by Jacob-pixil** [comment]
用的是最新的, 转化我倒没有试过, 可以说说哪里转换吗

**Comment by Jacob-pixil** [comment]
> trojan需要最新版的ClashX,订阅地址需要转换。

用的是最新的1.19.1. 转换我试过, 但是可能方法不对, 请问可以说一下你的步骤吗?

**Comment by yichengchen** [comment]
is not clashx(UI) related issue. Try ask in core and provides more details.
