### ISSUE TITLE
可否考虑一下 加一个用户自定义规则

### ISSUE THREAD

**Issue by zl939144892** [yichengchen/clashX#299]
再现有规则上 可以自己指定一些域名走代理

**Comment by zhangyubushiyu** [comment]
同样期待这个功能

**Comment by yichengchen** [comment]
not clash(UI) issue. 
It’s recommended to use the proxy provider in your custom config files to achieve what you wanted.

https://lancellc.gitbook.io/clash/clash-config-file/proxy-provider
