### ISSUE TITLE
端口和默认线路

### ISSUE THREAD

**Issue by Tsahao** [yichengchen/clashX#3]
如果在配置文件更改端口，Clash 自动配置的系统代理端口仍然为 7890

系统的默认线路无法更改，每次开启均以默认线路连接

Edit Config Manually 功能不清楚

非常感谢！解决了 Mail 客户端使用 Gmail 的问题

**Comment by yichengchen** [comment]
1、如果在配置文件中修改端口号 需要在Config->reload config 或重启后并手动取消再设置代理自动配置才会进行更新。
2、默认线路Bug，会修改
3、ClashX是命令行软件[Clash](https://github.com/Dreamacro/clash)的一个gui实现。Clash使用配置文件来进行配置，使用Rest API进行通信。gui仅负责生成最基本的配置文件，更多操作需要自行编辑配置文件进行实现。

**Comment by yichengchen** [comment]
Fixed in 1.1.2

**Comment by dofy** [comment]
第一个 bug 貌似没有修复，不管配置文件中设置的端口是什么，代理都会被设置成 7890，重载配置也不行。
