### ISSUE TITLE
与libev兼容问题

### ISSUE THREAD

**Issue by Esinchung** [yichengchen/clashX#30]
服务端是ss-libev+ obfs 加密用chacha20-ietf-poly1305，clashx（版本1.4.1）支持么，加密用AEAD_CHACHA20_POLY1305或chacha20-ietf-poly1305都连不上，与libev不兼容么

**Comment by yichengchen** [comment]
obfs需要使用clashx 1.5版本

Esinchung <notifications@github.com>于2018年9月18日 周二12:36写道：
