### ISSUE TITLE
v2ray 动态端口无法连线

### ISSUE THREAD

**Issue by phlinhng** [yichengchen/clashX#300]
我有个设置动态端口的服务器， 其他代理软件都可以连，用clashX连不上。
后来在服务器那取消动态端口就连上了，推测clash-core或clashX不支持vmess动态端口。

**Comment by Antediluvian** [comment]
动态端口不推荐使用了吧，还是换 443 + tls。

**Comment by yichengchen** [comment]
Core not supported
