### ISSUE TITLE
网络连接正常时bechmark 一直 fail 

### ISSUE THREAD

**Issue by timesons** [yichengchen/clashX#305]
网络连接正常时bechmark 一直 fail

**Comment by yichengchen** [comment]
ClashX use `http://cp.cloudflare.com/generate_204` to run benchmark. If your server reject to visit this url, the benchmark would fail. You can custom benchmark url in experimental setting menu.

**Comment by yichengchen** [comment]
BTW, If you are using the latest pro version or compiled from latest master branch. There is an display issue for proxy provider and will be fixed soon.
