### ISSUE TITLE
Translate problem

### ISSUE THREAD

**Issue by cxy5014** [yichengchen/clashX#307]
When I use ClashX, some parts are not translated.
![Screen Shot 2020-04-25 at 15 37 34](https://user-images.githubusercontent.com/42842481/80274182-21391300-870b-11ea-85b7-63c6ac573731.png)

**Comment by yichengchen** [comment]
For the dashboard related issue, please go to https://github.com/Dreamacro/clash-dashboard
BTW, translate is a simple but also complex task, any pr is welcomed.
