### ISSUE TITLE
节点信息内外显示不一致

### ISSUE THREAD

**Issue by alexlee728** [yichengchen/clashX#311]
![image](https://user-images.githubusercontent.com/3183748/80297594-06bc7380-87b7-11ea-8371-ec904eae21eb.png)

![image](https://user-images.githubusercontent.com/3183748/80297649-9bbf6c80-87b7-11ea-9653-0c4afff59d38.png)

1、新版本规则后面的节点颜色变淡（几乎看不见了）是设计如此吗？
2、自动选择里左边和展开勾选的不是同一个是为啥？

**Comment by alexlee728** [comment]
发现手动选择任意节点，那个√都是在第一个。

**Comment by yichengchen** [comment]
用的是appcenter更新通道吧 有bug 重新从github release下载吧

对于1 颜色淡不是一直都是这样吗

**Comment by alexlee728** [comment]
> 用的是appcenter更新通道吧 有bug 重新从github release下载吧
【我是下载源码（master分支）编译安装的】

> 对于1 颜色淡不是一直都是这样吗 是之前版本不会吗
【变淡是这个版本才出现的】

**Comment by yichengchen** [comment]
master分支是有这个问题的 还在修 可以回退到tag的提交

**Comment by yichengchen** [comment]
fixed

**Comment by yichengchen** [comment]
fix后emoji又变暗了。。。

**Comment by alexlee728** [comment]
1、是了一下颜色不变灰了
2、手动选择节点的√的位置是对的，但是自动选择的√位置还是不对

**Comment by yichengchen** [comment]
不会吧？我这里看autogroup和fallbcak gourp看着都没问题的样子？

**Comment by yichengchen** [comment]
fixed

**Comment by alexlee728** [comment]
好了
