### ISSUE TITLE
测速一直失败

### ISSUE THREAD

**Issue by timesons** [yichengchen/clashX#316]
最近calshX 的测速总是失败，实际上连接是正常的，不管换成什么连接 一直都是测速失败，尝试了 clashflare 跟 apple的链接都是失败

**Comment by yichengchen** [comment]
请在实验性功能中设置正确的测速链接 比如 http://www.gstatic.com/generate_204

**Comment by yichengchen** [comment]
If you are using the latest pro version or compiled from latest master branch. There is an display issue for proxy provider and will be fixed soon.

**Comment by timesons** [comment]
> If you are using the latest pro version or compiled from latest master branch. There is an display issue for proxy provider and will be fixed soon.

试了不管 benchmark url设置成什么 测速都是失败的，clashx pro也尝试了，都是测速失败。
