### ISSUE TITLE
在Dashboard中无法更改proxy port

### ISSUE THREAD

**Issue by jubyshu** [yichengchen/clashX#318]
我使用的时候一直以来存在这样一个问题，当在Dashboard中更改代理端口时，比如把默认的55548换成7891，输入7891后回车，输入框还是原来的55548或直接变成0。当重启之后，端口又会变成另一组默认的数字。我都不知道自己是在怎样的条件下侥幸更改成功过一两次的。非常迷惑。

**Comment by yichengchen** [comment]
请认真阅读readme 在config.yaml中修改端口号 dashboard中的入口会禁止掉
