### ISSUE TITLE
托管配置时候报错提示： 托管配置文件格式不正确: ProxyGroup Proxy: 'proxies' is not a slice

### ISSUE THREAD

**Issue by WangMaoling** [yichengchen/clashX#321]
版本：Version:1.18.0
无法配置托管文件提示  ：
托管配置文件格式不正确: ProxyGroup Proxy: 'proxies' is not a slice
![image](https://user-images.githubusercontent.com/23271322/80570969-5c4e8580-8a2e-11ea-85e6-2246d44ceb73.png)
点开界面也没有设置proxy的地方
![image](https://user-images.githubusercontent.com/23271322/80571048-7ee09e80-8a2e-11ea-8311-4be10952c4de.png)

下面是配置文件夹里面的内容：
![image](https://user-images.githubusercontent.com/23271322/80571179-ba7b6880-8a2e-11ea-9130-de28d41bb5b6.png)

其中config.yaml内容是这样的
![image](https://user-images.githubusercontent.com/23271322/80571252-dda61800-8a2e-11ea-8f65-d871639421bd.png)

已经卸载删除config文件夹，从新安装多次了，依然没有用，麻烦大佬给看下

**Comment by lianxinping** [comment]
怎么解决的

**Comment by WangMaoling** [comment]
> 怎么解决的

没解决，换了其它软件

**Comment by Ninzero** [comment]
@WangMaoling 你贴出来的信息是无效的, 只有看了你的订阅地址下载的配置文件才能知道问题出在哪里.
