### ISSUE TITLE
Mac 用ClashX pro 会闪退

### ISSUE THREAD

**Issue by Tao-bug** [yichengchen/clashX#324]
mac OS Catalina 10.15.4
ClashX pro Version 1.19.2.4 (1.19.2.4)
- 老版本也一样会闪退，打开设置为系统代理模式，就立马闪退。

- 而且使用托管配置，提示没有权限添加文件，把文件下载下来，手动添加到配置文件夹，能正常配置。安装的时候，提示安装帮助也选的安装。

- 是从大佬提供的app center下载的app

**Comment by yichengchen** [comment]
是系统代理闪退还是增强模式闪退？

**Comment by Tao-bug** [comment]
> 是系统代理闪退还是增强模式闪退？

是系统代理就会闪退，增强模式更是不行

**Comment by yichengchen** [comment]
这就不科学了…（明明没动到过……

**Comment by Tao-bug** [comment]
> 这就不科学了…（明明没动到过……

有没有什么彻底删除的方法，我再尝试重新安装一下，还是说直接重新安装也行。。。还有我没法直接用机场给的拖配置，更新的时候提示没有添加文件的权限。大佬有什么建议吗

**Comment by yichengchen** [comment]
~/Library/Logs/DiagnosticReports/ 看看这里有没有崩溃日志

完全卸载有如下几个路径
app本身
~/.config/clash
 /Library/PrivilegedHelperTools/com.west2online.ClashX.ProxyConfigHelper
终端执行 `defaults delete com.west2online.clashxpro`

**Comment by Tao-bug** [comment]
> ~/Library/Logs/DiagnosticReports/ 看看这里有没有崩溃日志
> 
> 完全卸载有如下几个路径
> app本身
> ~/.config/clash
> /Library/PrivilegedHelperTools/com.west2online.ClashX.ProxyConfigHelper
> 终端执行 `defaults delete com.west2online.clashxpro`

重新尝试过了，clashx 和clashx pro都不能正常使用，或许与他们无缘吧。感谢用心解答问题，我猜想应该是我电脑里有什么不知道的东西与这款app有冲突，所以没法使用
