### ISSUE TITLE
"ClashX fail to create ~/.config/clash folder."

### ISSUE THREAD

**Issue by glenxoseph** [yichengchen/clashX#328]
下载后双击安装时，弹出窗口：
「ClashX fail to create ~/.config/clash folder. Please check privileges or manually create folder and restart ClashX.You don’t have permission to save the file “clash” in the folder “.config”.」
点击「Quit」后自动退出。

**Comment by glenxoseph** [comment]
Catalina 10.15

**Comment by glenxoseph** [comment]
Version 1.19.2

**Comment by yichengchen** [comment]
尝试用一下ClashPro最新版本 然后出现问题的时候看看 log `~/Library/Logs/ClashX Pro/` 里面显示创建失败的原因。

如果手动创建这个目录呢

**Comment by yichengchen** [comment]
You don’t have permission to save the file “clash” in the folder “.config”. 这是系统返回的错误。。。可能是对config文件夹没有权限写入？

**Comment by yangleyou** [comment]
自己手动建一下目录试试呢

**Comment by yangleyou** [comment]
我是用root权限建的，新建倒是成功了，软件还是闪退，感觉还是有问题


On 5/18/2020 16:40，Carvin<notifications@github.com> wrote：

自己建目录会显示file exists 但是cd 不进去,重开软件还是一样有提示

**Comment by yichengchen** [comment]
@lhz5166 @yangleyou 因为clashx是在普通用户权限运行的。所以目录也需要有普通用户权限。因此不能使用root权限建立。。估计.config目录是root的 所以无法创建成功。删除整个.config目录应该就可以了

**Comment by yangleyou** [comment]
多谢，关键是不知道.config目录是哪里来的，脑袋疼，我都放弃了，我还有个windows本，用clash没啥问题


On 5/24/2020 11:16，Yicheng<notifications@github.com> wrote：

@lhz5166@yangleyou 因为clashx是在普通用户权限运行的。所以目录也需要有普通用户权限。因此不能使用root权限建立。。估计.config目录是root的 所以无法创建成功。删除整个.config目录应该就可以了

**Comment by ryszme** [comment]
打开终端，保持当前目录，删掉.config文件（隐藏文件），再新建文件夹.config/clash。

**Comment by yichengchen** [comment]
close due to long time.
