### ISSUE TITLE
ClashX Pro启动出现端口打开失败，请尝试重启ClashX

### ISSUE THREAD

**Issue by hertzr** [yichengchen/clashX#330]
最近在启动ClashX pro时出现提示：启动出现端口打开失败，请尝试重启ClashX。并且软件没有启动成功（在重启休眠后大概率出现），日志中出现：
[error] enableProxy fail: 0 7891
[error] checkPortConfig: 0 7891
系统：10.15.4
版本已升级最新
尝试在配置中更改端口，仍然没有改变，日志错误端口也随之改变。
使用lsof查看启动前7891等端口没有被占用。
现在已经更换为ClashX使用，暂时没有发现这种情况
麻烦大佬看一下

**Comment by yichengchen** [comment]
clashx也有这个问题 只是弹窗没弹出来 下个版本会弹出来 具体原因暂时还不是很知道。。有人说过半分钟再开就好了。。。端口打开失败的时候继续使用能用但是可能会出现奇怪的问题

**Comment by yichengchen** [comment]
是不是开了允许局域网？

**Comment by hertzr** [comment]
> 是不是开了允许局域网？

没有开，默认只更改了开机启动与设为系统代理

**Comment by Marvin3Benz** [comment]
我也是出现Config loading Fail，说没有一个文件

**Comment by yichengchen** [comment]
I guess it should be fixed in the latest clashx/clashxpro version
