### ISSUE TITLE
关于功能的三个建议

### ISSUE THREAD

**Issue by fuhaiwei** [yichengchen/clashX#331]
① 速度显示部分能不能设置为只显示代理流量的速度
② 能否在控制台的连接界面可以过滤只显示代理连接
③ 能否更加智能的统计代理流量，如分月分域名汇总
总的来说就是因为代理流量有总量限制，所以需要单独统计

**Comment by yichengchen** [comment]
基本上由于core api的限制都无法实现。需要上游core提供api才行
