### ISSUE TITLE
bug 1.20版本貌似有bug

### ISSUE THREAD

**Issue by CrazyMouse** [yichengchen/clashX#333]
升级新版本后发现退出的时候v2ray进程不会被关闭，再次启动clashx的时候，会提示端口占用

**Comment by QiQiBiBi** [comment]
同，升级后才有的好像，吓我一跳，还好用的T协议，用回T协议专门的工具应下急。

**Comment by CrazyMouse** [comment]
> 同，升级后才有的好像，吓我一跳，还好用的T协议，用回T协议专门的工具应下急。

随系统启动后不关闭clashx还是能凑合用着

**Comment by yichengchen** [comment]
May fixed in 20.1
