### ISSUE TITLE
是否有类似 cfw-profile-mixin 的配置方法

### ISSUE THREAD

**Issue by clockcloud** [yichengchen/clashX#337]
是否有批量修改订阅配置文件的方法，或者之后考虑提供类似方法？

**Comment by yichengchen** [comment]
maybe not. probably is a good way to write your custom config with proxy-provider

**Comment by weijinsun** [comment]
proxy-provider 这个是什么?  有时候会有一个需求,就是有自定义的配置,但是订阅的配置会覆盖自定义配置,有没有方式,自定义配置和订阅配置同时都生效的方式
