### ISSUE TITLE
请问ClashX有支持Mac OS10.11的版本吗？系统比较旧，但是目前的releases都是支持10.12及以上的

### ISSUE THREAD

**Issue by FloraWang0828** [yichengchen/clashX#338]

**Comment by hao-lh** [comment]
Yeah, the same question here.
Or could you let me know where can I download the legacy version?
Thanks!

**Comment by yichengchen** [comment]
ClashX is not support system below 10.12 due the third party dependencies requirment. Maybe very early version of clashx support 10.11 in https://install.appcenter.ms/users/clashx/apps/clashx/distribution_groups/public but may contains lots of bugs and can not get the latest feature.

**Comment by paradiseduo** [comment]
clash是用Swift5开发的，早期的系统不支持swift，因此无法做到兼容。要么升级系统，要么考虑用别的软件。
