### ISSUE TITLE
M1芯片mac下，导入配置后无显示proxy

### ISSUE THREAD

**Issue by aa36** [yichengchen/clashX#346]
在一台老的mac上，clashx运行正常。但在m1芯片的mac上导入配置后菜单栏无显示proxy，是什么问题？

**Comment by aa36** [comment]
已解决，通过老版的clashx导入配置后就能正常显示。不知是什么问题

**Comment by yichengchen** [comment]
啊？还有这种区别……试验性功能中的icloud开了吗 开的话读取的是icloud文件夹中的配置

**Comment by yichengchen** [comment]
track using https://github.com/yichengchen/clashX/issues/347
