### ISSUE TITLE
big sur  代理部分空白

### ISSUE THREAD

**Issue by lyydhy** [yichengchen/clashX#347]
不是m1 就以前的老机型 升级到big sur  后 代理部分就空白显示了 重新 重新安装都试过了  代理部分一直空白

**Comment by lyydhy** [comment]
![Uploading iShot2020-12-09 10.06.49.png…]()

**Comment by lyydhy** [comment]
![iShot2020-12-09 10 06 49](https://user-images.githubusercontent.com/19465770/101564896-f041f000-3a06-11eb-99dc-caa182831213.png)

**Comment by yichengchen** [comment]
确定选择的config没问题吗？ 看看是否在试验性功能开了 icloud， 如果开了icloud的话读取的是icloud 文件夹里的配置文件。我在m1设备上用了一下看着好像没什么问题来着……

**Comment by yichengchen** [comment]
检查一下配置文件 代理字段是 proxies: 吗 上古旧版是Proxy不兼容

**Comment by GeneralUtensils** [comment]
配置没问题，也出现了这个问题，无法选中订阅，rm -f 掉clashx文件都不行，最新的CXP

**Comment by lyydhy** [comment]
> 确定选择的config没问题吗？ 看看是否在试验性功能开了 icloud， 如果开了icloud的话读取的是icloud 文件夹里的配置文件

不是icloud  这个选项我都选不了

> 检查一下配置文件 代理字段是 proxies: 吗 上古旧版是Proxy不兼容

是proxies

**Comment by yichengchen** [comment]
我本地试了一下 11.0.1上clashx clashxpro 用了dler和cordcloud的订阅没法复现。。可以麻烦贴一下app log 和 脱敏的配置文件吗

**Comment by lyydhy** [comment]
> 我本地试了一下 11.0.1上clashx clashxpro 用了dler和cordcloud的订阅没法复现。。可以麻烦贴一下app log 和 脱敏的配置文件吗

我后面改配置文件后 可以了 就是每次启动软件的时候 总不能第一时间选择到我自己的配置文件 不知道什么原因 可能是我操作不对吧  不过我还是用v2 去了 那个稳定 简单    谢谢

**Comment by Fury76** [comment]
问题复现了，修改配置文件中的rules，在配置中将部分DIRECT的改为Proxy或者PROXY，然后重新载入配置，代理就消失了
查看日志发现日志报如下错误
2020/12/14 03:04:34:778  [info] rules[0] [DOMAIN-SUFFIX,google.com,Proxy] error: proxy [Proxy] not found
2020/12/14 03:04:37:350  [debug] Optional(<WKNavigation: 0x7fe01588e800>)
2020/12/14 03:05:02:689  [info] rules[0] [DOMAIN-SUFFIX,google.com,Proxy] error: proxy [Proxy] not found
2020/12/14 03:05:08:518  [debug] Optional(<WKNavigation: 0x7fe015013000>)
2020/12/14 03:05:26:452  [debug] Optional(<WKNavigation: 0x7fe01408fa00>)
2020/12/14 03:10:06:680  [debug] loggingWebSocket did Connect
2020/12/14 03:10:06:680  [debug] trafficWebSocket did Connect
2020/12/14 03:10:11:037  [info] rules[0] [DOMAIN-SUFFIX,google.com,Proxy] error: proxy [Proxy] not found
2020/12/14 03:10:14:023  [debug] Optional(<WKNavigation: 0x7fe0158a5e00>)
2020/12/14 03:11:51:825  [debug] Optional(<WKNavigation: 0x7fe016808200>)
2020/12/14 03:11:57:229  [debug] loggingWebSocket did Connect
2020/12/14 03:11:57:230  [debug] trafficWebSocket did Connect
2020/12/14 03:11:59:663  [debug] Optional(<WKNavigation: 0x7fe0138d3a00>)
2020/12/14 03:12:31:750  [info] rules[0] [DOMAIN-SUFFIX,google.com,PROXY] error: proxy [PROXY] not found

**Comment by llkhs** [comment]
你proxy-groups里面有包含Proxy或者PROXY分组吗？

**Comment by Fury76** [comment]
> 你proxy-groups里面有包含Proxy或者PROXY分组吗？

没有，group里面是空的

**Comment by llkhs** [comment]
> * DOMAIN-SUFFIX,google.com,Proxy

问题就出在这里，没有 Proxy 这个字段，或者里面没有东西，你指向它就报错了。

**Comment by yichengchen** [comment]
看起来是配置的问题
