### ISSUE TITLE
Terminal无法代理

### ISSUE THREAD

**Issue by TheodoreHills** [yichengchen/clashX#353]
在通过直接复制终端的代理命令之后拷贝进入终端，终端依然无法访问google等网站

**Comment by llkhs** [comment]
你的意思是在Terminal > ping Google.com显示time out？

**Comment by TheodoreHills** [comment]
是的，显示Request timeout

**Comment by llkhs** [comment]
了解一下osi模型和ping的协议，ping time out不代表没有成功代理，你可以试着Rew一个repository看速度有没有改变。

**Comment by llkhs** [comment]
了解一下OSI模型和ping的协议,terminal>ping timeout不代表没有成功proxy.你可以试着RawGithubURL观察速度来判断proxy成功与否.

**Comment by yichengchen** [comment]
可以尝试一下使用clashx pro 开启增强模式
