### ISSUE TITLE
macos10.14.6打不开。点没反应！有日志

### ISSUE THREAD

**Issue by toosui** [yichengchen/clashX#354]
Process:               ClashXR [955]
Path:                  /Applications/ClashXR.app/Contents/MacOS/ClashXR
Identifier:            com.west2online.ClashXR
Version:               ???
Code Type:             X86-64 (Native)
Parent Process:        ??? [1]
Responsible:           ClashXR [955]
User ID:               501

Date/Time:             2020-12-14 14:18:07.223 +0800
OS Version:            Mac OS X 10.14.6 (18G103)
Report Version:        12
Bridge OS Version:     4.0 (17P572)
Anonymous UUID:        BE0B4209-4B23-4DA2-5520-B566DFD0B610

Time Awake Since Boot: 1200 seconds

System Integrity Protection: enabled

Crashed Thread:        0

Exception Type:        EXC_CRASH (Code Signature Invalid)
Exception Codes:       0x0000000000000000, 0x0000000000000000
Exception Note:        EXC_CORPSE_NOTIFY

Termination Reason:    Namespace CODESIGNING, Code 0x1

kernel messages:

VM Regions Near 0 (cr2):
--> 
    __TEXT                 000000010fe30000-0000000110337000 [ 5148K] r-x/r-x SM=COW  

Thread 0 Crashed:
0                                 	0x000000011ca78000 _dyld_start + 0

Thread 0 crashed with X86 Thread State (64-bit):
  rax: 0x0000000000000000  rbx: 0x0000000000000000  rcx: 0x0000000000000000  rdx: 0x0000000000000000
  rdi: 0x0000000000000000  rsi: 0x0000000000000000  rbp: 0x0000000000000000  rsp: 0x00007ffedfdcfbd0
   r8: 0x0000000000000000   r9: 0x0000000000000000  r10: 0x0000000000000000  r11: 0x0000000000000000
  r12: 0x0000000000000000  r13: 0x0000000000000000  r14: 0x0000000000000000  r15: 0x0000000000000000
  rip: 0x000000011ca78000  rfl: 0x0000000000000200  cr2: 0x0000000000000000
  
Logical CPU:     0
Error Code:      0x00000000
Trap Number:     0

Binary Images:
       0x10fe30000 -        0x110336ff7 + (0) <50657EF3-219A-3EB7-9E55-27CEE5DB4D87> 
       0x11ca77000 -        0x11cae170f + (655.1.1) <DFC3C4AF-6F97-3B34-B18D-7DCB23F2A83A> 

External Modification Summary:
  Calls made by other processes targeting this process:
    task_for_pid: 0
    thread_create: 0
    thread_set_state: 0
  Calls made by this process:
    task_for_pid: 0
    thread_create: 0
    thread_set_state: 0
  Calls made by all processes on this machine:
    task_for_pid: 765
    thread_create: 0
    thread_set_state: 0

VM Region Summary:
ReadOnly portion of Libraries: Total=8960K resident=0K(0%) swapped_out_or_unallocated=8960K(100%)
Writable regions: Total=8560K written=0K(0%) resident=0K(0%) swapped_out=0K(0%) unallocated=8560K(100%)
 
                                VIRTUAL   REGION 
REGION TYPE                        SIZE    COUNT (non-coalesced) 
===========                     =======  ======= 
STACK GUARD                       56.0M        1 
Stack                             8192K        1 
__DATA                            5456K        4 
__LINKEDIT                        3384K        2 
__TEXT                            5576K        2 
shared memory                        8K        2 
===========                     =======  ======= 
TOTAL                             78.1M       12

**Comment by yichengchen** [comment]
这个是clashxr 不是本项目clashx。。用release页面下载的clashx试试？
