### ISSUE TITLE
1.31.1和1.31.0如果设置开机启动，都无法运行，系统10.13.6 。

### ISSUE THREAD

**Issue by leonhart118** [yichengchen/clashX#356]
1.31.1和1.31.0如果设置开机启动，都无法运行，系统10.13.6 。

另外发现clashx不运行，很多软件都无法联网——这种情况正常吗？

**Comment by yichengchen** [comment]
可以提供一下log吗。。我这里没有10.13的系统测试。软件无法联网应该是因为系统代理设置没有恢复。同时帮忙看看 ~/Library/Logs/DiagnosticReports下有没有相关的crash log

**Comment by pluone** [comment]
10.15.7开机自启动有同样问题 ，
每次上不去谷歌发现代理未启动，查看发现进程存在，强制结束进程，然后重启clashx恢复正常

**Comment by yichengchen** [comment]
31.2已经做了尝试修复，先close
