### ISSUE TITLE
Can you provide a sample bunch JSON file format?

### ISSUE THREAD

**Issue by ky0nch3ng** [yichengchen/clashX#36]
When Import JSON file from windows ss client, an error occurred.

Can you provide a sample bunch JSON file format? Thx.

**Comment by yichengchen** [comment]
It should be the same as Shadowsocks-NG. But there is a bug while handling with aead  encryption methods

**Comment by ky0nch3ng** [comment]
@yichengchen Not just json file from  Shadowsocks-NG, all ss config json file can not import to clashx.

aead encryption methods displays import error.
aes-256-cfb and other old method displays success, but not import to clashx, config .yml file has not renewed.
