### ISSUE TITLE
Big Sur 11.1 clashx Pro 1.31.1.1 退出以后无法联网 

### ISSUE THREAD

**Issue by qyzxg** [yichengchen/clashX#361]
系统代理 取消，关闭自动还原之前代理 打开 然后再退出，也还是不行，不知道为啥

**Comment by denghulk** [comment]
me too

**Comment by yichengchen** [comment]
看看网络设置中的代理、dns 是哪项没有恢复？ 看看clashx的log？

**Comment by qyzxg** [comment]
应该是dns dns 设为 114.114.114.114 就可以了

**Comment by denghulk** [comment]
已验证，是开启增强模式后再退出会导致如上的问题，不开启不会

**Comment by cobig** [comment]
关闭clash x后需要关闭wifi，然后重新打开wifi才会有网络

**Comment by denghulk** [comment]
这个应该是bug吧，每次关闭要手动改dns才能恢复

**Comment by yichengchen** [comment]
有尝试1.31.2.1吗

**Comment by ljybill** [comment]
Hi，使用big sur能够正常连接代码？我这边无法连接 ，最新稳定版
