### ISSUE TITLE
VMess模式下，关于ws访问失败的问题

### ISSUE THREAD

**Issue by tengfei-xy** [yichengchen/clashX#362]
需要注释ws参数的配置文件，加载配置文件后，取消注释ws参数才能爬墙。

注释参数如下：
udp: true
tls: true
skip-cert-verify: true
network: ws
ws-path: /csstyle
ws-headers:
Host: xunyang.monster

请问是我配置的参数问题吗？

系统：macOS BigSur 11.1 (20C69)
ClashX：0d33dc

**Comment by tengfei-xy** [comment]
当前有报错[warning] [TCP] dial PROXY (match DomainKeyword/github) to github.com error: server:443 connect error: lookup server: no such host

**Comment by dev4u** [comment]
试试注释掉udp，ws不支持udp转发。

**Comment by dev4u** [comment]
试试注释掉udp，ws不支持udp转发。

**Comment by yichengchen** [comment]
这个建议到clash的repo按模板提详细的issue.超出clashx这个ui的范围啦
