### ISSUE TITLE
试验性功能--更新IP数据库失败

### ISSUE THREAD

**Issue by wang93wei** [yichengchen/clashX#363]
![image](https://user-images.githubusercontent.com/6371053/102320731-ac775980-3fb7-11eb-8b3d-27b1d7093d0c.png)

可以换成这个：https://github.com/Hackl0us/GeoIP2-CN

**Comment by dev4u** [comment]
更新不了ip库，和你提供地址的库有什么关系吗？

**Comment by yichengchen** [comment]
这个已经修了还没release 最近很忙 估计周末会做一下自定义url一起上

**Comment by wang93wei** [comment]
> 更新不了ip库，和你提供地址的库有什么关系吗？

有啊，，，最小巧、最准确、最实用的 中国大陆 IP 段 + GeoIP2 数据库

**Comment by wang93wei** [comment]
> 这个已经修了还没release 最近很忙 估计周末会做一下自定义url一起上

感谢
