### ISSUE TITLE
Big sur 11.1 clashx pro 1.31.1.1 增强功能无法打开

### ISSUE THREAD

**Issue by forex24** [yichengchen/clashX#364]
如题

**Comment by yichengchen** [comment]
提供一下log

**Comment by forex24** [comment]
按照以前issue里的方法，我在终端里运行clashx pro，增强模式就可以里，然后退出，重新从UI里运行，也可以了，请关闭这个issue

**Comment by 4tj** [comment]
> 按照以前issue里的方法，我在终端里运行clashx pro，增强模式就可以里，然后退出，重新从UI里运行，也可以了，请关闭这个issue

怎么运行，我也遇到这个问题了
