### ISSUE TITLE
macOS big sur 11.1 下，开机自启动或重启clashX时配置加载不正确

### ISSUE THREAD

**Issue by zeddit** [yichengchen/clashX#367]
<img width="295" alt="截屏2020-12-18 下午2 47 28" src="https://user-images.githubusercontent.com/30164206/102583896-6c8fae00-4140-11eb-834d-e1dfffa368f8.png">
<img width="314" alt="截屏2020-12-18 下午2 48 04" src="https://user-images.githubusercontent.com/30164206/102583906-6f8a9e80-4140-11eb-9359-7c4a6c9e21a5.png">

如图所示，按配置文件加载的话应该为上图，只有PROXY的策略组，规则判断模式。

但是开机自启动后，或退出clashX再打开后，会多出GLOBAL策略组的选项，而且模式为全局，如下图；手动reload配置文件后恢复上图。

猜测clashX在启动startup时，加载配置文件时有些问题。clashX版本为1.31.1 0d33dc.

**Comment by yichengchen** [comment]
无法复现这个问题，尝试一下控制台执行 一下 defaults read com.west2online.clashx selectOutBoundMode 看看输出结果？
执行 defaults delete com.west2online.clashx 同时删除配置文件夹中的默认配置(config.yaml) 看是否能解决问题? (自己的配置另取个名字）

**Comment by zeddit** [comment]
感谢回复，问题解决。
1. defaults read com.west2online.clashx selectOutBoundMode 返回 global
2. 使用 defaults delete com.west2online.clashx 删除后，调用 defaults read com.west2online.clashx selectOutBoundMode 返回 The domain/default pair of (com.west2online.clashx, selectOutBoundMode) does not exist
3. 之前配置是直接改的默认配置config.yaml里的内容，没有自己创建新的配置文件，所以这一步没有删除默认配置
4. 完成上述操作后，关闭clashX，重新打开不再出现GLOBAL选项
