### ISSUE TITLE
clashx pro (m1) telegram 无法连接到 7890代理端口

### ISSUE THREAD

**Issue by vast-z** [yichengchen/clashX#368]
麻烦作者看一下。m1版本clashx pro，telegram链接7890一直无法连接，非常感谢您！

**Comment by yichengchen** [comment]
我这里试试正常的 可以提供一下log 或者确认一下 clashx 菜单 帮助 中的端口号

**Comment by vast-z** [comment]
非常感谢您的回复。这是我的一些截图。telegram显示一直在转圈圈，无法连接上。
![config](https://github.com/vast-z/pic/blob/master/m1-clashxpro1.png)
![config](https://github.com/vast-z/pic/blob/master/m1-clashxpro2.png)

**Comment by dev4u** [comment]
试试把tg的代理按钮关闭后，再重新打开。

**Comment by vast-z** [comment]
我已经进行了尝试，包括重新打开代理按钮，重新打开软件，重启电脑。。emm。不知道问题出在了哪里，在日志中没有相关的显示。。。

**Comment by vast-z** [comment]
貌似可以了。。哈哈 非常感谢您。

**Comment by 907904228** [comment]
重新启动下telegram就行了

**Comment by ajfg93** [comment]
> 重新启动下telegram就行了

+1 重启telgeram解决，有点魔幻。

**Comment by stimw** [comment]
我遇到了。。。重启没解决

**Comment by vickllny** [comment]
> 我遇到了。。。重启没解决

我登录的时候 遇到了设置了代理没有效果。但是我开启了增强模式就可以登录了，登录进去也不使用增强模式也可以使用😝

**Comment by pangwen** [comment]
我遇到了。。 网页测试socks5代理正常，同样配置telegram就不行

**Comment by ngn999** [comment]
重启OK, 这是什么设置才会这样.

**Comment by pangwen** [comment]
重启也不行，后面也不知道咋抽风就好了……
________________________________
发件人: ngn999 ***@***.***>
发送时间: Saturday, July 24, 2021 11:32:52 AM
收件人: yichengchen/clashX ***@***.***>
抄送: pangwen ***@***.***>; Comment ***@***.***>
主题: Re: [yichengchen/clashX] clashx pro (m1) telegram 无法连接到 7890代理端口 (#368)


重启OK, 这是什么设置才会这样.

―

**Comment by amoyyean** [comment]
你们现在都可以了吗？

我是登录界面连接会一直打转。手机热点全局socks5 proxy连上过一次，然后Mac系统(Catalina)的Telegram仍然无法登录成功，提示timeout。请问如何调查问题根源？

**Comment by Evilrabbit520** [comment]
我的Catalina重启也没解决，求帮忙

**Comment by GreenHandTo** [comment]
> 我的Catalina重启也没解决，求帮忙

看看你的配置文件对不对，我在其他地方生成的配置文件貌似不对，有个socks-port，都被我改成mixed-port了
<img width="334" alt="截屏2021-08-18 23 58 03" src="https://user-images.githubusercontent.com/32973023/129931510-ad7325c7-d4e8-4e8a-8228-aa9e5f0ec96d.png">

**Comment by MemoryNoodles** [comment]
> 貌似可以了。。哈哈 非常感谢您。

 我这边也是m1 使用的clashx，使用telegram关闭或设置代理都不行。你是咋解决的

**Comment by nicolastinkl** [comment]
重启就可以解决，，，，，魔幻++++++1

**Comment by sweethaozi** [comment]
重启就可以解决，，，，，魔幻++++++++1

**Comment by ZEKEOO** [comment]
一样的情况，本地和端口都正确，tg添加一直显示connecting，重启tg还是这样。
结果重启电脑就好了。。。。好无语

**Comment by qDonl** [comment]
重启tg和电脑都不管用。。。

**Comment by HuimingChu** [comment]
重启之后，弹出来要扫二维码
然后扫了就上去了，搞半天端口啥的，就是找不到问题。
真的魔性。
