### ISSUE TITLE
Clashx Pro 在终端下ping不通任何外网地址

### ISSUE THREAD

**Issue by chou108** [yichengchen/clashX#369]
Pro版本在终端下ping不通任何外网IP地址，内网的IP可以ping通

ClashX没这问题

**Comment by yichengchen** [comment]
增强模式会影响ping

**Comment by chou108** [comment]
我明白大概是ClashX只处理了TCP和UDP，但ICMP直接放行不可以吗? :-)

**Comment by BenjaminGao** [comment]
> 我明白大概是ClashX只处理了TCP和UDP，但ICMP直接放行不可以吗? :-)

是。
