### ISSUE TITLE
重启系统时，偶尔出现CXP（1.31.1.1）增强模式开启失败

### ISSUE THREAD

**Issue by zealson** [yichengchen/clashX#372]
请问有时重启Mac，CXP的增强模式偶尔会失败，手动再次开启，还是开不了，只能重启CXP，再开增强才能成功；
推断是刚进入系统没有检查到网络，失败后的状态没revert，希望得到解决，谢谢！

**Comment by yichengchen** [comment]
I believe this should be fix in the latest version. If problem still exist, feel free to open a new issue
