### ISSUE TITLE
最新macOS Big Sur下无法修改代理端口

### ISSUE THREAD

**Issue by 138907168** [yichengchen/clashX#373]
软件版本：1.31.2
系统操作版本：macOS Big Sur

订阅配置后，HTTP端口和Socks端口都是7890，在使用Telegram设置代理端口为7890时候就是连接不上，尝试手动在配置文件中修改端口后，重新载入配置还是一样的端口不会变都是7890

**Comment by dev4u** [comment]
> 软件版本：1.31.2
> 系统操作版本：macOS Big Sur
> 
> 订阅配置后，HTTP端口和Socks端口都是7890，在使用Telegram设置代理端口为7890时候就是连接不上，尝试手动在配置文件中修改端口后，重新载入配置还是一样的端口不会变都是7890

tg连不了，请关闭代理开关后，再重新打开。
修改端口，一般需要重启应用才生效。

**Comment by 138907168** [comment]
> > 软件版本：1.31.2
> > 系统操作版本：macOS Big Sur
> > 订阅配置后，HTTP端口和Socks端口都是7890，在使用Telegram设置代理端口为7890时候就是连接不上，尝试手动在配置文件中修改端口后，重新载入配置还是一样的端口不会变都是7890
> 
> tg连不了，请关闭代理开关后，再重新打开。
> 修改端口，一般需要重启应用才生效。

尝试过重启应用了，但是还是不会生效，端口检测还是一直显示HTTP跟Socks都是7890端口

**Comment by yichengchen** [comment]
查看readme，需要修改自带的config.yaml,其他配置文件中的端口字段无效。
