### ISSUE TITLE
mac应用比如maven退出clashx后访问局域网maven仓库无法访问

### ISSUE THREAD

**Issue by ysysdzz** [yichengchen/clashX#374]
ClashX安装后桌面程序访问局域网域名无法访问
桌面程序提示nexus.xxx.cloud:80 failed to respond
ClashX提示日志
2020/12/21 07:54:49:804 [info] [TCP] 127.0.0.1:63016 --> nexus.xxx.cloud match Match() using Proxy[Japan-TY2-4-Rate:1.0]
将将ClashX退出后依然无法访问，提示：
(http://nexus.xxx.cloud/nexus/content/groups/dev-repo): Connect to 127.0.0.1:7890 [/127.0.0.1] failed: Connection refused (Connection refused)
备注：退出ClashX后网络---高级---代理里面选中的代理内容都已经自动取消选中，DNS也已经清空

**Comment by ysysdzz** [comment]
Ping命令可以通
PING nexus.xxx.cloud (192.168.46.8): 56 data bytes
64 bytes from 192.168.46.8: icmp_seq=0 ttl=63 time=2.789 ms
64 bytes from 192.168.46.8: icmp_seq=1 ttl=63 time=3.183 ms
64 bytes from 192.168.46.8: icmp_seq=2 ttl=63 time=8.555 ms

**Comment by yichengchen** [comment]
是不是maven 缓存了代理设置。。

**Comment by ysysdzz** [comment]
> 是不是maven 缓存了代理设置。。

应该不是，不光maven，局域网内idea访问eureka也有这个问题

**Comment by shadow-boy** [comment]
mac 跑过springboot项目之后，启动clashx pro 显示“系统代理设置已被另一进程修改，clashx不再是系统默认代理”，咋办

**Comment by ysysdzz** [comment]
> 是不是maven 缓存了代理设置。。

我安装了surge3，退出clashX，然后启动surge3，开启surge的系统代理，然后再退出surge。
一顿操作后会把clashx残留的配置清除，上面的问题就好了，我觉得clashx还是有些bug
