### ISSUE TITLE
[Feature Request] Merge system hosts file with clash config

### ISSUE THREAD

**Issue by SukkaW** [yichengchen/clashX#375]
Is it possible for ClashX to read `/etc/hosts` and merge it with Clash's config? Since clash core refuses to implement the feature, is it possible to achieve it in ClashX?

Related issue: #104 #138 #262

**Comment by yichengchen** [comment]
Is there a good way to parse system hosts file?

**Comment by SukkaW** [comment]
> Is there a good way to parse system hosts file?

macOS system hosts file complied with https://tools.ietf.org/html/rfc1123.

**Comment by yichengchen** [comment]
it should be done by core
