### ISSUE TITLE
建议：上网环境经常变化，请问dns配置段中的nameserver的参数能否取系统当前的默认配置

### ISSUE THREAD

**Issue by jetvster** [yichengchen/clashX#376]
因为我的工作环境老发生变化，移动、联通、电信都会有，如果只用固定的nameserver经常会碰到不能解析或者解析的地址访问非常缓慢的情况，所以经常需要更换。

建议一个功能：dns的nameserver如果不指定则取系统当前默认配置，不知能否在后续版本中实现，谢谢各位大大～

**Comment by jetvster** [comment]
[](https://github.com/Dreamacro/clash/issues/1141)

**Comment by jetvster** [comment]
[Clash板块重新提了](https://github.com/Dreamacro/clash/issues/1141)

**Comment by kongminhao** [comment]
感觉似乎这是一个操作系统相关的需求，建议还是不同客户端分开实现的好？
