### ISSUE TITLE
macOS BigSur 下http与sock端口为0且端口无法修改，只有混合端口

### ISSUE THREAD

**Issue by itenl** [yichengchen/clashX#377]
![image](https://user-images.githubusercontent.com/16585374/102956581-64a28600-4513-11eb-8796-a47e57c05963.png)

如图

**Comment by troyliu0105** [comment]
我也遇到了同样的问题。。。

**Comment by troyliu0105** [comment]
@itenl  你需要修改 config.yml 文件，而不是你自己的配置文件。
<img width="990" alt="image" src="https://user-images.githubusercontent.com/5518286/102965341-9d008f00-4528-11eb-868b-0b54a21e3481.png">

**Comment by itenl** [comment]
@troyliu0105 经尝试可行，非常感谢

添加以下自定义端口

``` shell
# HTTP port
port: 7890
# SOCKS5 port
socks-port: 7891
# (HTTP and SOCKS5 in one port)
mixed-port: 7892
```

**Comment by lincenying** [comment]
![image](https://user-images.githubusercontent.com/10840991/103325276-054df400-4a86-11eb-900a-30668c5e275e.png)

代理能生效, 但是UI看显示的端口号还是0

**Comment by wayone** [comment]
<img width="1409" alt="iShot2021-07-28 16 35 45" src="https://user-images.githubusercontent.com/10210378/127294226-cd4c8f90-e76e-45c2-9726-ae9ed93e8c41.png">
socks5 和 HTTP 代理端口都是 0，无法修改。在 telegram 里使用 socks + 混合代理端口，无法连接。
