### ISSUE TITLE
更新托管配置文件(订阅)失败

### ISSUE THREAD

**Issue by MiroChao** [yichengchen/clashX#378]
更新订阅的时候显示下图
托管配置文件格式不正确: yaml: unmarshal errors:
  line 1: cannot unmarshal !!str `dm1lc3M...` into config.RawConfig

有没有办法解决呢
![image](https://user-images.githubusercontent.com/11206594/103057984-f2e23f00-45db-11eb-8b53-1cdfeaa47ab9.png)

**Comment by whisterlee** [comment]
同样出现这个问题
Big Sur 11.2

日志
2020/12/28 02:55:05:906  [debug] checkInstall
2020/12/28 02:55:05:914  [info] Trying start proxy
2020/12/28 02:55:05:921  [info] set up autoUpateTimer
2020/12/28 02:55:05:922  [info] Tigger config auto update check
2020/12/28 02:55:05:935  [info] port config updated,new: 7890,7890
2020/12/28 02:55:05:939  [info] Saving Remote Config Setting
2020/12/28 02:55:05:940  [debug] loggingWebSocket did Connect
2020/12/28 02:55:05:940  [debug] trafficWebSocket did Connect
2020/12/28 02:55:05:988  [debug] helper version 1.7 require version 1.7
2020/12/28 02:55:05:988  [info] check helper using time: 0.08067202568054199
2020/12/28 02:55:28:928  [info] Saving Remote Config Setting
2020/12/28 02:55:51:443  [error] yaml: unmarshal errors:
  line 1: cannot unmarshal !!str `c3NyOi8...` into config.RawConfig
2020/12/28 02:55:54:760  [info] Saving Remote Config Setting

**Comment by lelelegrand** [comment]
> 同样出现这个问题
> Big Sur 11.2
> 
> 日志
> 2020/12/28 02:55:05:906 [debug] checkInstall
> 2020/12/28 02:55:05:914 [info] Trying start proxy
> 2020/12/28 02:55:05:921 [info] set up autoUpateTimer
> 2020/12/28 02:55:05:922 [info] Tigger config auto update check
> 2020/12/28 02:55:05:935 [info] port config updated,new: 7890,7890
> 2020/12/28 02:55:05:939 [info] Saving Remote Config Setting
> 2020/12/28 02:55:05:940 [debug] loggingWebSocket did Connect
> 2020/12/28 02:55:05:940 [debug] trafficWebSocket did Connect
> 2020/12/28 02:55:05:988 [debug] helper version 1.7 require version 1.7
> 2020/12/28 02:55:05:988 [info] check helper using time: 0.08067202568054199
> 2020/12/28 02:55:28:928 [info] Saving Remote Config Setting
> 2020/12/28 02:55:51:443 [error] yaml: unmarshal errors:
> line 1: cannot unmarshal !!str `c3NyOi8...` into config.RawConfig
> 2020/12/28 02:55:54:760 [info] Saving Remote Config Setting

我也是同样的问题，win 7 是订阅失败，mac能成功但是不出来节点

**Comment by whisterlee** [comment]
> 同样出现这个问题
> Big Sur 11.2
> 
> 日志
> 2020/12/28 02:55:05:906 [debug] checkInstall
> 2020/12/28 02:55:05:914 [info] Trying start proxy
> 2020/12/28 02:55:05:921 [info] set up autoUpateTimer
> 2020/12/28 02:55:05:922 [info] Tigger config auto update check
> 2020/12/28 02:55:05:935 [info] port config updated,new: 7890,7890
> 2020/12/28 02:55:05:939 [info] Saving Remote Config Setting
> 2020/12/28 02:55:05:940 [debug] loggingWebSocket did Connect
> 2020/12/28 02:55:05:940 [debug] trafficWebSocket did Connect
> 2020/12/28 02:55:05:988 [debug] helper version 1.7 require version 1.7
> 2020/12/28 02:55:05:988 [info] check helper using time: 0.08067202568054199
> 2020/12/28 02:55:28:928 [info] Saving Remote Config Setting
> 2020/12/28 02:55:51:443 [error] yaml: unmarshal errors:
> line 1: cannot unmarshal !!str `c3NyOi8...` into config.RawConfig
> 2020/12/28 02:55:54:760 [info] Saving Remote Config Setting


已解决，链接用错了，以下是同一个问题的解决方式
#371
