### ISSUE TITLE
订阅的代理节点突然消失

### ISSUE THREAD

**Issue by jheroy** [yichengchen/clashX#380]
![image](https://user-images.githubusercontent.com/504766/103077903-add60100-460b-11eb-95e1-eb54554efeeb.png)

如上图代理节点看不到 并且Dashboard打开是空白，如下图：
![image](https://user-images.githubusercontent.com/504766/103077977-d5c56480-460b-11eb-9c7e-16157a074f07.png)

都是正常用着几个小时后突然变成这样， 重启系统或者待机过一段时间会自动恢复。

系统是 10.15.7 Catalina

**Comment by lelelegrand** [comment]
我跟你是一样的问题哎，clash和chrome拆了装装了拆都不能解决，重启也没有用

**Comment by zhaojinhong** [comment]
我的也出现这个问题了，系统11.0.1的，有解决的吗

**Comment by yichengchen** [comment]
log log!

**Comment by lelelegrand** [comment]
> log log!
第一次使用，不知道能不能看见哎。
![截屏2020-12-28 下午10 29 27](https://user-images.githubusercontent.com/76649762/103220874-49dd7080-495c-11eb-84a4-23506b95e50a.png)

**Comment by jheroy** [comment]
> log log!

出问题的时候Dashboard打不开 有其他方式看日志吗 比如日志目录的位置在哪儿

**Comment by yichengchen** [comment]
> > log log!
> 
> 出问题的时候Dashboard打不开 有其他方式看日志吗 比如日志目录的位置在哪儿

/Users/yicheng/Library/Logs/ClashX （ClashXPro）

**Comment by jheroy** [comment]
我看了下之前的日志有以下error：
2020/12/21 05:45:29:158  [info] start crash logger
2020/12/21 05:45:30:107  [error] The operation couldn’t be completed. Input/output error
2020/12/21 05:45:30:107  [debug] trafficWebSocket did disconnect
2020/12/21 05:45:39:980  [error] The operation couldn’t be completed. Input/output error
2020/12/21 05:45:39:980  [debug] trafficWebSocket did disconnect
2020/12/21 05:45:45:503  [error] The operation couldn’t be completed. Input/output error
2020/12/21 05:45:45:503  [debug] trafficWebSocket did disconnect
2020/12/21 05:45:47:505  [error] The operation couldn’t be completed. Input/output error
2020/12/21 05:45:47:505  [debug] trafficWebSocket did disconnect
2020/12/21 05:45:51:507  [error] The operation couldn’t be completed. Input/output error
2020/12/21 05:45:51:508  [debug] trafficWebSocket did disconnect
2020/12/21 05:45:59:509  [error] The operation couldn’t be completed. Input/output error
2020/12/21 05:45:59:511  [debug] trafficWebSocket did disconnect

**Comment by KimbingNg** [comment]
我也遇到了这个问题，请问您后来是怎么解决的呢？

**Comment by jheroy** [comment]
目前怀疑是自动更新远程配置导致的，有时会导致更新回来的文件是一串错误吗，我关闭了自动更新配置后到目前没出过问题了，clash应该检测一下，如果出错就不要把老配置覆盖了。

Kimbing Ng <notifications@github.com>于2021年1月29日 周五下午5:34写道：

**Comment by KimbingNg** [comment]
感谢！
