### ISSUE TITLE
最新版的是不是有问题啊

### ISSUE THREAD

**Issue by CNK-80Q3** [yichengchen/clashX#382]
同样的配置安装老版本的可以用，控制面板显示也正常，新版的没法用，控制面板不显示。

**Comment by JammeLee** [comment]
> 同样的配置安装老版本的可以用，控制面板显示也正常，新版的没法用，控制面板不显示。

我刚刚更新后，也遇到了这个问题。老哥解决了么？

**Comment by JammeLee** [comment]
> 同样的配置安装老版本的可以用，控制面板显示也正常，新版的没法用，控制面板不显示。

我刚刚更新也遇到这个问题了，刚找到了解决方法。[1.30.2](https://github.com/yichengchen/clashX/releases/tag/1.30.2)版本有提到。[ClashCore](https://github.com/Dreamacro/clash/wiki/breaking-changes-in-1.0.0)更新了配置文件中的关键字，你需要把老版本的yaml文件中的关键字替换成最新的就可以了。
