### ISSUE TITLE
订阅更新覆盖自行设置的规则，有什么方式解决吗，谢谢！

### ISSUE THREAD

**Issue by devlei** [yichengchen/clashX#383]

**Comment by BenjaminGao** [comment]
表述不清楚。
猜测一下：你在订阅的文件上直接修改规则，导致你每次更新订阅，修改的规则总是消失。如果真是这样，那就创建副本再改。另外这种问题跟 clash 没有什么关系。

**Comment by devlei** [comment]
> 表述不清楚。
> 猜测一下：你在订阅的文件上直接修改规则，导致你每次更新订阅，修改的规则总是消失。如果真是这样，那就创建副本再改。另外这种问题跟 clash 没有什么关系。

抱歉没表述清楚，的确是你猜测的，订阅文件直接修改规则更新会被覆盖，如果创建副本再修改，一旦订阅节点有更新，副本无法自动更新，所以想要一种类似于Shadowsocks的[用户自定义PAC规则]功能，每次订阅更新，这个规则依然生效，自行通过Google查询到Clash使用MiXin属性可合并自定义规则，但好像只有在windows平台下才行，想问下mac版本ClashX是否支持，谢谢！

Shadowsocks示例：
![image](https://user-images.githubusercontent.com/8512362/103324294-de8dbe80-4a81-11eb-8daa-0efb15c727bd.png)

**Comment by weijinsun** [comment]
同样有这个需求, 目前没有找到好的解决方式, 即能正常更新订阅 , 也能保证自定义的一些规则不失效, 除非自己写脚本,

**Comment by magicdawn** [comment]
试试 https://github.com/magicdawn/clash-config-manager

**Comment by null-id** [comment]
确实需要自定义规则的功能，自带的规则判断无法满足所有需求～

**Comment by romberli** [comment]
+1

**Comment by weijinsun** [comment]
> 试试 https://github.com/magicdawn/clash-config-manager

这种方式也挺费劲 ,目前的做法是 , 把规则 写死了, 规则的变化其实很小, 也没必要天天更新,
主要是节点变化太快,
只有机场的节点是订阅的, 使用 proxy-providers

**Comment by magicdawn** [comment]
> > 试试 https://github.com/magicdawn/clash-config-manager
> 
> 这种方式也挺费劲 ,目前的做法是 , 把规则 写死了, 规则的变化其实很小, 也没必要天天更新,
> 主要是节点变化太快,
> 只有机场的节点是订阅的, 使用 proxy-providers

还好吧, 主要还需要一个地方管理自定义规则...
如果要编辑规则如新增一个域名需要代理, 只能手动改 rules 配置文件, 这里是有 GUI 的 🤣 
写了一个上手教程 https://github.com/magicdawn/clash-config-manager#%E5%B8%A6%E8%A7%84%E5%88%99%E7%9A%84%E8%AE%A2%E9%98%85%E6%AF%8F%E6%AC%A1%E6%9B%B4%E6%96%B0%E5%AF%BC%E8%87%B4%E7%BC%96%E8%BE%91%E7%9A%84%E8%87%AA%E5%AE%9A%E4%B9%89%E8%A7%84%E5%88%99%E4%B8%A2%E5%A4%B1%E7%9A%84%E9%97%AE%E9%A2%98

> 没必要天天更新

机场有可能天天更新, 比如我用的就是建议日更...

**Comment by bronco** [comment]
相同的需求，目前最方便的还是换成Clash for Windows，希望ClashX也能提供类似功能。

**Comment by YutingYou** [comment]
很失望, 过了半年再来看还是没有新增自定义规则的feature.

订阅规则是用服务商提供的, 每家都不一样, 机场IP也经常变换, 从产品角度上看, 用户自定义规则和订阅规则分开管理更合理.

**Comment by null-id** [comment]
@bronco Mac用户用不了clash for windows……

**Comment by bronco** [comment]
> @bronco Mac用户用不了clash for windows……

可以去clash for windows的releases里看看，不要想当然哦～

**Comment by null-id** [comment]
@bronco 感谢，确实可以用，而且有自定义直连域名的功能，但是好像没有自定义强制代理的功能？

**Comment by coosir** [comment]
同样的需求。其实机场提供的订阅文件里的规则肯定覆盖不了自己的需求，所以才需要有一份自己维护的，订阅自动更新也只是想更新节点信息。

**Comment by coosir** [comment]
作者有在另一个issue里提到 Proxy Provider， #287 
provider的说明 https://lancellc.gitbook.io/clash/clash-config-file/proxy-provider
所以要达到这种效果就是只需要用默认的config.yaml，将多个机场的配置链接配置在里面（而不是使用托管配置），rules里面完全写自己的配置。可以理解为使用机场的链接只提供节点信息，这样就分离开了。

**Comment by null-id** [comment]
@coosir 小白看不懂[doge]

**Comment by YutingYou** [comment]
@coosir 感谢回复, 我先尝试一下, 如此高频的需求如果能把用法放到readme里面, 感觉会很有帮助.

**Comment by coosir** [comment]
@null-id @YutingYou 
参考我的示例吧 https://gist.github.com/coosir/1e980ba4d0cfc11ba75db57968deffdc

**Comment by zhangnew** [comment]
我是使用 [subconverter](https://github.com/tindy2013/subconverter) 作为订阅管理，同时用里面的自定义规则，这样有两个好处：
1、不会因为机场的规则变化而改变
2、多个设备共享同样的规则
缺点是每次都要上服务器改 subconverter 的规则，而且配置对小白不太友好~

**Comment by YutingYou** [comment]
@zhangnew 确实稍微繁琐些, 不适合分享给公司同事一起使用, 不过这个思路很不错

@coosir 亲测可用, 非常感谢!

**Comment by YutingYou** [comment]
FYI, 用上述方法后有个缺点是无法查看日志, 也能接受吧.

**Comment by Kaijun** [comment]
@YutingYou  @zhangnew   @coosir  @devlei 
自己写了一个 Alfred Workflow 来更新，有需要的同学自取吧...

https://github.com/Kaijun/clash-subscription-update.alfredworkflow

**Comment by devlei** [comment]
> 作者有在另一个issue里提到 Proxy Provider， #287
> provider的说明 https://lancellc.gitbook.io/clash/clash-config-file/proxy-provider
> 所以要达到这种效果就是只需要用默认的config.yaml，将多个机场的配置链接配置在里面（而不是使用托管配置），rules里面完全写自己的配置。可以理解为使用机场的链接只提供节点信息，这样就分离开了。

@coosir proxy-provider这个方法的确不错，可用，也不麻烦，感谢！

**Comment by edwards19900128** [comment]
mark, 备忘录一下

**Comment by jacinzhang** [comment]
2021.06.25 还是不支持订阅合并自定义规则！！！

**Comment by riskers** [comment]
使用 clashX Pro 的 `rule-providers` 可以解决：

```yaml
rule-providers:
  fy:
    behavior: "classical"
    type: file
    path: ./providers/rules.yaml
```

`rules.yaml` 是这样的：

```
payload:
  - DOMAIN-SUFFIX,lin.ee
  - DOMAIN-SUFFIX,line.me
  - DOMAIN-SUFFIX,line.naver.jp
  - DOMAIN-SUFFIX,line-apps.com
  - DOMAIN-SUFFIX,line-cdn.net
  - DOMAIN-SUFFIX,line-scdn.net

  - DOMAIN-KEYWORD,v2ex
  - DOMAIN-SUFFIX,medium.com

  - DOMAIN-SUFFIX,reddit.com
  - DOMAIN-SUFFIX,redditmedia.com
  - DOMAIN-SUFFIX,redd.it
  - DOMAIN-SUFFIX,redditstatic.com

  - DOMAIN-SUFFIX,quora.com
  - DOMAIN-SUFFIX,quoracdn.net

  - DOMAIN-SUFFIX,twimg.com
  - DOMAIN-SUFFIX,twitter.com

  - DOMAIN-SUFFIX,stackoverflow.com

  - DOMAIN-SUFFIX,imgur.com

  - DOMAIN-SUFFIX,xiaomi.com
  - DOMAIN-SUFFIX,spotify.com
  - DOMAIN-SUFFIX,discordapp.net
  - DOMAIN-SUFFIX,discord.com
  - DOMAIN-SUFFIX,cdn.discordapp.com
  - DOMAIN-SUFFIX,github.com

  - DOMAIN-SUFFIX,qq.com
  - DOMAIN-SUFFIX,itiger.com
  - DOMAIN-SUFFIX,notion.so

  - DOMAIN-SUFFIX,pornhub.com
  - DOMAIN-SUFFIX,91porn.com

  - DOMAIN-SUFFIX,wikipedia.org
```

这样每次订阅更新的时候，就不会影响自定义 rule 了！

**Comment by dawnray** [comment]
有没有朋友知道这个proxy-provider节点的更新方法？现在只能删除文件然后重新下载。
clash for win里面有个proxy-provider的更新功能

**Comment by junjiah** [comment]
感谢 @riskers 的方法，非常有用。附上 [clash 关于 rule provider 的文档](https://lancellc.gitbook.io/clash/clash-config-file/rule-provider)，以及我的疑问是订阅更新是否会覆盖整个 yaml 以至于仍然需要手动在 yaml config 里添加 rule provider 的定义和规则？

**Comment by DISVGOD** [comment]
> 使用 clashX Pro 的 `rule-providers` 可以解决
> 
> `config.yaml`:
> 
> ```yaml
> rule-providers:
>   fy:
>     behavior: "classical"
>     type: file
>     path: ./providers/rules.yaml
> 
> rules:
>   - RULE-SET,fy,Proxy # 这里的 fy 和上面对应
> ```
> 
> `rules.yaml` 是这样的：
> 
> ```yaml
> payload:
>   - DOMAIN-SUFFIX,lin.ee
>   - DOMAIN-SUFFIX,line.me
>   - DOMAIN-SUFFIX,line.naver.jp
>   - DOMAIN-SUFFIX,line-apps.com
>   - DOMAIN-SUFFIX,line-cdn.net
>   - DOMAIN-SUFFIX,line-scdn.net
>   - DOMAIN-KEYWORD,v2ex
>   - DOMAIN-SUFFIX,medium.com
>   - DOMAIN-SUFFIX,reddit.com
>   - DOMAIN-SUFFIX,redditmedia.com
>   - DOMAIN-SUFFIX,redd.it
>   - DOMAIN-SUFFIX,redditstatic.com
>   - DOMAIN-SUFFIX,quora.com
>   - DOMAIN-SUFFIX,quoracdn.net
>   - DOMAIN-SUFFIX,twimg.com
>   - DOMAIN-SUFFIX,twitter.com
>   - DOMAIN-SUFFIX,stackoverflow.com
>   - DOMAIN-SUFFIX,imgur.com
>   - DOMAIN-SUFFIX,spotify.com
>   - DOMAIN-SUFFIX,discordapp.net
>   - DOMAIN-SUFFIX,discord.com
>   - DOMAIN-SUFFIX,cdn.discordapp.com
>   - DOMAIN-SUFFIX,github.com
>   - DOMAIN-SUFFIX,wikipedia.org
> ```
> 
> 这样每次订阅更新的时候，就不会影响自定义 rule 了！

大佬,Windows版的应该怎么写啊

**Comment by HytonightYX** [comment]
Mark

**Comment by simsicon** [comment]
> 使用 clashX Pro 的 `rule-providers` 可以解决
> 
> `config.yaml`:
> 
> ```yaml
> rule-providers:
>   fy:
>     behavior: "classical"
>     type: file
>     path: ./providers/rules.yaml
> 
> rules:
>   - RULE-SET,fy,Proxy # 这里的 fy 和上面对应
> ```
> 
> `rules.yaml` 是这样的：
> 
> ```yaml
> payload:
>   - DOMAIN-SUFFIX,lin.ee
>   - DOMAIN-SUFFIX,line.me
>   - DOMAIN-SUFFIX,line.naver.jp
>   - DOMAIN-SUFFIX,line-apps.com
>   - DOMAIN-SUFFIX,line-cdn.net
>   - DOMAIN-SUFFIX,line-scdn.net
>   - DOMAIN-KEYWORD,v2ex
>   - DOMAIN-SUFFIX,medium.com
>   - DOMAIN-SUFFIX,reddit.com
>   - DOMAIN-SUFFIX,redditmedia.com
>   - DOMAIN-SUFFIX,redd.it
>   - DOMAIN-SUFFIX,redditstatic.com
>   - DOMAIN-SUFFIX,quora.com
>   - DOMAIN-SUFFIX,quoracdn.net
>   - DOMAIN-SUFFIX,twimg.com
>   - DOMAIN-SUFFIX,twitter.com
>   - DOMAIN-SUFFIX,stackoverflow.com
>   - DOMAIN-SUFFIX,imgur.com
>   - DOMAIN-SUFFIX,spotify.com
>   - DOMAIN-SUFFIX,discordapp.net
>   - DOMAIN-SUFFIX,discord.com
>   - DOMAIN-SUFFIX,cdn.discordapp.com
>   - DOMAIN-SUFFIX,github.com
>   - DOMAIN-SUFFIX,wikipedia.org
> ```
> 
> 这样每次订阅更新的时候，就不会影响自定义 rule 了！

我理解这些规则放在 config.yaml 里面，但是其他的订阅 config yaml 里面的规则还是会覆盖这个规则，至少我测试是这样的。请问是我漏了哪里吗？

**Comment by junjiah** [comment]
@simsicon 我的办法是覆盖后跑个脚本添加规则。当然可以想办法自动化，比如 cronjob 一天一次

```bash
➜  cat providers/changes.txt

rule-providers:
  locomoco:
    behavior: classical
    type: file
    path: ./providers/rules.yaml

➜  cat providers/changes.txt >> your.yaml && awk -i inplace '/MATCH,DIRECT/{print "  - \x27RULE-SET,locomoco,Proxy\x27"}1' your.yaml
```

**Comment by simsicon** [comment]
@junjiah 谢谢你的回复，这方法挺好，但如果要在多端上配置，就会比较麻烦，所以最好是从源头解决问题。我现在的方案是通过 subconvert 的上传自定义规则，在基础规则上维护自己的规则

**Comment by mafeifan** [comment]
mark 一下

**Comment by xiao-baii** [comment]
> 有没有朋友知道这个proxy-provider节点的更新方法？现在只能删除文件然后重新下载。
> clash for win里面有个proxy-provider的更新功能

我也想知道这个怎么更新，我使用了proxy-provider和rule-provider用了interval设置为86400（24小时）但是过了两天还是没有更新

**Comment by Xelawk** [comment]
我是写了个python脚本，每次更新完订阅就merge一下，或者用corntab等类似的定时任务让它自行更新

**Comment by Xelawk** [comment]
我的办法是写个python把目标relus字段添加上自己的规则就行了

**Comment by iTofu** [comment]
mark
