### ISSUE TITLE
使用 iCloud 存放配置文件

### ISSUE THREAD

**Issue by lfzyx** [yichengchen/clashX#384]
当我使用 iCloud 存放配置文件，yaml文件都正确的放在了 iCloud/ClashX 目录中，但 Country.mmdb 还是在原来的 ~/.config/clash 目录，这样mac 上就存在了两个 config 文件夹， 强迫症表示有点受不了😂😂

**Comment by yichengchen** [comment]
~/.config/clash 这个文件夹还有一些基础配置的东西再里面，不好移到icloud。。。
