### ISSUE TITLE
混合代理端口每次启动都会随机一个数，配置文件无法指定端口。

### ISSUE THREAD

**Issue by Castleeee** [yichengchen/clashX#387]
如题，每次端口还会随机增加，有时候生效。
而且http和socks端口无法设置，配置文件设置无效。
![图片](https://user-images.githubusercontent.com/33923279/103432330-234b5e00-4c18-11eb-938f-3d9409dd5bbb.png)

**Comment by Ninzero** [comment]
[看这里](https://github.com/yichengchen/clashX#change-the-ports-of-clashx)

**Comment by Castleeee** [comment]
这就是那个config.yaml,生成默认7908，改成10808之后重启会变成一个随机数

**Comment by llkhs** [comment]
Socks5 代理端口没作用了吗，还是跟 http 混合了？！

**Comment by yuhengshen** [comment]
猜测是端口占用，然后随机选取一个使用了。
我重启下就可以了。

**Comment by yichengchen** [comment]
需要修改config.yaml中的mixed port。随机数是因为端口被占用
