### ISSUE TITLE
退出后无法联网

### ISSUE THREAD

**Issue by tuohecaf** [yichengchen/clashX#388]
系统是Mac Bigsur 11,之前有一次退出了软件，后面就再也连不上了。

**Comment by shaonianruntu** [comment]
同这样的问题，即使退出clashX或者卸载后，然后不能联网：
表现在app可以联网（QQ、微信等），但浏览器不行。

**Comment by Binglin** [comment]
**电脑现在没法上网了**

clashx打开 然后并没有设置系统代理，电脑自动重启了 然后就再没连上过网
日志里只有这两项
`
[warning] dial Domestic error: All DNS requests failed
[warning] dial V2-Y error: xx.xx.xx:xxx connect error
`

**Comment by yichengchen** [comment]
try with new version. If has any issue, recreate the issue
