### ISSUE TITLE
[日志] ClashX Pro 的日志显示有问题

### ISSUE THREAD

**Issue by Loyalsoldier** [yichengchen/clashX#389]
Version 1.31.2.1 (1.31.2.1)

ClashX Pro 的日志有新增内容时，日志会自动跳到最上面（最旧）的条目。点击日志的「现在」按钮，也会自动跳到最上面（最旧）的条目，而不是最下面。

期待的结果：日志显示的画面保持在最下面（最新）。

![image](https://user-images.githubusercontent.com/10487845/103477927-40418600-4dfe-11eb-8f03-37276c7d8110.png)

**Comment by jasonxytan** [comment]
这个也困扰我好久。感觉是因为Mac的Console设计逻辑是最新的在最上面？

**Comment by dev4u** [comment]
tail -f

**Comment by yichengchen** [comment]
这个是macos 11 日志查看器的bug。。💊
