### ISSUE TITLE
添加服务器会覆盖之前的服务器

### ISSUE THREAD

**Issue by 5cr1pt** [yichengchen/clashX#39]
从这里添加服务器的话，会覆盖之前config.ini文件中已有的服务器
![image](https://user-images.githubusercontent.com/3685107/47193558-2f73d980-d386-11e8-8abe-74786bba54d6.jpeg)
而且这里每次都是新建服务器，即使已经有服务器在用。

**Comment by yichengchen** [comment]
This config generator would be deprecated in the next version. new designed dashboard would replace it.
