### ISSUE TITLE
[Feature Request] 希望可以自定义 GeoIP 数据库下载地址

### ISSUE THREAD

**Issue by Loyalsoldier** [yichengchen/clashX#390]
原因：MaxMind 的 GeoLite2 数据在中国大陆下不是特别准，有网友做了更好的 mmdb 数据库

https://github.com/alecthw/mmdb_china_ip_list

**Comment by dev4u** [comment]
已支持

**Comment by Loyalsoldier** [comment]
感谢提醒！
