### ISSUE TITLE
[Feature Request] 希望增加一个「手动代理」模式

### ISSUE THREAD

**Issue by Loyalsoldier** [yichengchen/clashX#391]
「手动代理」模式，类似于「设置为系统代理」模式：同样需要启动 Clash。但是「手动代理」模式，不自动配置 macOS 的网络代理。

目前存在的问题：「设置为系统代理」模式下，只要手动修改了 macOS 的网络代理，此时 ClashX Pro 就不可用了。

**Comment by yichengchen** [comment]
不打钩设置系统代理就好了？

**Comment by Loyalsoldier** [comment]
有道理 😂
