### ISSUE TITLE
总是弹出这个，版本big sur11.1

### ISSUE THREAD

**Issue by ZZtac** [yichengchen/clashX#394]
ClashX 需要使用管理员权限安装/更新一个帮助程序来帮助设置系统代理。如不安装,ClashX的设置系统代理功能将失效。

**Comment by studenthug** [comment]
你好，【ClashX 需要使用管理员权限安装/更新一个帮助程序来帮助设置系统代理。如不安装,ClashX的设置系统代理功能将失效。】这个问题解决了嘛？
