### ISSUE TITLE
大佬、请求，mac运行过java web项目之后无法使用

### ISSUE THREAD

**Issue by shadow-boy** [yichengchen/clashX#395]
mac 跑过springboot项目之后，启动clashx pro 显示“系统代理设置已被另一进程修改，clashx不再是系统默认代理”，咋办
![image](https://user-images.githubusercontent.com/15226194/103649907-32286c80-4f9a-11eb-89df-14c28264f052.png)

**Comment by yichengchen** [comment]
是不是挂了vpn 看看log

**Comment by ZZLinvec** [comment]
别用MAC啦
