### ISSUE TITLE
[Feature Request]希望增加TUN代理模式

### ISSUE THREAD

**Issue by NobodyHere-rrr** [yichengchen/clashX#397]
希望增加TUN代理模式以用于游戏代理！
个人觉得可以用go-TUN2socks实现。
https://github.com/eycorsican/go-tun2socks
PS:clash for windows的windows版好像实现了TAP代理的样子，希望Clash也能尽快实现！

**Comment by Loyalsoldier** [comment]
ClashX 没有 TUN 模式（增强模式）
ClashX Pro 才有 TUN 模式，下载地址：https://install.appcenter.ms/users/clashx/apps/clashx-pro/distribution_groups/public

**Comment by NobodyHere-rrr** [comment]
@Loyalsoldier 谢谢，问题解决了
