### ISSUE TITLE
图标异常

### ISSUE THREAD

**Issue by MF-x** [yichengchen/clashX#40]
在双屏幕的时候，正常情况其中一个屏幕会出现图标变暗，但clashX不会。具体见图。
<img width="171" alt="wechatimg79" src="https://user-images.githubusercontent.com/29669208/47250247-f94f5c00-d450-11e8-9701-d3a4f535b564.png">
![wechatimg80](https://user-images.githubusercontent.com/29669208/47250250-fc4a4c80-d450-11e8-94e5-f1d15f78ea07.png)

**Comment by tzhao11** [comment]
Itsycal 的解决方法，似乎用了一些黑魔法

https://github.com/sfsam/Itsycal/blob/6cbeaf4aa5f2903e3fd490a2ca07de2bc4ae1704/Itsycal/ViewController.m#L426

https://github.com/sfsam/Itsycal/blob/6cbeaf4aa5f2903e3fd490a2ca07de2bc4ae1704/Itsycal/ViewController.m#L443

**Comment by tzhao11** [comment]
一种更好的办法：
```swift
self.statusItem.image = NSImage(data: self.statusItemView.dataWithPDF(inside: self.statusItemView.bounds))
self.statusItem.image?.isTemplate = true
```
