### ISSUE TITLE
 proxy setting changed by other process clashx

### ISSUE THREAD

**Issue by Joetiny** [yichengchen/clashX#401]
proxy setting changed by other process clashx
2021/01/07 02:49:51:964  [warning] Proxy changed by other process!, current:["SOCKSEnable": 0, "HTTPSEnable": 1, "HTTPSPort": 7890, "HTTPPort": 7890, "HTTPProxy": 127.0.0.1, "HTTPSProxy": 
2021/01/07 04:35:37:845  [warning] Proxy changed by other process!, current:["HTTPPort": 7890, "HTTPProxy": 127.0.0.1, "HTTPSPort": 7890, "HTTPSProxy": 127.0.0.1, "__SCOPED__":

**Comment by garinyong** [comment]
the same problem!
