### ISSUE TITLE
TUN 模式下docker容器访问https无法连接

### ISSUE THREAD

**Issue by invictus555** [yichengchen/clashX#404]
在docker容器中curl https://www.google.com返回错误（gnutls_handshake() failed: The TLS connection was non-properly terminated.），clashX的日志是[info] [TCP] 127.0.0.1:51785 --> 198.18.0.29 match Match() using Auto[Bandwagon-CA]。 docker容器采用了--network=host设置。有个奇怪的现象，在宿主主机https的透明代理没问题([info] [TCP] 198.18.0.1:51848 --> www.google.com match RuleSet(Global) using Auto[GoogleCloud-HK])。请问如何解决？
config附上：
port: 7890
socks-port: 7891
allow-lan: false
bind-address: "*"
mode: rule
log-level: info
ipv6: true
external-controller: 127.0.0.1:9090
bypass:
  ...
  - 'music.163.com'
  - '*.music.126.net'
  - '*.kuwo.cn'
  - '*.iqiyi.com'
  - '*.microsoft.com'
dns:
  enable: true
  listen: 0.0.0.0:53
  enhanced-mode: fake-ip
  fake-ip-range: 198.18.0.1/16
  fake-ip-filter:
    - '*.lan'
    - localhost.ptlogin2.qq.com
  nameserver:
    - 114.114.114.114
  fallback-filter:
    geoip: true
    ipcidr: null
tun:
  enable: true
  stack: system # or gvisor
  macOS-auto-route: true
  macOS-auto-detect-interface: true
  dns-hijack:
    - tcp://114.114.114.114:53
experimental:
  interface-name: en0 # your interface-name, only for TUN mode

**Comment by yichengchen** [comment]
docker mac没有--network=host这一用法吧

**Comment by BenjaminGao** [comment]
docker 有 `--network host` 这种用法，不过没有 `--network=host` 这种用法。

**Comment by invictus555** [comment]
感谢大佬关注此问题，不过此错误跟有无--network选项无关

**Comment by BenjaminGao** [comment]
> 感谢大佬关注此问题，不过此错误跟有无--network选项无关

我不是很懂 Docker，我运行了一下我的 Docker，在 Docker 的一个容器里开一个终端，在其中运行 `curl -I www.google.com`，Clash 正常设置为增强模式，运行结果如下：
<img width="1440" alt="截屏2021-02-23 下午8 57 03" src="https://user-images.githubusercontent.com/16028320/108846698-d5504680-7619-11eb-91b7-736bbb975a6f.png">
很明显一切都很正常。运行 `curl` 时自动判断规矩规则判断。

**Comment by invictus555** [comment]
curl www.google.com 是没问题的。如果curl https://www.google.com呢？

**Comment by BenjaminGao** [comment]
> curl [www.google.com](http://www.google.com) 是没问题的。如果curl [https://www.google.com呢？](https://www.google.com%E5%91%A2%EF%BC%9F)

也是正常的。
<img width="1440" alt="截屏2021-02-23 下午9 09 26" src="https://user-images.githubusercontent.com/16028320/108848071-7e4b7100-761b-11eb-9e9f-21a351af7d07.png">

**Comment by invictus555** [comment]
那就是我的配置有问题。能分享一下你的配置文件(请抹掉与账号相关的信息)，邮箱：sean.sheng@live.com

**Comment by BenjaminGao** [comment]
> 那就是我的配置有问题。能分享一下你的配置文件(请抹掉与账号相关的信息)，邮箱：[sean.sheng@live.com](mailto:sean.sheng@live.com)

自己找一下吧。这个仓库的 ISSUS 里有。
