### ISSUE TITLE
增强模式局域网无法访问

### ISSUE THREAD

**Issue by daihy8759** [yichengchen/clashX#405]
![image](https://user-images.githubusercontent.com/6057326/103966977-eba26000-519b-11eb-8262-32b9d83ec115.png)

**Comment by BenjaminGao** [comment]
可以访问
![Uploading 截屏2021-01-11 下午1.00.47.png…]()

**Comment by BenjaminGao** [comment]
Version：Pro 1.31.3.2
可以访问。
<img width="1151" alt="截屏2021-01-11 下午1 00 47" src="https://user-images.githubusercontent.com/16028320/104148547-9ff6ed00-540d-11eb-8920-a6e0687e6892.png">

**Comment by daihy8759** [comment]
1.31.2.1不行，升级到1.31.3.2可以了
