### ISSUE TITLE
mac 版总提示「Network Proxy Authentication」

### ISSUE THREAD

**Issue by JasinYip** [yichengchen/clashX#408]
![image](https://user-images.githubusercontent.com/7105264/104291580-a9a84f80-54f6-11eb-8cac-3f8d003ce74a.png)
如图，请问是什么原因？关掉后过一段时间又会出来，每次都弹两次，关闭 ClashX 就不会弹。

ClashX 版本是 1.31.2，macOS 系统 11.1 (20C69)

**Comment by BenjaminGao** [comment]
题主确定是 ClashX 的问题么？是不是别的应用，有代理的需求，弹出来的。

**Comment by JasinYip** [comment]
我把「Set as system proxy」取消掉，就肯定不会弹。

要说另一个软件要开代理的话，那就是阿里郎在它代理的时候也在申请代理了？

**Comment by BenjaminGao** [comment]
> 我把「Set as system proxy」取消掉，就肯定不会弹。
> 
> 要说另一个软件要开代理的话，那就是阿里郎在它代理的时候也在申请代理了？

取消系统代理当然就没有代理的作用的了。这样即便是其他软件需要代理也不会弹窗。只能每次打开一个软件，然后看 ClashX 日志，确定是哪个软件需要使用代理。

**Comment by yichengchen** [comment]
这个是系统弹的。一般是由于网络不通什么的。好像是赛门铁克的弹窗
