### ISSUE TITLE
clashx 订阅链接地址在哪呀

### ISSUE THREAD

**Issue by jathena233** [yichengchen/clashX#409]
你好，我下载了clashx，然后要在配置管理里添加url链接，请问这个链接从哪里找啊？新手小白so sorry

**Comment by fyenne** [comment]
右键, config -> remote config -> manage -> add

**Comment by koenzhao** [comment]
这是一个协议流量转发的工具，不是一个机场服务的提供方。
打个比方，你买了一个TP-Link的路由器，在家里安装好，配置路由器设置的时候，需要填入宽带网络账号。这个时候你应该向你的宽带网络提供商（中国电信/中国移动/中国联通）索取这个网络账号，而不是向路由器厂商TP-Link索取。
你问题中描述的场景就有点类似于上述比方中向路由器厂商索取宽带网络账号。

**Comment by zhixuans** [comment]
配置-托管配置-管理
