### ISSUE TITLE
打开 Enhanced Mode 后修改 DNS Server 行为的咨询

### ISSUE THREAD

**Issue by twiceyuan** [yichengchen/clashX#410]
公司因为需要使用 DHCP 下发的 DNS Server 才能访问某些内网服务，发现 ClashX Pro 开启 Enhanced Mode 后会覆盖设置一个 198.18.0.2 的 DNS Server 导致内网服务不可用。

尝试删除这条 DNS Server 配置后，Enhanced Mode 似乎也是正常的（非浏览器 App、终端等可以正常使用代理），那么这个配置的作用是什么，是否可以通过设置关掉

**Comment by dev4u** [comment]
配置文件里指定dns地址

**Comment by BenjaminGao** [comment]
DNS 配置 http://blog.joylau.cn/2020/05/01/Clash-Config/

只要你开启增强模式，Clash 是一定会覆盖系统的，只有修改 Clash 配置文件。
