### ISSUE TITLE
clash mac重启无法正常启动，要在进程里面结束掉之后，才能重新启动，请问怎么解决。

### ISSUE THREAD

**Issue by summerwakeme** [yichengchen/clashX#411]
clash mac重启无法正常启动，要在进程里面结束掉之后，才能重新启动，请问怎么解决。

**Comment by hansenz42** [comment]
我也有同样情况，重启之后后一定几率clashx进程会假死，任务栏上不显示图标。要在activity monitor里面结束进程重启后才能正常使用。big sur，intel处理器环境。试过重新安装也没用

**Comment by VIEWSTAY** [comment]
我也有同样的情况，BigSur intel

**Comment by dev4u** [comment]
等适配

**Comment by sheeptako** [comment]
+10086，要kill 掉进程才能打开

**Comment by telanflow** [comment]
me too

**Comment by kratos9394** [comment]
还以为我电脑问题,只能去用windows的mac版

**Comment by summerwakeme** [comment]
那就只能等作者适配了。

**Comment by xieqing0428** [comment]
+1

**Comment by Tyro-Fang** [comment]
macos 10.13.6,出现此bug

**Comment by liukaiwen0422** [comment]
Macbook pro2020
version10.15.7
CPU：英特尔
睡眠之后打开电脑也会出现该问题.

**Comment by HKZ773999** [comment]
今天升级到了 11.2 还是有这个问题。

**Comment by XuanBoWu** [comment]
clashx version：1.3.2
macOS 11.1
intel版本
同样有此问题
