### ISSUE TITLE
请求帮助，电脑无法上网了

### ISSUE THREAD

**Issue by Binglin** [yichengchen/clashX#412]
之前版本是ClashX 1.19，有次电脑重启 ClashX没启动 电脑就无法上网了，后来点开ClashX就可以上网了 就没管
昨天电脑又自己重启了，这次电脑没法上网了，试了下更新了ClashX 1.31 但是也没用
![WechatIMG11](https://user-images.githubusercontent.com/4366588/104688960-abfbeb00-573c-11eb-838d-de56c1f86218.jpeg)
![WechatIMG12](https://user-images.githubusercontent.com/4366588/104688968-b0c09f00-573c-11eb-98f2-dc441d88800a.jpeg)

**Comment by mumubin** [comment]
我也有同样的问题

软件及系统:

- ClashX Pro 1.31.3.2 
- Mac Big Sur

现象：
- 关闭ClashX后完全无法上网。
- 打开ClashX后，部分网站可访问，百度等无法访问。

且偶尔Clashx会crash

**Comment by dev4u** [comment]
看看系统的代理配置

**Comment by mumubin** [comment]
> 看看系统的代理配置
看了下 clashx退出后 系统代理之前勾选的都为空了，但是依然在退出状态下无法上网

**Comment by wkoa** [comment]
请问这个问题解决了吗？

**Comment by zhanleshun** [comment]
试一下勾选这些，我的也不能上百度，勾选了就好了

![image](https://user-images.githubusercontent.com/13835085/113503156-9be8f000-9562-11eb-9934-801622b27fc4.png)
