### ISSUE TITLE
GEOIP,cn,DIRECT 不生效macos 11.1

### ISSUE THREAD

**Issue by skill7899** [yichengchen/clashX#413]
clash x pro 1.31.3.2 
 - GEOIP,cn,DIRECT
  - MATCH,Proxy-1
 开启了系统代理和增强代理
访问百度走了是最后一个规则
2021/01/16 01:03:31.365  [debug] [DNS] www.baidu.com --> 14.215.177.38
2021/01/16 01:03:31.373  [debug] [DNS] passport.baidu.com --> 180.97.36.39
2021/01/16 01:03:32.292  [info] [TCP] 127.0.0.1:64185 --> passport.baidu.com match Match() using Proxy-1
2021/01/16 01:03:32.355  [debug] [DNS] sp2.baidu.com --> 14.215.177.39
2021/01/16 01:03:32.729  [info] [TCP] 127.0.0.1:64198 --> sp2.baidu.com match Match() using Proxy-1

**Comment by dev4u** [comment]
关闭系统代理，只开增强试试。

**Comment by skill7899** [comment]
> 关闭系统代理，只开增强试试。

一样不生效
2021/01/16 04:53:14.702  [debug] [DNS] www.baidu.com --> 14.215.177.39
2021/01/16 04:53:14.713  [debug] [DNS] passport.baidu.com --> 180.97.36.39
2021/01/16 04:53:15.060  [info] [TCP] 198.18.0.1:56976 --> www.baidu.com match Match() using Proxy-1

**Comment by skill7899** [comment]
找到原因。。。大小写的问题 GEOIP,cn,DIRECT。改成 GEOIP,CN,DIRECT
