### ISSUE TITLE
1.31.3没有增强模式

### ISSUE THREAD

**Issue by mizuharakiko** [yichengchen/clashX#414]
系统: macos 11.1,  m1

clashx pro: version 1.31.3, b6ee47, 3435ffd-HEAD

只有系统代理功能，无增强模式功能

**Comment by mizuharakiko** [comment]
#364 

试过这个 issue 中的方法，还是不行

**Comment by yichengchen** [comment]
download clashx pro at https://install.appcenter.ms/users/clashx/apps/clashx-pro/distribution_groups/public
