### ISSUE TITLE
ClashX 支持用 Shell 命令控制吗？

### ISSUE THREAD

**Issue by xieliying** [yichengchen/clashX#415]
自动化脚本打包上传软件时，有时会用到代理去跑一些功能。

想问下 ClashX 是否支持使用 Shell 命令去切换模式？比如有些功能要开全局，有些功能要取消代理等，这时如果能用 Shell 命令控制的话，就不用人手去切换 ClashX 的工作模式。

**Comment by SailerNote** [comment]
- 配置DNS
- 配置文件中修改目标地址的代理配置
- export 环境变量http_proxy https_proxy all_proxy 

可以试试

**Comment by yichengchen** [comment]
可以使用clash的http api进行控制
