### ISSUE TITLE
能隐藏菜单栏的图标吗？

### ISSUE THREAD

**Issue by fengsx1995** [yichengchen/clashX#421]
能提供个开关不在菜单栏里显示吗？

**Comment by summer19940609** [comment]
![](https://cdn.jsdelivr.net/gh/summer19940609/picture-repo/blog/20210121183249.png)

这个软件好用，免费的，隐藏菜单栏

![](https://cdn.jsdelivr.net/gh/summer19940609/picture-repo/blog/20210121183335.png)

**Comment by fengsx1995** [comment]
谢谢帮助，我其实只想隐藏clashX的Menu icon，感觉为了这个多装个软件，显得更麻烦：兼容性上更多问题。

**Comment by SailerNote** [comment]
按住command，拖拽icon到桌面。就可以隐藏了。

reference
https://www.ifanr.com/app/1046703

**Comment by SailerNote** [comment]
> 谢谢帮助，我其实只想隐藏clashX的Menu icon，感觉为了这个多装个软件，显得更麻烦：兼容性上更多问题。
> 试用了一下还是挺方便的。

按住command，拖拽icon到桌面。就可以隐藏了。

reference
https://www.ifanr.com/app/1046703

**Comment by yichengchen** [comment]
没有，因为clashx 已经没用dock图标了，状态栏图标是唯一入口
