### ISSUE TITLE
为什么我打开ClashX后看不到任何节点？

### ISSUE THREAD

**Issue by leogentleman** [yichengchen/clashX#424]
导入配置文件后，显示不了任何节点，无法选择代理，如下所示，有谁知道为为啥吗？
![image](https://user-images.githubusercontent.com/13391858/105577184-ec99db00-5db2-11eb-8cb9-497a9f54cb50.png)

**Comment by SailerNote** [comment]
1. 配置->打开本地配置文件夹 检查配置文件
2. ClashX是客户端，需要配置文件或订阅VPS服务或配置VPS

**Comment by leogentleman** [comment]
为什么你们的网站143143.site进不去了？vps都失效了？。。


Yansy <notifications@github.com> 于2021年2月4日周四 上午11:54写道：

**Comment by zhixuans** [comment]
导入配置文件没有节点，那应该是配置文件有问题了，另外那个网站可能是你服务商的网站，跟软件没有关系。
