### ISSUE TITLE
Should clear previous benchmark results when launch new speed testing

### ISSUE THREAD

**Issue by pengzhenghao** [yichengchen/clashX#426]
Hi @yichengchen , thanks for this great project!

Sometimes the machine is connected smoothly in previous test, but later it fails. In this case, the FINAL benchmark results will shows "failed" but when testing the user would only see the previous benchmark result which is good. This cause confusion.

So I suggest to remove previous benchmarks result when launching new test.

Thanks!

**Comment by yichengchen** [comment]
This is limited in by the api of clash core https://github.com/Dreamacro/clash .Maybe you can raise a issue on it
