### ISSUE TITLE
Clash X分流失效

### ISSUE THREAD

**Issue by Profitter** [yichengchen/clashX#427]
rt，clashx分流失效，istat的网速指示器上显示为国内IP，且无法访问fq，开全局模式可以fq，dashboard里无日志输出

**Comment by app111** [comment]
+1, mac 11.2 (20D62)

**Comment by 97Yates05** [comment]
+1，开代理网页可以正常fq，但是终端、npm都不行（已配置代理）

**Comment by 97Yates05** [comment]
> +1，开代理网页可以正常fq，但是终端、npm都不行（已配置代理）

我的已解决，策略选择问题，规则外路由配置需要选择代理
