### ISSUE TITLE
最新版本的ClashX支持SSR订阅吗

### ISSUE THREAD

**Issue by RoyRao2333** [yichengchen/clashX#428]
简介里提到了支持Shadowsocks，但没有ShadowsocksR。我特意去搜了ClashXR，但那个项目说原生Clash的内核已经支持SSR了，所以停止维护。那最新版本的ClashX支持SSR订阅吗？我在配置管理里添加SSR订阅链接会提示添加失败，所以如果支持SSR订阅的话，该如何添加呢？谢谢！

**Comment by RoyRao2333** [comment]
> 简介里提到了支持Shadowsocks，但没有ShadowsocksR。我特意去搜了ClashXR，但那个项目说原生Clash的内核已经支持SSR了，所以停止维护。那最新版本的ClashX支持SSR订阅吗？

我在配置管理里添加SSR的订阅链接会提示失败，所以如果支持SSR的话，应该怎么添加呢，谢谢！

**Comment by BenjaminGao** [comment]
支持。

**Comment by yichengchen** [comment]
只支持含有ssr配置的**clash订阅**

**Comment by seagle0128** [comment]
请问怎么设置才能支持ssr？我和 @RoyRao2333 一样，无法订阅ssr配置
