### ISSUE TITLE
希望添加一个友好的增加规则的界面

### ISSUE THREAD

**Issue by Mankvis** [yichengchen/clashX#432]
如题，目前mac版本好像没有规则界面可以灵活添加规则，必须要修改配置文件
因为在也使用过windows的版本，感觉有这个的话就不用每次打开配置文件了

**Comment by yichengchen** [comment]
暂时没有精力做这个。windows版本的规则编辑也基本不维护了。。

**Comment by Antsypc** [comment]
刚需。好像修改配置文件后，自动更新远程规则后，会覆盖掉自定义配置的规则。

**Comment by bastengao** [comment]
我**每天**都需要在自动配置被更新覆盖后，手动把自己的规则再追加到配置文件里。

**Comment by ehznahz** [comment]
我自己写了一个脚本来接替clashx的订阅更新功能 同时完成自定义规则和服务商规则的合并

**Comment by supermanxiacheng** [comment]
请教一下，规则修改有什么参考的教程吗？

**Comment by Kaijun** [comment]
> 暂时没有精力做这个。windows版本的规则编辑也基本不维护了。。

可以考虑类似 clash for windows 的自定义 mixin 的操作吗？可以自己写 yaml/javascript 来追加 rules

**Comment by Kaijun** [comment]
自己写了一个 Alfred Workflow 来更新，有需要的同学自取吧...

https://github.com/Kaijun/clash-subscription-update.alfredworkflow

# clash-subscription-update.alfredworkflow

> 通过 Alfred 更新 Subscription，并且支持自定义规则追加

## 配置

#### 1. 双击，填写自定义的订阅地址

![Screen Shot 2021-03-20 at 6 43 31 PM](https://user-images.githubusercontent.com/1693027/111867326-2bf93800-89ae-11eb-9bd3-a073b99db003.png)

![Screen Shot 2021-03-20 at 6 44 26 PM](https://user-images.githubusercontent.com/1693027/111867408-a629bc80-89ae-11eb-8f20-f27d1d798fa1.png)

注意：Arg 内，填写 `配置文件名 | 订阅URL` 其中分隔符` | `不要删除，必须保留

#### 2. 填写追加配置

![Screen Shot 2021-03-20 at 6 47 47 PM](https://user-images.githubusercontent.com/1693027/111867435-dbcea580-89ae-11eb-971b-64419b7e2a82.png)
![Screen Shot 2021-03-20 at 6 49 22 PM](https://user-images.githubusercontent.com/1693027/111867436-de30ff80-89ae-11eb-99c1-59220fd78ff7.png)

注意：
- 配置会默认追加到 rules 最前面。
- 如果配置路径有改动则修改 CLASH_CONFIG_PATH 
- 默认拉取超时 15秒，如果需要修改更长或者更短，则修改 `curl -m 15` 的值

## 使用截图
![WX20210320-190705](https://user-images.githubusercontent.com/1693027/111867567-d58cf900-89af-11eb-8d6c-9d46f71c38e1.png)
![WX20210320-190741](https://user-images.githubusercontent.com/1693027/111867569-d756bc80-89af-11eb-9e50-396687eacff5.png)
![WX20210320-190919](https://user-images.githubusercontent.com/1693027/111867571-d9b91680-89af-11eb-952c-eb6d76d5cd15.png)

**Comment by EzioZz** [comment]
可以考虑转用clash for windows（目前没有开源）
https://github.com/Fndroid/clash_for_windows_pkg

**Comment by JPAdCoder** [comment]
> 可以考虑转用clash for windows（目前没有开源）
> https://github.com/Fndroid/clash_for_windows_pkg

换平台的代价可太大了

**Comment by EzioZz** [comment]
> > 可以考虑转用clash for windows（目前没有开源）
> > https://github.com/Fndroid/clash_for_windows_pkg
> 
> 换平台的代价可太大了

两个差不多。都是基于clash的

**Comment by yichengchen** [comment]
> > 可以考虑转用clash for windows（目前没有开源）
> 
> > https://github.com/Fndroid/clash_for_windows_pkg
> 
> 
> 
> 换平台的代价可太大了

clash for windows 支持mac🤣

**Comment by EzioZz** [comment]
> > > 可以考虑转用clash for windows（目前没有开源）
> > 
> > 
> > > https://github.com/Fndroid/clash_for_windows_pkg
> > 
> > 
> > 换平台的代价可太大了
> 
> clash for windows 支持mac🤣

名字确实是这个。。不过支持mac。

**Comment by zhan9san** [comment]
我是把ClashX的代理模式设置为全局，然后在浏览器通过[SwitchyOmega](https://github.com/FelisCatus/SwitchyOmega)来自定义规则的
对于非浏览器的访问，按需在命令行增加代理的环境变量启动，也就可以通过代理访问了

**Comment by cntrump** [comment]
https://github.com/cntrump/clashconfigutil 使用这个来替代 APP 的线路更新，就是需要自己手动运行。
