### ISSUE TITLE
macOS Big Sur 11.3 Beta 下增强模式 Auto Interface Detection=Core 无法联网

### ISSUE THREAD

**Issue by wydinhk** [yichengchen/clashX#438]
需要调到 ClashXIFace 才可以。

[com.west2online.ClashXPro 2021-02-03--01-48-03-850.log](https://github.com/yichengchen/clashX/files/5915611/com.west2online.ClashXPro.2021-02-03--01-48-03-850.log)

**Comment by willin** [comment]
mark

**Comment by yichengchen** [comment]
可能还是得把ClashXIFace作为default mode比较靠谱。。
