### ISSUE TITLE
控制台代理页显示空白，页面元素中有 <noscript> 标签

### ISSUE THREAD

**Issue by winoros** [yichengchen/clashX#439]
试了多个版本都是这样，请问这时候应该怎么解决？
![PNG图像](https://user-images.githubusercontent.com/7846227/106734431-fa225100-664d-11eb-842e-f56f213e0a74.png)

**Comment by aaapei** [comment]
同问，但日志文件是空的
系统升级big sur后出现的问题

**Comment by winoros** [comment]
> 同问，但日志文件是空的
> 系统升级big sur后出现的问题

我没升级前就是，升级了发现还是一样。。

**Comment by xfirefly** [comment]
同样的问题

**Comment by zengande** [comment]
+1

**Comment by 2048li** [comment]
我mac配置的时候遇到同样的问题，现在已经解决！！！
不要直接用clash订阅链接，将ssr订阅链接转换为clash链接，添加到配置，更新后就全都有啦！！！

**Comment by xfirefly** [comment]
> 我mac配置的时候遇到同样的问题，现在已经解决！！！
> 不要直接用clash订阅链接，将ssr订阅链接转换为clash链接，添加到配置，更新后就全都有啦！！！

请问 将ssr订阅链接转换为clash链接 这个具体是怎样操作的..没看明白

**Comment by 2048li** [comment]
https://bianyuan.xyz/
我用的上面这个网站转换的，直接贴ssr订阅链接就行。【不确定是否安全/是否存在被dao哈～】

**Comment by xfirefly** [comment]
> https://bianyuan.xyz/
> 我用的上面这个网站转换的，直接贴ssr订阅链接就行。【不确定是否安全/是否存在被dao哈～】
> 
> > > 我mac配置的时候遇到同样的问题，现在已经解决！！！
> > > 不要直接用clash订阅链接，将ssr订阅链接转换为clash链接，添加到配置，更新后就全都有啦！！！
> > 
> > 
> > 请问 将ssr订阅链接转换为clash链接 这个具体是怎样操作的..没看明白

已解决, 多谢

**Comment by bang919** [comment]
我这边是打开.yaml，然后log-level: silent改成log-level: info
