### ISSUE TITLE
Clash 自动崩溃

### ISSUE THREAD

**Issue by BenjaminGao** [yichengchen/clashX#442]
**系统版本：** 11.1(M1)
**软件版本：** Clash Pro 1.31.3.2
**问题描述：**
一下午看B站直播时,发现软件两次自动崩溃。看着看着就无法联网了。现提供三份日志，两份在 **控制台** 里找到的，一份是 Clash 的日志。（按说 Clash 应该还有一份日志，可是在 Log 文件夹里的三份日志文件中没有发现，被覆盖了，不知有没有调整日志容量的配置参数）
[（下午崩溃时）Clash自带的报错日志.log](https://github.com/yichengchen/clashX/files/5942008/default.log)
[（控制台）中午崩溃日志.log](https://github.com/yichengchen/clashX/files/5942009/default.log)
[（控制台）下午崩溃日志.log](https://github.com/yichengchen/clashX/files/5942011/default.log)

**Comment by yichengchen** [comment]
```
0   libsystem_kernel.dylib        	0x000000019d0e7cec __pthread_kill + 8
1   libsystem_pthread.dylib       	0x000000019d118c24 pthread_kill + 292
2   libsystem_c.dylib             	0x000000019cff84d0 raise + 32
3   com.west2online.ClashXPro     	0x0000000103188f04 runtime.raise_trampoline (in ClashX Pro) (sys_darwin_arm64.s:432)
4   com.west2online.ClashXPro     	0x0000000103187cd8 runtime.asmcgocall (in ClashX Pro) (asm_arm64.s:956)
```

crash inside golang

**Comment by BenjaminGao** [comment]
> ```
> 0   libsystem_kernel.dylib        	0x000000019d0e7cec __pthread_kill + 8
> 1   libsystem_pthread.dylib       	0x000000019d118c24 pthread_kill + 292
> 2   libsystem_c.dylib             	0x000000019cff84d0 raise + 32
> 3   com.west2online.ClashXPro     	0x0000000103188f04 runtime.raise_trampoline (in ClashX Pro) (sys_darwin_arm64.s:432)
> 4   com.west2online.ClashXPro     	0x0000000103187cd8 runtime.asmcgocall (in ClashX Pro) (asm_arm64.s:956)
> ```
> 
> 
> crash inside golang

明白了。谢谢作者。
