### ISSUE TITLE
语言设置为中文点击图标还是显示英文

### ISSUE THREAD

**Issue by zhongjiajie** [yichengchen/clashX#443]
### 使用版本

ClashX version 1.31.2

### 复现方法

* 将mac全局语言设置成英文，安装 ClashX，此时默认为英文
* 点击图标打开dashboard，点击设置，语言选择中文，此时dashborad为中文
* 点击banner小图标，发现还是英文
* 退出应用重启，发现daashboard是中文，但是点击banner仍然是英文

**Comment by yichengchen** [comment]
dashboard中的设置暂时只对dashboard生效。如果要切app语言 可以尝试 https://sspai.com/post/44536 或者在系统设置 - 语言与地区 - app 中指定 （macOS 11）
