### ISSUE TITLE
Trojan x509 error: certificate signed by unknown authority

### ISSUE THREAD

**Issue by zexxlin** [yichengchen/clashX#444]
使用Trojan协议时，clash在TLS握手阶段报错：certificate signed by unknown authority。

使用的为letsencrypt申请的免费证书，浏览器可验证通过。若将skip-cert-verify置为true，可能遭遇中间人攻击，是否有更为妥善的解决方案？

**Comment by kkkingim** [comment]
今天letsencrypt证书过期,新申请的证书遇到了相同的问题,iOS使用shadowrocket没有问题,蹲一个解决方法

**Comment by yichengchen** [comment]
检查服务端设置，中间证书是否配置
