### ISSUE TITLE
configure TOR browser through ClashX

### ISSUE THREAD

**Issue by cyhonik** [yichengchen/clashX#456]
Hi,

Thanks for developing ClashX, it works great.

I am wondering if it's possible to configure TOR browser through ClashX, feel free to let me know how to use the proxy for it, thanks.

**Comment by yichengchen** [comment]
I haven't use the tor browser before. But I assume you can check if there is a "Proxy Setting" inside the tor browser. Otherwise, you can download the ClashX pro and try the "Enhance Mode", it should work.
