### ISSUE TITLE
【不知是否是个例】每次重启app均报错

### ISSUE THREAD

**Issue by xiaosong** [yichengchen/clashX#46]
运行正常的配置文件，每次app重启后，都会提示：

<img width="488" alt="screen shot 2018-11-04 at 21 57 13" src="https://user-images.githubusercontent.com/707574/47965098-97603a80-e07d-11e8-86b8-5c0a733a0565.png">

然后，诡异的是，删除 `~/.config/clash/` 后重新生成，然后将相同的配置贴进去保存又能正常运行

**Comment by yichengchen** [comment]
检查各种url是否有用引号包裹

**Comment by xiaosong** [comment]
@yichengchen 问题出在：http://www.google.com/generate_204 这个自动检测的URL没加引号导致的，现在搞定了，👍

**Comment by yzlnew** [comment]
我也遇到了这个问题，并且我的 url 有引号包裹
