### ISSUE TITLE
延迟测速不会及时显示，需要换到其他页面或者临时关闭再打开才显示最新的测延迟数据

### ISSUE THREAD

**Issue by CooCleC** [yichengchen/clashX#460]
延迟测速不会及时显示，需要换到其他页面或者临时关闭再打开才显示最新的测延迟数据

mac big sur  clashx版本 1.31.2

当配置文件节点name 中带有 / 时，测速有问题，需要离开当前窗口再回来才展示延迟数据

**Comment by CooCleC** [comment]
该是订阅链接有问题

**Comment by yichengchen** [comment]
fixed

**Comment by CooCleC** [comment]
@yichengchen 请问fork之后怎么打包，执行流程的时候在证书解密的时候报错了

**Comment by yichengchen** [comment]
> @yichengchen 请问fork之后怎么打包，执行流程的时候在证书解密的时候报错了

你需要用你自己的证书打包 或者选择sign to run locally 不签名

**Comment by CooCleC** [comment]
> > @yichengchen 请问fork之后怎么打包，执行流程的时候在证书解密的时候报错了
> 
> 你需要用你自己的证书打包 或者选择sign to run locally 不签名

大神你好，之前是想在github直接编译的， 然后报错，后来把源码拉到自己电脑上打包成功了，谢谢

**Comment by belm** [comment]
> > > @yichengchen 请问fork之后怎么打包，执行流程的时候在证书解密的时候报错了
> > 
> > 
> > 你需要用你自己的证书打包 或者选择sign to run locally 不签名
> 
> 大神你好，之前是想在github直接编译的， 然后报错，后来把源码拉到自己电脑上打包成功了，谢谢

github actions里面用的是作者自己加密后证书, 你fork后 要换成自己的证书就可以了.

**Comment by CooCleC** [comment]
> > > > @yichengchen 请问fork之后怎么打包，执行流程的时候在证书解密的时候报错了
> > > 
> > > 
> > > 你需要用你自己的证书打包 或者选择sign to run locally 不签名
> > 
> > 
> > 大神你好，之前是想在github直接编译的， 然后报错，后来把源码拉到自己电脑上打包成功了，谢谢
> 
> github actions里面用的是作者自己加密后证书, 你fork后 要换成自己的证书就可以了.

好的， 谢谢，主要自己不是ios开发，不怎么看得懂ios项目，本地打包的时候core version 和buildTime 都是unknown。昨天也是找了半天才填上，这个证书要去ios开发者平台获取么？

**Comment by yichengchen** [comment]
> > > > > @yichengchen 请问fork之后怎么打包，执行流程的时候在证书解密的时候报错了
> 
> > > > 
> 
> > > > 
> 
> > > > 你需要用你自己的证书打包 或者选择sign to run locally 不签名
> 
> > > 
> 
> > > 
> 
> > > 大神你好，之前是想在github直接编译的， 然后报错，后来把源码拉到自己电脑上打包成功了，谢谢
> 
> > 
> 
> > github actions里面用的是作者自己加密后证书, 你fork后 要换成自己的证书就可以了.
> 
> 
> 
> 好的， 谢谢，主要自己不是ios开发，不怎么看得懂ios项目，本地打包的时候core version 和buildTime 都是unknown。昨天也是找了半天才填上，大概查了一下，这个证书是要注册开发者才能有的，我自己不是ios开发，也不怎么用得上，就本地编译算了

可以pr参与开发啊

**Comment by CooCleC** [comment]
> > > > > > @yichengchen 请问fork之后怎么打包，执行流程的时候在证书解密的时候报错了
> > 
> > 
> > > > >
> > 
> > 
> > > > >
> > 
> > 
> > > > > 你需要用你自己的证书打包 或者选择sign to run locally 不签名
> > 
> > 
> > > >
> > 
> > 
> > > >
> > 
> > 
> > > > 大神你好，之前是想在github直接编译的， 然后报错，后来把源码拉到自己电脑上打包成功了，谢谢
> > 
> > 
> > > 
> > 
> > 
> > > github actions里面用的是作者自己加密后证书, 你fork后 要换成自己的证书就可以了.
> > 
> > 
> > 好的， 谢谢，主要自己不是ios开发，不怎么看得懂ios项目，本地打包的时候core version 和buildTime 都是unknown。昨天也是找了半天才填上，大概查了一下，这个证书是要注册开发者才能有的，我自己不是ios开发，也不怎么用得上，就本地编译算了
> 
> 可以pr参与开发啊

感谢大佬信任，不过我不会ios，我是前端和java，ios只能看懂一点点
