### ISSUE TITLE
[Homebrew] 希望把 ClashX Pro 添加到 Homebrew Cask 仓库

### ISSUE THREAD

**Issue by Loyalsoldier** [yichengchen/clashX#461]
类似 Zeplin 添加到 Homebrew Cask 仓库（https://github.com/Homebrew/homebrew-cask/blob/master/Casks/zeplin.rb ），需要一个 appcast URL，类似于：

```
https://api.appcenter.ms/v0.1/public/sparkle/apps/8926efff-e734-b6d3-03d0-9f41d90c34fc
```

其中 `8926efff-e734-b6d3-03d0-9f41d90c34fc` 是 app 的 app_secret。获取并设置 app_secret 参考 https://docs.microsoft.com/en-us/appcenter/distribution/sparkleupdates

**Comment by yichengchen** [comment]
appcast URL 是 https://api.appcenter.ms/v0.1/public/sparkle/apps/1cd052f7-e118-4d13-87fb-35176f9702c1 可以在info plist拿到。

据我所知clashx有 homebrew cask仓库 但不是我这边维护的，大家可以去同样的帮忙搞一个

**Comment by gqbre** [comment]
@yichengchen 尝试在搞上去，然鹅 pro dmg 的 [下载地址] (https://install.appcenter.ms/users/clashx/apps/clashx-pro/distribution_groups/public) 并没有固定直链下载地址，不知道怎么继续了

**Comment by gqbre** [comment]
> @yichengchen 尝试在搞上去，然鹅 pro dmg 的 [下载地址] (https://install.appcenter.ms/users/clashx/apps/clashx-pro/distribution_groups/public) 并没有固定直链下载地址，不知道怎么继续了

凉凉 https://github.com/Homebrew/homebrew-cask/pull/79549#issuecomment-605668146

**Comment by Loyalsoldier** [comment]
我前几天刚搞好，但 Homebrew Cask 官方不接受 AppCenter 的 app。想要自用的可以参考我这个 cask https://github.com/Homebrew/homebrew-cask/pull/100105

**Comment by gqbre** [comment]
@Loyalsoldier @yichengchen 找到方案了。。 已提 pr， https://github.com/Homebrew/homebrew-cask/pull/100346
感谢两位大佬的付出

**Comment by Loyalsoldier** [comment]
> @Loyalsoldier @yichengchen 找到方案了。。 已提 pr，[Homebrew/homebrew-cask#100347](https://github.com/Homebrew/homebrew-cask/pull/100347)
> 感谢两位大佬的付出

不是官方下载地址，应该不会通过。

**Comment by JounQin** [comment]
第三方服务不会通过，不过我有另一个提案，新增一个 AppCenterDownloadStrategy

https://github.com/Homebrew/homebrew-cask/pull/79549#issuecomment-735386385

需要的可以暂时用 https://github.com/homebrew-x/homebrew-x/blob/master/Casks/clashx-pro.rb

**Comment by gqbre** [comment]
成功添加到 cask-versions 库了，作为 ClashX 的 Pro 版本提交到这个仓库也没太大毛病，它的审核没有 cask 仓库那么严格。

https://github.com/Homebrew/homebrew-cask-versions/pull/10472

```
brew tap homebrew/cask-versions
brew install --cask clashx-pro
```
@yichengchen @JounQin @Loyalsoldier
