### ISSUE TITLE
Not usable in Terminal

### ISSUE THREAD

**Issue by Percivalllll** [yichengchen/clashX#462]
It was quite usable in the GUI environment, I can have access to google, but when I tried to install brew in terminal, the speed becomes incredibly slow and ping to google fails also, at the same time, safari can still connect to google.

I've tried all the three mode and none of them worked.

I've personally checked the log, pinging to google.com in terminal weren't even logged.

**Comment by dev4u** [comment]
ping不走tcp/udp协议，这个无解。
brew慢，这个有时切换到直连模式，会比用代理要更快。

**Comment by Percivalllll** [comment]
> ping不走tcp/udp协议，这个无解。
> brew慢，这个有时切换到直连模式，会比用代理要更快。

谢谢，另外请问一下，curl是不是也是不走TCP协议的，curl到raw.githubusercontent也存在类似问题（即浏览器可以连，但是curl就是access denied

**Comment by dev4u** [comment]
> > ping不走tcp/udp协议，这个无解。
> > brew慢，这个有时切换到直连模式，会比用代理要更快。
> 
> 谢谢，另外请问一下，curl是不是也是不走TCP协议的，curl到raw.githubusercontent也存在类似问题（即浏览器可以连，但是curl就是access denied

开启增强模式试试

**Comment by yichengchen** [comment]
please try enhance mode in ClashX Pro
