### ISSUE TITLE
clash x 支持xray的vless吗

### ISSUE THREAD

**Issue by fredericky123** [yichengchen/clashX#464]
RT

**Comment by dev4u** [comment]
没看到clash有相关的信息发出。但可以通过用v2建立socks5后，在clashx连接socks5使用。

**Comment by fredericky123** [comment]
明白，只是xray的vless协议对性能的提升不是一星半点

**Comment by f2sky** [comment]
同样有这样的需求。
目前使用支持VLESS协议的Qv2ray和v2rayU，体验都不好。

**Comment by yichengchen** [comment]
It need clash core to support.
