### ISSUE TITLE
使用proxy-providers时，benchmark 全fail

### ISSUE THREAD

**Issue by ArsenicX** [yichengchen/clashX#465]
配置用的是自己编辑的 config ，里面写了 proxy-providers，引用的是机场的订阅链接
在benchmark的时候发现所有节点都是fail，但是我的节点是能正常使用的。
我改了系统时间、换了benchmark url，发现始终都是全 fail

然后我不用自己的config，改成直接使用机场的订阅链接的配置之后，benchmark就有效了，不全是 fail 了
然后我又试着用回自己编辑的 config ，在里面手动添加了两条 proxies 节点，再次benchmark，proxy-providers的依旧还是全 fail，但是手动添加的那两条能正常测延迟了

我不知道是什么原因，但猜测应该是 proxy-providers 的问题吧，希望大佬能解决下

**Comment by yichengchen** [comment]
需要在providers配置中指定heath check url
