### ISSUE TITLE
Bug Report: 休眠后唤醒无法联网

### ISSUE THREAD

**Issue by farmostream** [yichengchen/clashX#468]
系统：10.15.7
ClashX Pro 版本：Latest
网络情况：连接iPhone热点

休眠后唤醒无法联网（此时关闭ClashX Pro后可联网）。另外重启后（CLashX为开启状态）可正常联网。

**Comment by dev4u** [comment]
重新打开增强模式可以解决

**Comment by farmostream** [comment]
> 重新打开增强模式可以解决

谢谢回复，不过还是不行。

**Comment by JulyFinal** [comment]
我也有类似的情况，不过要严重的多，硬件经过官方店检测无异常，但到目前还无法排除其他原因。
M1芯片的MBP，使用CLashX后，关闭，经过一段时间后会失去网络（包括睡眠后唤醒），但是WIFI连接无异常，只是无网络。
推测原因多样，可能是系统版本11.0-11.2、路由器（ax86u）或软件造成的，很难排查。

**Comment by yichengchen** [comment]
没有log无法分析，增强模式的dns mode和interface detection mode是什么？先close
