### ISSUE TITLE
[订阅导入失败]just my socks 订阅URL导入失败

### ISSUE THREAD

**Issue by edwards19900128** [yichengchen/clashX#470]
![image](https://user-images.githubusercontent.com/11594850/109902380-5a4ff580-7cd5-11eb-8347-41e636fedb56.png)
有大佬遇到一样的问题不？

**Comment by shidesheng1004** [comment]
我原来也碰到了这个问题，需要把订阅地址链接转换一下，转换成Clash X能用的那种就行了。
你试试在这个链接里转换一下：https://acl4ssr-sub.github.io
然后再添加到ClashX里更新。

**Comment by edwards19900128** [comment]
> 我原来也碰到了这个问题，需要把订阅地址链接转换一下，转换成Clash X能用的那种就行了。
> 你试试把之前的订阅地址在这个链接里转换一下：https://acl4ssr-sub.github.io
> 然后再添加到ClashX里更新。

感谢大佬回答，已成功替代了ShadowsocksX-NG，这货太久不更新了。
