### ISSUE TITLE
[建议] 关于设置中的端口配置

### ISSUE THREAD

**Issue by tiann** [yichengchen/clashX#471]
看了 readme 的确可以在 config.yaml 中修改这些端口配置

如果设计决定只让用户在 配置文件中改 也不是不行，但是界面上就不要用那个“看起来可以编译” 的编辑框了；因为用户会不自主地去点编辑，结果点击没有反应。

建议：

1. 要么直接支持在界面上修改配置。
2. 要么界面上不用那个编辑框，改为普通的文本框，并提示用户如果要改就去编辑配置文件。

**Comment by magic3584** [comment]
实际上改了端口也没有生效，我也不知道为啥。
而 dashboard 是 clash core 自带的，如果大佬自己写费精力了

**Comment by yichengchen** [comment]
dashboard 现在已经不能改端口了
