### ISSUE TITLE
小白使用clashx连接线路出现问题，几乎全都是失败

### ISSUE THREAD

**Issue by ZeiglerWong** [yichengchen/clashX#473]
<img width="677" alt="image" src="https://user-images.githubusercontent.com/57358101/110182399-a622ac00-7e47-11eb-9661-ac1d4ce61830.png">
如图，但是线路通过其他平台测试过是可以使用的。不知该如何调整。
#clashx

**Comment by Kevin1996cn** [comment]
同出现一样问题

**Comment by Luci4-97** [comment]
+1

**Comment by ighunk** [comment]
me too

**Comment by Kevin1996cn** [comment]
貌似 把机场的 订阅连接转换一下就可以了 https://acl4ssr-sub.github.io/

**Comment by yukewang1** [comment]
不知道出现什么问题，我这两天macos clashx pro和win clash都是所有节点timeout，换别的软件就能连上，很奇怪

**Comment by yukewang1** [comment]
> 不知道出现什么问题，我这两天macos clashx pro和win clash都是所有节点timeout，换别的软件就能连上，很奇怪

我刚看了眼config，原因都是DNS失败，我把之前fallback里的tls://dns.google:853换成8.8.8.8就好了。具体原因不是很清楚

**Comment by fenglangjunzi** [comment]
这个问题也困扰了我。在家里所有节点正常；在公司只有个别节点正常，除非修改dns为8.8.8.8或者114.114.114.114，才能跟家里一样

**Comment by lzl19900514** [comment]
是的，修改dns   enable：false或者fallback里面添加8.8.8.8后就可以了

**Comment by swuecho** [comment]
> 是的，修改dns enable：false或者fallback里面添加8.8.8.8后就可以了

能分享一下详细的dns 配置么 @lzl19900514

**Comment by yukewang1** [comment]
> > 是的，修改dns enable：false或者fallback里面添加8.8.8.8后就可以了
> 
> 能分享一下详细的dns 配置么 @lzl19900514

试试这个

`dns:
  enable: true # set true to enable dns (default is false)
  ipv6: false # default is false
  listen: 0.0.0.0:53
  enhanced-mode: fake-ip
  fake-ip-range: 198.18.0.1/16
  nameserver:
    - 114.114.114.114
    - 119.29.29.29
  fallback: # concurrent request with nameserver, fallback used when GEOIP country isn't CN
    - 1.1.1.1
    - 8.8.8.8
  fallback-filter:
    geoip: true # default
    ipcidr: # ips in these subnets will be considered polluted
      - 240.0.0.0/4`

**Comment by lzl19900514** [comment]
![](https://picgo-image-lzl.oss-cn-beijing.aliyuncs.com/tuchuang-image/20210317154935.png)

改为false或者增加 8.8.8.8都可以，两种方式选一个

**Comment by swuecho** [comment]
@yukewang1  @lzl19900514  多谢两位。 都试了一下，不成功。我通过openwrt 是可以上的，clashx 不能。

**Comment by xwLyc** [comment]
https://github.com/yichengchen/clashX/issues/490 看看是不是跟这个一样

**Comment by swuecho** [comment]
> #490 看看是不是跟这个一样

赞，确实是这个问题。 大意了。

**Comment by fenglangjunzi** [comment]
经过验证，发现只要加这几行配置就可以了：

dns:
  enable: true
  nameserver:
    - 114.114.114.114

**Comment by xwLyc** [comment]
> > #490 看看是不是跟这个一样
> 
> 赞，确实是这个问题。 大意了。

哈哈哈哈，捣鼓整整一天的成果，各种办法都试了。

**Comment by RRRoger** [comment]
> > > 是的，修改dns enable：false或者fallback里面添加8.8.8.8后就可以了
> > 
> > 
> > 能分享一下详细的dns 配置么 @lzl19900514
> 
> 试试这个
> 
> ```
> dns:
>   enable: true # set true to enable dns (default is false)
>   ipv6: false # default is false
>   listen: 0.0.0.0:53
>   enhanced-mode: fake-ip
>   fake-ip-range: 198.18.0.1/16
>   nameserver:
>     - 114.114.114.114
>     - 119.29.29.29
>   fallback: # concurrent request with nameserver, fallback used when GEOIP country isn't CN
>     - 1.1.1.1
>     - 8.8.8.8
>   fallback-filter:
>     geoip: true # default
>     ipcidr: # ips in these subnets will be considered polluted
>       - 240.0.0.0/4
> ```

请问这个在哪里设置？

**Comment by RRRoger** [comment]
> - 114.114.114.114

谢谢 解决了 过来还愿  困扰了我两天了😂
