### ISSUE TITLE
Can't use proxychains4 to connect the socks5 protocol of ClashX

### ISSUE THREAD

**Issue by yukar1z0e** [yichengchen/clashX#476]
In Apple Silicon M1 chip version.
Can't use proxychains4 to connect the socks5 protocol of ClashX.
The profile of proxychains4 is below.

```bash
[ProxyList]
# add proxy here ...
# meanwile
# defaults set to "tor"
socks5	127.0.0.1 7891
```
and the configuration profile of ClashX is below

```bash
# (HTTP and SOCKS5 in one port)
mixed-port: 7890
socks-port: 7891
port: 7892
# RESTful API for clash
external-controller: 127.0.0.1:7893
allow-lan: false
mode: rule
log-level: warning
```
when type `proxychains4 curl www.google.com` in terminal , it report error as 'time out'.

**Comment by yichengchen** [comment]
Could you try again now?
Recommend just use enhance mode in ClashX Pro

**Comment by yukar1z0e** [comment]
I tried again and the error happened again. But I think it's not the bug of the ClashX , it seems that the problem of proxychians4. I guess while  proxychains4 procceeing, it hooks some libs of apple to open socks5 tunnel , but the libs in apple (intel chip) don't exit in apple ( m1 chip).  
But still thank you for your answer.
