### ISSUE TITLE
ClashX使用过程频繁弹出网络代理身份验证窗口

### ISSUE THREAD

**Issue by dongpf** [yichengchen/clashX#477]

**Comment by dongpf** [comment]
![image](https://user-images.githubusercontent.com/968208/110566233-b1990e80-818a-11eb-81dd-0415450c8999.png)
系统：macos mojave 10.14.6

**Comment by wuzer** [comment]
我这边偶发

**Comment by mengyangniu** [comment]
我这边频发，已解决。关闭ClashX的内置“系统代理”功能，并如下设置mac即可。
<img width="780" alt="截屏2021-03-29 下午5 44 27" src="https://user-images.githubusercontent.com/34436710/112819077-c7795f80-90b6-11eb-9a55-da104f9731f8.png">

**Comment by yichengchen** [comment]
感觉是赛门铁克的问题

**Comment by denty** [comment]
@mengyangniu clash文件夹下只有.yaml文件，你这边pac文件是生成的吗

**Comment by mengyangniu** [comment]
> @mengyangniu clash文件夹下只有.yaml文件，你这边pac文件是生成的吗
我没说清楚，pac不是clashX生成的，我只是把现有的pac移到了.config/clash/。
