### ISSUE TITLE
iPhone version

### ISSUE THREAD

**Issue by hadifarnoud** [yichengchen/clashX#478]
I love Clash X. It’s super useful app. I could not do anything to this nature without Clash and this clean UI

iPhone used to have Shadowrocket vpn app with lots of features like Shortcuts support. 

Now that I saw what Clash could do, I wish we had an iOS version too. Please consider creating an iOS client 🙏🏻 I gladly pay for it too

**Comment by X1A0CA1** [comment]
+1

**Comment by ben-august** [comment]
looking forward

**Comment by Can-Chen** [comment]
+1
