### ISSUE TITLE
开启 ClashX Pro 代理后，访问局域网（内网）服务异常

### ISSUE THREAD

**Issue by jaggerwang** [yichengchen/clashX#479]
## 问题描述

有个公司内网服务 `cloud.bbdops.com`，不开启代理时可正常访问，域名解析出来的 IP 为 `10.28.108.10`。

如果只开启系统代理，curl 命令可以访问，但 Chrome 浏览器不行：
![image](https://user-images.githubusercontent.com/1255011/110600383-d7400b00-81be-11eb-9e8e-1fc5edf275cf.png)
![image](https://user-images.githubusercontent.com/1255011/110600432-e3c46380-81be-11eb-841b-50f65956dc93.png)

如果只开启增强模式，curl 命令和 Chrome 浏览器都不行，curl 命令里看到解析出来的 IP 变成了 `198.18.0.12`。
![image](https://user-images.githubusercontent.com/1255011/110600567-08204000-81bf-11eb-92e4-97da3499b823.png)

ClashX Pro 日志为空：
![image](https://user-images.githubusercontent.com/1255011/110600894-651bf600-81bf-11eb-90cf-6a3ecb89e0d9.png)

## 系统环境

OS：macOS 11.2.1
Chrome: 89.0

**Comment by KanoWill** [comment]
既然是内网服务，使用了代理之后，你的访问就是从公网尝试去访问了，当然无法实现啦

**Comment by jaggerwang** [comment]
> 既然是内网服务，使用了代理之后，你的访问就是从公网尝试去访问了，当然无法实现啦

内网服务访问肯定不会配置让其走代理阿，这个也是 ClashX 内置的配置。
<img width="1032" alt="截屏2021-03-15 13 49 27" src="https://user-images.githubusercontent.com/1255011/111109320-813fde80-8595-11eb-97af-8574155ac109.png">

**Comment by dev4u** [comment]
指定cloud.bbdops.com不要走代理试试

**Comment by jaggerwang** [comment]
![image](https://user-images.githubusercontent.com/1255011/111126958-3d0d0800-85ae-11eb-98c3-d54f7387fd93.png)
没用，重新加载配置和重启 ClashX Pro 都试了，系统代理和增强模式也都试了。

另外默认规则不是不走代理才更合理吗？安装的 1.40 版本，没做任何配置更改。

**Comment by eureka101v** [comment]
设置MATCH为DIRECT可以默认使用直连，但我设置了一个指向127.0.0.1的host地址，不知道为什么直连也无法连接，日志提示  [warning] [TCP] dial DIRECT (match Match/) to myhost.test error: couldn't find ip

**Comment by yichengchen** [comment]
把公司dns加到clash配置中试试 或者在clash配置中增加host设置

**Comment by gqbre** [comment]
类似的问题，公司内网域名 aa.com **没有添加外网解析**。
```
dns:
  enable: true
  nameserver:
      - 10.0.0.2 # 内网 DNS 服务器
      - 114.114.114.114
```
日志返回 couldn't find ip，猜测应该是 `114.114.114.114` 返回了最快的结果，但为空。
当 ``nameserver` 只保留 `10.0.0.2` 时才可正常解析，但这份配置会造成非公司网络环境下 DNS 服务不可用

**Comment by buildyuan** [comment]
> 指定cloud.bbdops.com不要走代理试试

请问是否有添加通配符的模式呢？
比如我想要所有 *.test 类似的域名都走直接连接，应当如何编写呢。
我尝试了`  - DOMAIN-SUFFIX,*.test,DIRECT`
不生效

**Comment by NinoPanic** [comment]
> > 指定cloud.bbdops.com不要走代理试试
> 
> 请问是否有添加通配符的模式呢？ 比如我想要所有 *.test 类似的域名都走直接连接，应当如何编写呢。 我尝试了` - DOMAIN-SUFFIX,*.test,DIRECT` 不生效

我在本地尝试了加了test
`DOMAIN-SUFFIX,local,test,` *.test可以正常访问了
之前都是在网络设置里的bypass添加 `*.test`
