### ISSUE TITLE
clashx pro配置文件中rule provider里的interval更新间隔好想不起作用

### ISSUE THREAD

**Issue by ben-august** [yichengchen/clashX#482]
配置文件自己写的，没有用订阅功能，自己的配置能正常使用。但是我发现规则不会自动更新，请问interval功能是不能正常使用吗？比如下面的例子，interval设置为86400s，但是时间到了并没有更新，请问这是什么原因呢？
  Rejectlist:
    type: http
    behavior: classical
    path: ./RuleSet/Rejectlist.yaml
    url: https://raw.sevencdn.com/lhie1/Rules/master/Clash/Provider/Reject.yaml
    interval: 86400

**Comment by yichengchen** [comment]
这个应该是core的问题，需要到clash core那边问问
