### ISSUE TITLE
将Clash本地监听代理端口作为OpenVPN前置代理时出现异常

### ISSUE THREAD

**Issue by KanoWill** [yichengchen/clashX#484]
![image](https://user-images.githubusercontent.com/20693041/111107558-032e0880-8592-11eb-91f4-80d9569f18e4.png)
OpenVPN报错日志如上，如果安装提示增加了float参数则会出现TLS认证错误
OpenVPN是UDP模式，节点是Vmess协议，同样的节点在V2RayU使用则不会出现此问题
因为不知道为什么Mac上的转发端口没有HTTP或Socks专有的，所以设置的OpenVPN前置代理的地址是127.0.0.1:7890

**Comment by yichengchen** [comment]
可能是core的问题，可以去 https://github.com/Dreamacro/clash 提问
