### ISSUE TITLE
设置配置自动更新的话每次自定义的规则都会被覆盖掉

### ISSUE THREAD

**Issue by drgnchan** [yichengchen/clashX#486]
是否支持合并自定义规则，而不是每次自动更新时配置文件全部覆盖呢？

**Comment by cheneyxx** [comment]
clashx能自动更新订阅吗？为啥我自己搭建的订阅感觉它并不会去更新 也不知道多长时间更新一次 openwrt clash for android clash for windows 是可以的

**Comment by drgnchan** [comment]
![image](https://user-images.githubusercontent.com/40224023/111252036-44362380-864b-11eb-9a81-0a567cae68fc.png)

打开就行了

**Comment by cheneyxx** [comment]
打开了的 我在观察一下吧 不知道默认多久同步一次

**Comment by drgnchan** [comment]
![image](https://user-images.githubusercontent.com/40224023/111252342-ddfdd080-864b-11eb-97bd-e44cd32bdc35.png)
可以打开管理，看看最近一次的更新时间

**Comment by Kaijun** [comment]
自己写了一个 Alfred Workflow 来更新，有需要的同学自取吧...

https://github.com/Kaijun/clash-subscription-update.alfredworkflow
