### ISSUE TITLE
socks 端口无效

### ISSUE THREAD

**Issue by dididi-upcar** [yichengchen/clashX#489]
http和https端口可以正常使用，但是socks端口无法使用  

![iShot2021-03-18 11.27.00.gif](https://i.loli.net/2021/03/18/y8nXMSkoJqhOr5K.gif)

**Comment by hdc8899** [comment]
我也遇到了。telegram登入不了

**Comment by HytonightYX** [comment]
一样的问题，希望解答

**Comment by yichengchen** [comment]
看上面有个jvm 警告？ 本地测速是ok的
