### ISSUE TITLE
两台mac电脑，同样的电脑系统，同样的clashx版本，同样的配置，其中一台电脑测速全是失败

### ISSUE THREAD

**Issue by xwLyc** [yichengchen/clashX#490]
系统： macOs Big Sur 11.2.3
clashx 版本： v1.40.0

本来两台电脑都能用的，最近一段时间其中一台点击延时测速的时候，所有的节点都是失败，是什么原因造成的啊

**Comment by xwLyc** [comment]
**已解决**

有问题的电脑时间不是自动的，很早之前手动调整过，设为自动时区就可以了。还是别的翻墙app提示的。建议优化一下。

**Comment by RRRoger** [comment]
我也是一台有问题 一台没问题 试了各种方式 使用了其他的app 都不行，还有什么可能性吗
