### ISSUE TITLE
clashX External controller can not use iPv6 localhost

### ISSUE THREAD

**Issue by iTZQing** [yichengchen/clashX#491]
online Web External controller (http://clash.razord.top/ & http://yacd.haishan.me/) can not use iPv6 localhost

It is feasible for these websites to use ipv6 addresses. The problem is that ClashX only uses v4 localhost address

<img width="337" alt="截圖 2021-03-21 下午8 28 18" src="https://user-images.githubusercontent.com/5062100/111905006-8795f500-8a84-11eb-82a6-be40772633bb.png">

<img width="448" alt="截圖 2021-03-21 下午8 29 08" src="https://user-images.githubusercontent.com/5062100/111905026-99779800-8a84-11eb-9c53-bdd923585859.png">

**Comment by iTZQing** [comment]
I found the problem. The default `config.yaml `file configuration is `external-controller: 127.0.0.1:9090`, which is incorrect. Should be `0.0.0.0:9090`

**Comment by yichengchen** [comment]
the external-controller should be listen in local by default. User can manual change it if there are special use case.

**Comment by iTZQing** [comment]
> the external-controller should be listen in local by default. User can manual change it if there are special use case.

But the ~~[::1]~~ is an iPv6 localhost, ⋯ 也可能是俺太笨還是不曉得為什麼會這副體 ( ˘･з･) 。

**Comment by yichengchen** [comment]
should change in clashx config. ~/.config/clash/config.yaml. If there is any more question, suggest open a ticket in clash core project
