### ISSUE TITLE
mac系统建议换一个分辨率高点的图标

### ISSUE THREAD

**Issue by ArchFeh** [yichengchen/clashX#492]
<img width="196" alt="截屏2021-03-22 16 53 58" src="https://user-images.githubusercontent.com/16155165/111964076-32fb8400-8b2f-11eb-8ed6-a5a1ab5fb428.png">
感觉锯齿有点多呀

**Comment by fuyuanyua** [comment]
不说还没发现，看了一下分辨率确实有点低

**Comment by fenglangjunzi** [comment]
支持，顶一下

**Comment by yichengchen** [comment]
好像是有问题，pro版本不会 研究看看。。

**Comment by yichengchen** [comment]
拆包看里面的资源文件是一样的。。。为什么呢

**Comment by yichengchen** [comment]
fix in 8c69bdd
