### ISSUE TITLE
在host中设置域名指向局域网或本机ip后访问异常，已经设置直连

### ISSUE THREAD

**Issue by eureka101v** [yichengchen/clashX#493]
我设置了一个指向127.0.0.1的host地址，不管是直接使用直连模式还是在规则中指定直连，都无法连接，日志提示 [warning] [TCP] dial DIRECT (match Match/) to myhost.test error: couldn't find ip

**Comment by netdong** [comment]
开启代理后无法访问本地启动的nginx服务
clashx设置的出站模式是‘规则判断’
在配置文件也加了这条过滤
- DOMAIN-SUFFIX,hbh.work,DIRECT

**Comment by netdong** [comment]
也是 couldn't find ip

**Comment by netdong** [comment]
已解决！
增加配置：


`
hosts:
   '你的域名': 127.0.0.1
`
域名可以写*号通配
