### ISSUE TITLE
clashX Pro 1.40.0.1 版本貌似还不支持 AEAD

### ISSUE THREAD

**Issue by weaming** [yichengchen/clashX#495]
- [VMess MD5 认证信息 淘汰机制 | V2Fly.org](https://www.v2fly.org/config/protocols/vmess.html#vmess-md5-%E8%AE%A4%E8%AF%81%E4%BF%A1%E6%81%AF-%E7%8E%B7%E6%B1%A1%E6%9C%BA%E5%88%B6)

**Comment by love4taylor** [comment]
这是上游的事 https://github.com/Dreamacro/clash

**Comment by love4taylor** [comment]
https://github.com/Dreamacro/clash/commit/109bfcb0f9bb07a23d55038ed4908b5d30037f31
