### ISSUE TITLE
1.2.x版本可以查看到外部配置升级到1.3.x以后的版本就看不到了

### ISSUE THREAD

**Issue by chongbaak** [yichengchen/clashX#496]
![QQ20210326-012707](https://user-images.githubusercontent.com/78186745/112516601-67429f00-8dd2-11eb-8d53-3e0488ff5b6f.png)
![QQ20210326-012745](https://user-images.githubusercontent.com/78186745/112516696-817c7d00-8dd2-11eb-84ec-88b3f9942dc4.png)

**Comment by yichengchen** [comment]
配置文件格式更新
