### ISSUE TITLE
自动更新无效

### ISSUE THREAD

**Issue by zero-hugo** [yichengchen/clashX#498]
勾选了自动更新，但订阅好像都没有更新啊，显示的最近更新都是好几天前的日期。另外，无法自定义自动更新时间，对于一些有效时间很短的代理池，我需要经常更新着呀。

**Comment by cheneyxx** [comment]
我也不知道它啥时候更新一次 有时候启动软件的时候会立即更新

**Comment by meteormatt** [comment]
看代码是48小时更新订阅。
https://github.com/yichengchen/clashX/blob/5c1049a3d214ac5577048282107d956f0d7a4249/ClashX/General/Managers/RemoteConfigManager.swift#L92

**Comment by cheneyxx** [comment]
> 看代码是48小时更新订阅。
> https://github.com/yichengchen/clashX/blob/5c1049a3d214ac5577048282107d956f0d7a4249/ClashX/General/Managers/RemoteConfigManager.swift#L92

感谢
