### ISSUE TITLE
mac下如何用clash连telegram?win下正常。Mac下能网页联网，上不了telegram

### ISSUE THREAD

**Issue by hdc8899** [yichengchen/clashX#500]
解决了。要在appstore下载才行。在网站上下载的telegram用不了

**Comment by fenglangjunzi** [comment]
![image](https://user-images.githubusercontent.com/5000975/112850140-5482df80-90dc-11eb-9b0d-214caa52eaf6.png)

**Comment by hdc8899** [comment]
这个试过了，没什么效果，一直卡。
<img width="620" alt="截屏2021-03-29 下午10 21 06" src="https://user-images.githubusercontent.com/35651076/112851094-37024580-90dd-11eb-9530-fcb7017885f5.png">

所以在想，是不是在m1下有bug

**Comment by lzl19900514** [comment]
我也是M1，tg没问题

**Comment by amoyyean** [comment]
我也是这个界面连接会一直打转。手机热点全局socks5 proxy连上过一次，然后Mac系统(Catalina)的Telegram仍然无法登录成功，提示timeout。请问如何调查问题根源？
