### ISSUE TITLE
vmess cipher 使用zero参数时报错

### ISSUE THREAD

**Issue by cbingos** [yichengchen/clashX#501]
你好：
       当我配置vmess协议时，cipher [使用zero参数时报错；](https://www.v2fly.org/config/protocols/vmess.html#outboundconfigurationobject)
`clashx pro 1.40.0.2
 vmess 配置：
- name: "vmess"
    type: vmess
    server: example.com
    port: 443
    uuid: 071uuid
    alterId: 0
    cipher: zero
    udp: true
    tls: true
    skip-cert-verify: true
    servername: example.com
    network: ws
    ws-path: /example
    ws-headers:
      Host: example.com
`
>log: [info] proxy 0: unknown security type: zero

**Comment by yichengchen** [comment]
1.50 should fix this issue
