### ISSUE TITLE
ClashX Pro的proxyIgnoreList.plist不起作用

### ISSUE THREAD

**Issue by HenryLuoCN** [yichengchen/clashX#502]
之前用ClashX的时候配置这个文件，可以不从代理走，但是下载了ClashX Pro 1.40.0.2却不起作用。

	<string>192.168.0.0/16</string>
	<string>10.0.0.0/8</string>
	<string>172.16.0.0/12</string>
	<string>127.0.0.1</string>
	<string>localhost</string>
	<string>*.local</string>
	<string>hr-payroll.iwhalecloud.com</string>
![image](https://user-images.githubusercontent.com/72094520/113079160-1c2bf000-9207-11eb-94a2-264b4b373021.png)

不知道这个TUN在哪里设置，原理是什么，难道根据GeoIP优先处理？
有其他几个域名可以直连

**Comment by HenryLuoCN** [comment]
再次打开ClashX 1.40.0测试，这个配置文件起作用，ClashX Pro下这个配置文件不起作用，难道读取proxyIgnoreList.plist目录不同？机场config文件读取目录是一样的。

**Comment by yichengchen** [comment]
一样的 本地测速时正常的。不开tun的时候clashx 和 pro是完全一致的

**Comment by degbug** [comment]
我这里是开启增强模式时这个配置不起作用，关闭增强模式时，此配置生效。

**Comment by yichengchen** [comment]
增强模式确实是不支持的，需要自己写规则
