### ISSUE TITLE
开启 ClashX 后，本地 Hosts 配置失效

### ISSUE THREAD

**Issue by JosephMing** [yichengchen/clashX#508]
![image](https://user-images.githubusercontent.com/31059354/114337263-6b690d80-9b83-11eb-96e5-b8c74981d3a8.png)

这次更新好像并没有解决这个问题

**Comment by fenglangjunzi** [comment]
我好像没有这个问题了（公司内网网站都可以访问了），1.40确实有问题

**Comment by KingAmo** [comment]
我用了1.5.0， 本地的hosts 文件并没有生效

**Comment by yichengchen** [comment]
可以到clash core提一下这个问题。

**Comment by KingAmo** [comment]
我目前的解决方案，在yaml配置文件里，设置 dns enable: false， 这样本地的hosts文件就会生效了
