### ISSUE TITLE
1.50.0版本测速全部失败

### ISSUE THREAD

**Issue by NanonaN** [yichengchen/clashX#511]
我升级clashX到1.50.0版本后，无论是手动测速还是自动测速均显示失败，socks5协议的两个节点有少部分时候会成功（但延迟较高），另外三个v2ray节点全部失效。将clashX降级到1.40.0后问题消失。

**Comment by Achilles-10** [comment]
我也遇到了这个问题，版本降级到1.40.0后问题依然存在

**Comment by fenglangjunzi** [comment]
看看是不是dns的问题

**Comment by NanonaN** [comment]
> 看看是不是dns的问题

我试过修改本地dns，清空设置、改为114.114.114.114、改为8.8.8.8均不行。而且降级到1.40.0后就没有问题了，感觉是软件本身的问题

**Comment by wangzcOvO** [comment]
我也遇到了相同问题，后来检查发现配置文件alterId设置和服务器设置不一致（以前默认一直设置的0），修改后重新加载后三个v2ray节点就能使用了。

**Comment by NanonaN** [comment]
> 我也遇到了相同问题，后来检查发现配置文件alterId设置和服务器设置不一致（以前默认一直设置的0），修改后重新加载后三个v2ray节点就能使用了。

确实如此，非常感谢，我调整alterid之后就可以了
