### ISSUE TITLE
建议优化  load-balance 策略组的 UI 显示

### ISSUE THREAD

**Issue by Chandler-Lu** [yichengchen/clashX#513]
![image](https://user-images.githubusercontent.com/18322610/114568929-250ccf00-9ca7-11eb-9866-7ca700005ce6.png)

如图，load-balance 策略组在节点名处无显示，看起来和上下很不搭。如果有可能，是否可以在此处显示 `Load Balance` 来占据空白处，谢谢

**Comment by yichengchen** [comment]
好主意

**Comment by yichengchen** [comment]
added in 610728a
