### ISSUE TITLE
[Bug] 设置系统代理失效

### ISSUE THREAD

**Issue by henhimicons** [yichengchen/clashX#516]
各位大佬好！我遇到一个问题想咨询一下。
ClashX版本 1.50.1
![image](https://user-images.githubusercontent.com/16780642/115152682-a055f280-a0a4-11eb-8745-2975c85335cf.png)
我使用时复制终端命令并且将该命令写在了zshrc中。
![image](https://user-images.githubusercontent.com/16780642/115152705-b5328600-a0a4-11eb-8054-d5bd61048d0f.png)
在iterm2中执行后ping google仍然无法ping通
![image](https://user-images.githubusercontent.com/16780642/115152736-eca13280-a0a4-11eb-9ca9-7fea48e47c14.png)
，但是通过chrome访问Google没有问题。

通过网页访问Google的log：
2021/04/19 00:22:28.556  [info] [TCP] 127.0.0.1:62390 --> www.google.com match DomainSuffix(google.com) using Proxy[GLaDOS-N2-00]
2021/04/19 00:22:28.767  [info] [TCP] 127.0.0.1:62392 --> www.google.com match DomainSuffix(google.com) using Proxy[GLaDOS-N2-00]
2021/04/19 00:22:33.797  [info] [TCP] 127.0.0.1:62396 --> aa.google.com match DomainSuffix(google.com) using Proxy[GLaDOS-N2-00]
2021/04/19 00:22:33.834  [info] [TCP] 127.0.0.1:62398 --> clients4.google.com match DomainSuffix(google.com) using Proxy[GLaDOS-N2-00]
2021/04/19 00:22:33.858  [info] [TCP] 127.0.0.1:62400 --> fonts.gstatic.com match DomainSuffix(gstatic.com) using Proxy[GLaDOS-N2-00]
2021/04/19 00:22:33.987  [info] [TCP] 127.0.0.1:62402 --> adservice.google.com.hk match DomainKeyword(google) using Proxy[GLaDOS-N2-00]
2021/04/19 00:22:36.249  [info] [TCP] 127.0.0.1:62405 --> clients4.google.com match DomainSuffix(google.com) using Proxy[GLaDOS-N2-00]
2021/04/19 00:22:37.815  [info] [TCP] 127.0.0.1:62407 --> ogs.google.com.hk match DomainKeyword(google) using Proxy[GLaDOS-N2-00]
2021/04/19 00:22:38.590  [info] [TCP] 127.0.0.1:62409 --> www.gstatic.com match DomainSuffix(gstatic.com) using Proxy[GLaDOS-N2-00]
2021/04/19 00:22:38.597  [info] [TCP] 127.0.0.1:62411 --> apis.google.com match DomainSuffix(google.com) using Proxy[GLaDOS-N2-00]
2021/04/19 00:22:44.548  [info] [TCP] 127.0.0.1:62413 --> api.im.qcloud.com match DomainSuffix(qcloud.com) using DIRECT

这个是clashx的bug嘛，谢谢各位大佬帮忙看一下！

**Comment by ysc3839** [comment]
ping 使用的是 ICMP 协议，不支持代理。
你可以执行 `curl -vv https://www.google.com` 看看有没有走代理。

**Comment by henhimicons** [comment]
看了一下是走了代理。这个issue可以关了。谢谢啦
