### ISSUE TITLE
在允许局域网连接时，复制的终端代理字符串中使用的IP地址

### ISSUE THREAD

**Issue by jasonj99** [yichengchen/clashX#518]
在允许局域网连接时，能不能把复制出的终端代理设置命令中的IP地址更换成真实的IP地址，而不是localhost地址？

例如，在在允许局域网连接时，复制出如下的命令：
export https_proxy=http://192.168.1.2:7890 http_proxy=http://192.168.1.2:7890 all_proxy=socks5://192.168.1.2:7890

**Comment by zhan9san** [comment]
同病相怜 #535
1. 在菜单栏点击clashx图标
2. 按Alt + Command + C即可
