### ISSUE TITLE
关于设置 proxy mode 设置不生效

### ISSUE THREAD

**Issue by greatislee** [yichengchen/clashX#52]
proxy mode 不可以选择模式; 默认为global   选择其他的不生效
![image](https://user-images.githubusercontent.com/24658478/48554085-6b17aa00-e918-11e8-86c3-6558cbb5ca20.png)

![image](https://user-images.githubusercontent.com/24658478/48554047-4de2db80-e918-11e8-84b3-3f0d588bd7c7.png)

**Comment by yichengchen** [comment]
看起来像配置文件有误 clash api没有成功启动 导致ui错误
