### ISSUE TITLE
[Bug] 旧的托管配置删除后，配置列表还会显示

### ISSUE THREAD

**Issue by nanqic** [yichengchen/clashX#520]
配置中添加了新的配置，旧的配置全部删除只留最新的配置，更新托管配置，再次查看配置列表还是存在旧的3个配置，请问这是bug还是我操作不当，感谢作者大大。
[配置列表](http://nanqic.github.io/images/issues/%E6%88%AA%E5%B1%8F2021-04-24%20%E4%B8%8A%E5%8D%8811.06.05.png)

**Comment by KingAmo** [comment]
在终端执行：`defaults delete com.west2online.ClashX`

**Comment by nanqic** [comment]
> 在终端执行：`defaults delete com.west2online.ClashX`

Domain (com.west2online.ClashX) not found.
Defaults have not been changed. 尝试无果，算了，不纠结了，也不影响使用
