### ISSUE TITLE
[Bug]打开几分钟后无法连接，必须重启电脑

### ISSUE THREAD

**Issue by orlowang** [yichengchen/clashX#522]
打开几分钟后无法连接，必须重启电脑，关闭重开会一直无法连接网络；这个效果很稳定，就好象开机启动clashx几分钟内一定可用fq，之后一定上不去。

1.5之前的版本(不确定具体是1.3x还是1.4x)使用很正常且稳定，这是bug吗？还是什么新的配置我遗漏了

另外[issues/521](https://github.com/yichengchen/clashX/issues/521)这个提到`set as system proxy`被修改这个，我尝试取消再勾选这个选项居然可用重新连接，但是不久(几分钟后)又不行了。我回想到就在不久前装过clashx pro，而且我发现clashx和clashx pro同时打开时都不可以使用(似乎互相占用了一些资源？)，所有有没有可能是卸载clashx(pro)时并不能完全卸载或有些缓存数据没有相应删除？

**Comment by KingAmo** [comment]
麻烦能不能点击`set as system proxy` 然后贴一下日志
```
在下方附上 ClashX 的日志，log level 最好使用 DEBUG。点击菜单栏->帮助->显示日志
```

**Comment by adamyangwg** [comment]
我最近一直有同样的问题，这是今早的日志。
[com.west2online.ClashX 2021-05-16--19-10-23-603.log](https://github.com/yichengchen/clashX/files/6490513/com.west2online.ClashX.2021-05-16--19-10-23-603.log)

**Comment by yichengchen** [comment]
历史issue，先关闭 有问题可以再开
