### ISSUE TITLE
[Feature] 配置文件预处理(Parsers)

### ISSUE THREAD

**Issue by tomatopunk** [yichengchen/clashX#524]
我认为我们需要类似Clash for Windows中的配置文件预处理功能,翻遍了Clashx,貌似目前暂不支持.
单配置文件无法满足绝大数人的需求.

举个栗子,我配置好一串配置规则,分享给同事.有部分请求需要我们全部`Forward`,有部分则需要针对性的`Forward`.
比方说我做java开发,我`不关心`domain-suffix golang.org的连接.
我做go开发,我`必须关心`domain-suffix golang.org的连接.
但是同时这些人还需要跟随我作为远端,某个节点下线,然后本地自动更新的需求.

事实证明单一配置文件,在实现远端Monitor与自定义配置文件之间,现在是存在冲突的.

我的诉求:
1. 添加类似Clash for Windows中的预处理功能
2. 支持不跟随远端更新的,本地配置规则,并且可以在更新后自动将本地配置规则与远端的配置规则合并成一份规则.

![image](https://user-images.githubusercontent.com/40015047/116182610-292cf800-a74f-11eb-833c-30e2472ca2e0.png)

**Comment by tomatopunk** [comment]
@yichengchen WDYT

**Comment by dev4u** [comment]
做java开发的，添加golang的站点规则后，会有什么影响吗？

**Comment by tomatopunk** [comment]
> 做java开发的，添加golang的站点规则后，会有什么影响吗？

如上的栗子,我这里想表达的是,由于现有功能的不支持,导致本不需要关心某个主域reject/direct
必须由远端强制制定,无形中增加了网络的复杂性.并无其他的意思.

**Comment by Loyalsoldier** [comment]
请使用 Clash Premium 提供的 Proxy Providers 功能。
