### ISSUE TITLE
macOS 11.3 

### ISSUE THREAD

**Issue by spacexnasa** [yichengchen/clashX#525]
clashx Pro 在最新版macOS 11.3 下的增强模式下，运行有问题，开启之后，不能使用代理，网页无法打开，只能去掉  Enhanced  Mode，没升级系统之前，一切都是正常的，目前不知道问题出在哪里，各位有遇到的么？

tun:
  enable: true
  macOS-auto-route: true
  macOS-auto-detect-interface: true
  device-url: dev://utun
  dns-listen: '0.0.0.0:53'
  stack: system #gvisor

**Comment by shatyuka** [comment]
看起来是DNS的问题

**Comment by hackftz** [comment]
同问

**Comment by timwa0669** [comment]
这个好像是核心Interface Detection的问题，临时解决办法是在GUI界面里把Enhanced Mode Config里的Auto Interface Detection改用ClashXIFace

**Comment by hackftz** [comment]
> 这个好像是核心Interface Detection的问题，临时解决办法是在GUI界面里把Enhanced Mode Config里的Auto Interface Detection改用ClashXIFace

怎么弄？请教

**Comment by spacexnasa** [comment]
> > 这个好像是核心Interface Detection的问题，临时解决办法是在GUI界面里把Enhanced Mode Config里的Auto Interface Detection改用ClashXIFace
> 
> 怎么弄？请教

device-url: clashxiface
# 默认是 dev://utun 在 macOS 上
如果你自己还有 openvpn，连接到办公室的这种需求，就不行了，以前是可以的

**Comment by tommychen1228** [comment]
11.3升级后，确实不行了

**Comment by weyunx** [comment]
配置-试验性功能-增强渲染代理列表，取消勾选，我这么干就好了

**Comment by lifeva** [comment]
+1

**Comment by spacexnasa** [comment]
> 配置-试验性功能-增强渲染代理列表，取消勾选，我这么干就好了

自己还有 openvpn 的话，依然是不行的

**Comment by kmkiwtk** [comment]
11.4升级后也有这个问题。。。
