### ISSUE TITLE
[Bug]在非Finder（访达页面）没有clashX的任务栏图标

### ISSUE THREAD

**Issue by angelyouyou** [yichengchen/clashX#526]
感谢你向 ClashX 提交 issue！
在提交之前，请确认：

- [ ] 这是 ClashX UI层面的问题，并非 Clash Core 的问题(例如xx软件连不上，无法连接特定服务器等)。其他 Clash 衍生版本没有次问题。

- [ ] Your issue may already be reported! Please search on the [issue tracker](……/) before creating one.

我都确认过了，我要继续提交。

### 重现问题的具体布骤 Steps to Reproduce
1、打开clashX；
2、切换到非Finder界面

**我预期会发生……？**
顶部任务栏菜单会有clashX图标。
![image](https://user-images.githubusercontent.com/12936259/116332095-aade5d80-a803-11eb-8b7a-40ba78c0e03f.png)

**实际上发生了什麽？**
顶部任务栏菜单没有clashX图标。

### 更多信息 
NA

**Comment by yichengchen** [comment]
是因为菜单栏太长了。。。安装control键把clashx 图标往里面拖一拖
