### ISSUE TITLE
能否用“全局”快捷键 或  REST-API 切换「出站模式 」？

### ISSUE THREAD

**Issue by xtremforce** [yichengchen/clashX#527]
经常需要切换出站模式
但快捷键不支持全局控制，每次都要鼠标点几次好麻烦。

能否用 REST-API 切换「出站模式 」？
看了下文档，似乎 API 没有这接口？？

**Comment by ylmf56** [comment]
MTMR可以控制到打开任何app模拟敲击任何快捷键,  但是我不太会代码，看看哪位大佬能写一个

**Comment by ylmf56** [comment]
https://apple.stackexchange.com/questions/400154/access-application-menu-item-with-applescript

**Comment by yichengchen** [comment]
reset-api是有的 可以参照https://clash.gitbook.io/doc/ 事实上clashx 也是通过操作api 实现的

**Comment by xtremforce** [comment]
> reset-api是有的 可以参照https://clash.gitbook.io/doc/ 事实上clashx 也是通过操作api 实现的

还请赐教具体是如何实现？

从文档看，rest api 中只有切换代理的方法，并没有切换「出站模式」的方法。

**Comment by yichengchen** [comment]
https://clash.gitbook.io/doc/restful-api/config  patch 修改config

**Comment by xtremforce** [comment]
> https://clash.gitbook.io/doc/restful-api/config patch 修改config

感谢！！原来在这里，成功了。。。
