### ISSUE TITLE
[Bug]通知栏上的菜单不管怎么设置都是英文的

### ISSUE THREAD

**Issue by chillyond** [yichengchen/clashX#529]
感谢你向 ClashX 提交 issue！
在提交之前，请确认：

- [x] 这是 ClashX UI层面的问题，并非 Clash Core 的问题(例如xx软件连不上，无法连接特定服务器等)。其他 Clash 衍生版本没有次问题。

软件版本：ClashX Pro 1.50.1
系统版本：macOS 11.3 (20E232)

系统语言是中文，地区也是中国，Dashboard里面的语言是中文，在系统语言设置里单独设置App的语言为中文也不行，这个菜单有办法设置成中文吗？我看别人的菜单都是中文到的，我的是这样的：
<img width="233" alt="image" src="https://user-images.githubusercontent.com/11400674/116528804-d26e1c80-a90e-11eb-9790-0aa78a954227.png">

**Comment by yichengchen** [comment]
重装一下？或者试试clashx pro? 感觉语言包被什么第三方软件删除了？

**Comment by yichengchen** [comment]
我前几天也遇到了。需要命令行执行
```
defaults delete com.west2online.clashxPro
defaults delete com.west2online.clashx
```
