### ISSUE TITLE
请问ClashX Pro的更新外部资源能通过走代理更新吗

### ISSUE THREAD

**Issue by jaykwok** [yichengchen/clashX#530]
之前每次更新外部资源是在家更新的，家里因为软路由本身挂着代理因此每次都更新成功也没有太在意；现在回到学校之后突然发现每次更新外部资源都会失败3个左右，感觉可能是直连的时候有些内容是被墙了吧。尝试找了设置貌似没有看到有设置这个的选项，就想问问请问一下有这种选项设置吗，还是说可能是我疏忽了没有找到。

**Comment by lukaschan** [comment]
同遇到这个问题。最后无奈只能把ruleset文件都下载下来后放到文件夹，最后再开启。

**Comment by yichengchen** [comment]
core不支持，暂时没有办法。需要去core提问
