### ISSUE TITLE
没有任何变动，忽然就连不上了，延迟测速全部失败？

### ISSUE THREAD

**Issue by dalton-chiou** [yichengchen/clashX#532]
版本1.30.0。无论是服务器还是本地，都没有任何变动。这些日子就连不了了，延迟测速全部失败。错误信息为：
[warning] dial Proxy error: xxx:xxx connect error: All DNS requests failed, first error: server failure
服务器是没问题的。别的客户端也连得上。
请问我要修正这个问题，从哪里入手呢？

**Comment by dalton-chiou** [comment]
试着更新到最新版本（配置文件做了需要的变化），问题依旧。错误信息为：[warning] [TCP] dial Proxy (match DomainKeyword/google) to mail.google.com error: xxx.xxxx connect error: all DNS requests failed, first error: server failure

贴一下我的主要配置：
# (HTTP and SOCKS5 in one port)
mixed-port: 7890
# RESTful API for clash
external-controller: 127.0.0.1:9090
allow-lan: false
mode: rule
log-level: silent

dns:
  enable: true
  ipv6: false
  listen: 0.0.0.0:53
  default-nameserver:
    - 114.114.114.114
    - 8.8.8.8
  enhanced-mode: redir-host # or fake-ip
  fake-ip-range: 198.18.0.1/16 # Fake IP addresses pool CIDR
  nameserver:
    - 114.114.114.114 # default value
    - 8.8.8.8 # default value
    - tls://dns.rubyfish.cn:853 # DNS over TLS
    - https://1.1.1.1/dns-query # DNS over HTTPS
  fallback: # 与 nameserver 内的服务器列表同时发起请求，当规则符合 GEOIP 在 CN 以外时，fallback 列表内的域名服务器生效。
    - tls://13800000000.rubyfish.cn:853
    - tls://1.0.0.1:853
    - tls://dns.google:853
  fallback-filter:
    geoip: true # 默认
    ipcidr: # 在这个网段内的 IP 地址会被考虑为被污染的 IP
      - 240.0.0.0/4

**Comment by yechaoa** [comment]
1.50.1 同失败

**Comment by JJAYCHEN1e** [comment]
JMS 的 v2ray 路线均失败
