### ISSUE TITLE
[Feature]提供选项将系统默认 DNS 添加到 dns.nameserver 中。

### ISSUE THREAD

**Issue by CzBiX** [yichengchen/clashX#534]
### 说明 Description
提供一个新选项，自动将默认网络接口的 DNS 添加到配置中的 `dns.nameserver` 里。

因为电脑会被带到不同的网络环境当中，将全部可能用到的 DNS 都手动添加到配置文件里并不是一个合理的方案。
Android 版 Clash 客户端很早就支持这个功能，命名为 Append System DNS。

### 更多信息 More Information
关联 issues：#479, #410, #376, #546

**Comment by yichengchen** [comment]
打开增强模式时是会自动加进去的。不开增强模式没有必要手动配置dns。会自动使用默认dns
