### ISSUE TITLE
配置文件只能选config，其他配置文件选了后还是跳回config[Bug] 

### ISSUE THREAD

**Issue by jiangaq** [yichengchen/clashX#541]
![image](https://user-images.githubusercontent.com/26076033/118216031-509cf800-b4a5-11eb-997b-4c4be1f310c2.png)

**Comment by yuwanlan** [comment]
我在config中配置了直连规则后，也是同样，强制被选中config，且不能切换

**Comment by minggangLu** [comment]
也有同样的问题，

**Comment by yichengchen** [comment]
没有log。这种情况90%是因为配置文件有问题，检查通知中心是否有弹出提示。
