### ISSUE TITLE
[Feature] 实现google插件的代理

### ISSUE THREAD

**Issue by Jasonsey** [yichengchen/clashX#542]
- [x] 我已经在 [Issue Tracker](……/) 中找过我要提出的请求

### 环境 Environment

* 使用者的操作系统 (the OS running on the client)
macOS Big Sur
* 网路环境或拓扑 (network conditions/topology)
    1. 需要通过http代理服务器才能访问外网
    2. 可以访问内部局域网
* iptables，如果适用 (if applicable)
     无
* ISP 有没有进行 DNS 污染 (is your ISP performing DNS pollution?)
     无

### 说明 Description

背景：
    1. 目前使用这个软件连接http代理服务器（有多个），使用relay的规则
    2. http代理服务器均无法访问google
    3. 目前已经购买google的插件，这个插件在公网环境下可以访问google

问题：
    1. 启动ClashX后，在不开启google插件的情况下可以访问国内网站
    2. 启动ClashX，并开启google插件的情况下，google插件显示无法访问其自身服务器，结果国内外网站均无法使用
    3. 使用Proxifer这个代理软件的时候可以实现通过google插件访问国外网站，但是这个软件和新版MacOS系统无法兼容

诉求：
    1. 期望可以通过ClashX代理这个Google插件（理论上应该是更底层的网络拦截，具体原理不清楚）

**Comment by yichengchen** [comment]
这应该是插件的问题吧？如果希望更底层的拦截，可以使用clashx pro
