### ISSUE TITLE
强烈建议加入PAC模式

### ISSUE THREAD

**Issue by YiRuiLiher** [yichengchen/clashX#544]
强烈建议加入PAC模式

**Comment by dev4u** [comment]
pac规则可以自行改成acl，

**Comment by cnlzxin** [comment]
目前对我的影响是, ClashX 设置为系统代理时, 会接管大部分流量, 导致防火墙软件 (Little Snitch) 对其他的软件无法在应用级别进行管理

**Comment by shikbupt** [comment]
> 目前对我的影响是, ClashX 设置为系统代理时, 会接管大部分流量, 导致防火墙软件 (Little Snitch) 对其他的软件无法在应用级别进行管理

碰到同样问题，好像是Little Snitch没办法对127.0.0.1流量进行监控

**Comment by guodong000** [comment]
+1 而且没有单纯的只走 proxy 的代理端口，通过 Clash X 代理端口进入的流量还是会应用规则，而不是像 ShadowsocksX 那样代理端口就是纯走 proxy。
比如我要在 Tor 上加前置代理，设置为 127.0.0.1:7890 是不起作用的，因为 Clash X 依然会应用规则判断，这时只能通过添加 ProcessName 规则来解决，不是很方便

**Comment by yichengchen** [comment]
> +1 而且没有单纯的只走 proxy 的代理端口，通过 Clash X 代理端口进入的流量还是会应用规则，而不是像 ShadowsocksX 那样代理端口就是纯走 proxy。
> 比如我要在 Tor 上加前置代理，设置为 127.0.0.1:7890 是不起作用的，因为 Clash X 依然会应用规则判断，这时只能通过添加 ProcessName 规则来解决，不是很方便

clashx core没有提供类似功能，无法实现。建议还是通过规则实现

**Comment by yichengchen** [comment]
> > 目前对我的影响是, ClashX 设置为系统代理时, 会接管大部分流量, 导致防火墙软件 (Little Snitch) 对其他的软件无法在应用级别进行管理
> 
> 碰到同样问题，好像是Little Snitch没办法对127.0.0.1流量进行监控

clash 的设计要求了流量进入clash才能走代理

**Comment by yichengchen** [comment]
目前没有计划加入pac模式

**Comment by luckymrwang** [comment]
> ProcessName

我也遇到相同问题，请问楼主，目前怎么通过`ProcessName`来解决啊？

**Comment by guodong000** [comment]
> > ProcessName
> 
> 我也遇到相同问题，请问楼主，目前怎么通过`ProcessName`来解决啊？

@luckymrwang 看一下 Clash 文档中对 PROCESS-NAME 规则的解释，简单来说和 DOMAIN-SUFFIX 这种用法基本相同，只是需要指定进程名。

实际操作时，进程名可能不是很好获取，可以结合脚本和日志打印进程名。

比如现在配置文件中添加一个脚本
```
script:
  code: |
    def main(ctx, metadata):
      # Log ProcessName
      ctx.log('Process Name: ' + ctx.resolve_process_name(metadata))
      return 'DIRECT'
```
然后 ClashX -> 帮助 -> 显示日志，并将 ClashX 出站模式选择为 脚本模式。

运行相应的程序，查看日志中打印出的进程名，这个进程名便可以直接应用到规则中。

**Comment by luckymrwang** [comment]
@guodong000 根据你提供的详细指导流程已经操作成功了，非常感谢
