### ISSUE TITLE
托管配置文件格式不正确

### ISSUE THREAD

**Issue by WengHaobin** [yichengchen/clashX#550]
![image](https://user-images.githubusercontent.com/16800049/120162270-cbe30580-c22a-11eb-8bd8-c978679cc8af.png)
是订阅的链接有问题？

**Comment by sjhjxcs** [comment]
我也遇到这种问题了，始终搞不懂

**Comment by WengHaobin** [comment]
> 我也遇到这种问题了，始终搞不懂

我这边已经解决了，联系一下机场管理员操作即可，属于机场的问题
