### ISSUE TITLE
请问能不能加个开启ipv6功能的设置开关啊。cfw里有ipv6功能开关。希望大佬在本软也加一个。谢谢。[Feature]

### ISSUE THREAD

**Issue by fyhzc** [yichengchen/clashX#551]
感谢你向 ClashX 提交 Feature Request！
在提交之前，请确认：

- [ ] 我已经在 [Issue Tracker](……/) 中找过我要提出的请求

请注意，如果你并没有遵照这个 issue template 填写内容，我们将直接关闭这个 issue。

我都确认过了，我要继续提交。

------------------------------------------------------------------

请附上任何可以帮助我们解决这个问题的信息，如果我们收到的信息不足，我们将对这个 issue 加上 *Needs more information* 标记并在收到更多资讯之前关闭 issue。

### 环境 Environment

* 使用者的操作系统 (the OS running on the client)
……
* 网路环境或拓扑 (network conditions/topology)
……
* iptables，如果适用 (if applicable)
……
* ISP 有没有进行 DNS 污染 (is your ISP performing DNS pollution?)
……
* 其他
……

**Comment by skipper17** [comment]
有同样的需求

**Comment by yichengchen** [comment]
这个有啥用啊。这个是不是可以在自带的config.yaml中进行指定。会覆盖其他配置文件的内容。

**Comment by skipper17** [comment]
哦哦哦我不了解config.yaml还能覆盖别的文件的功能，谢谢

**Comment by skipper17** [comment]
您好，我在自带的config.yaml中指定了发现并不能访问bt.byr.cn,但是在自己的config文件中指定后可以

**Comment by skipper17** [comment]
该字段和log-level字段貌似都是不会被覆盖的

**Comment by tuyifeng** [comment]
> 您好，我在自带的config.yaml中指定了发现并不能访问bt.byr.cn,但是在自己的config文件中指定后可以

请问，你是怎么在自己的config文件设置 ，才能上bt.byr.cn

**Comment by leechiuccc** [comment]
同样，在自带的config.yaml中指定并不会覆盖自己的config，config.yaml应该优先级比自己的config低，这就很麻烦，每次更新订阅都需要手动在自己的config上加伤ipv6: true
