### ISSUE TITLE
[Bug] M1版mac

### ISSUE THREAD

**Issue by mstar-kk** [yichengchen/clashX#553]
![image](https://user-images.githubusercontent.com/18113203/120736563-0c8a9980-c51f-11eb-84ae-8a484b49e95c.png)

**Comment by ighunk** [comment]
老的Mac也启动不了

**Comment by zhoushengxin** [comment]
![image](https://user-images.githubusercontent.com/25896736/120743375-790b9580-c52b-11eb-937b-fea1294971ab.png)
![image](https://user-images.githubusercontent.com/25896736/120743432-97719100-c52b-11eb-946a-f1bb5f919c77.png)
![image](https://user-images.githubusercontent.com/25896736/120743445-9d677200-c52b-11eb-8177-ac5547170b59.png)

同样启动不了，换了几个clashX的版本了

**Comment by Slandern** [comment]
我现在也是这种情况，之前还可以。

**Comment by Ran968777** [comment]
我的是一打开就闪退！！！

**Comment by yichengchen** [comment]
尝试一下pro版本？

**Comment by Ran968777** [comment]
> 尝试一下pro版本？

可以了，成功安装

**Comment by EverettSy** [comment]
> > 尝试一下pro版本？
> 
> 可以了，成功安装

用的哪个版本
