### ISSUE TITLE
http(s) 与 socks 端口 UI 显示异常

### ISSUE THREAD

**Issue by moriwang** [yichengchen/clashX#558]
### 说明 Description

界面上各处端口号码显示也不统一。
尝试修改 http 与 socks 端口并重载配置文件后，在界面上并没有更新，可能根本没有读取。

### clashX config

```
port: 9000
socks-port: 9001
```

**我预期会发生……？**
UI 显示与设置的端口号码应该一致。

**实际上发生了什麽？**
如图，橘色与红色分别对于 http 与 sock 端口显示状况 。

<img width="1477" alt="截屏2021-06-10 下午5 17 07" src="https://user-images.githubusercontent.com/9151525/121500874-4709a000-ca11-11eb-92ce-3578b5360ff6.png">

复制终端代理命令结果
```
export https_proxy=http://127.0.0.1:7890 http_proxy=http://127.0.0.1:7890 all_proxy=socks5://127.0.0.1:7890
```

归纳一下
| | http(s) | socks |
| --- | --- | --- |
| 配置文件 | 9000 | 9001 |
| 控制台-设置 | 0 | 7891 |
| 帮助-端口 | 7890 | 7890 |
| 复制终端代理命令 | 7890 | 7890 |

### 更多信息 More Information
ClashX Version Pro 1.50.1.1(7b3fe9)

**Comment by yichengchen** [comment]
默认帮忙开启mixed port了。clashx 会转换配置文件开启mixed port

**Comment by moriwang** [comment]
了解，我用 mixed-port 搜索发现已有若干 issue 提到这个问题了，之前并不知道是这个特性导致的。
希望在 Readme 中 Advance Config 第一节写清楚，也节省您回复的时间。
还有就是修改端口后，是否有方法让 clash 自动重启？或是跳一个通知提醒让用户手动重启？

**Comment by liby** [comment]
@yichengchen 冒昧打扰一下，关于这件事，我还有一些疑惑；实际上关于 http(s) 和 socks 端口显示的问题，我之前也在很多 issue 里参与过讨论：e.g.,[1](https://github.com/Dreamacro/clash/issues/982#issuecomment-721462405) and [2](https://github.com/Dreamacro/clash/discussions/818#issuecomment-674372170)

TL;DR: 如何关闭「默认帮忙开启mixed port了」的行为

今天我再来完整的整理一下关于 port 的行为，并在最后阐述我的问题：

1. 只设置 `port`，行为上看起来像是 `port` 的值被传给 `mixed-port`，最后 `port` 和 `socks-port` 都会被 `mixed-port` 的值覆盖

    |            | config.yaml | Dashboard > Setting | Help > Port |
    | ---------- | ----------- | -------- | ----------- |
    | port       | 7890        | 0        | 7890        |
    | socks-port | Unset       | 0        | 7890        |
    | mixed-port | Unset       | 7890     | No display  |

    <details>
    <summary>截图</summary>
    
    ![image](https://user-images.githubusercontent.com/38807139/126363831-bf7a42bc-c7f5-4761-9c62-48a7d646ca36.png)
    </details>

2. 只设置 `socks-port`，行为上看起来像是 `socks-port` 的值被传给 `mixed-port`，最后 `port` 和 `socks-port` 都会被 `mixed-port` 的值覆盖

    |            | config.yaml | Dashboard > Setting | Help > Port |
    | ---------- | ----------- | -------- | ----------- |
    | port       | Unset        | 0        | 7891        |
    | socks-port | 7891      | 0        | 7891        |
    | mixed-port | Unset       | 7891     | No display  |

    <details>
    <summary>截图</summary>
    
    ![image](https://user-images.githubusercontent.com/38807139/126367119-19bd4092-0961-4a99-a404-a7a32a55b775.png)
    </details>

3. 同时设置 `port` 和 `socks-port`，虽然 Dashboard > Setting 中显示 Socks Port 为 7891，但通过 Help > Port 和 「复制终端命令」 来看更像是 `port` 的值被传给 `mixed-port`，`socks-port` 的值被忽略，最后 `port` 和 `socks-port` 都会被 `mixed-port` 的值覆盖

    |            | config.yaml | Dashboard > Setting | Help > Port |
    | ---------- | ----------- | -------- | ----------- |
    | port       | 7890        | 0        | 7890        |
    | socks-port | 7891      | 7891        | 7890        |
    | mixed-port | Unset       | 7890     | No display  |

    <details>
    <summary>截图</summary>
    
    ![image](https://user-images.githubusercontent.com/38807139/126366078-892a998c-edd8-4bc0-8aeb-c0bbedb23581.png)
    </details>

4. 同时设置 `port` , `socks-port` 以及 `mixed-port`，虽然 Dashboard > Setting 中显示 HTTP port 为 7890，Socks Port 为 7891，但通过 Help > Port 和 「复制终端命令」 来看更像 `port` 和 `socks-port` 都被 `mixed-port` 的值覆盖了

    |            | config.yaml | Dashboard > Setting | Help > Port |
    | ---------- | ----------- | -------- | ----------- |
    | port       | 7890        | 7890        | 7892        |
    | socks-port | 7891      | 7891        | 7892        |
    | mixed-port | 7892       | 7892     | No display  |

    <details>
    <summary>截图</summary>
    
    ![image](https://user-images.githubusercontent.com/38807139/126367597-2354fd89-e3da-4536-82ad-c88eada2403e.png)
    </details>

5. 只设置 `mixed-port`，行为上看起来是 `port` 和 `socks-port` 都会被 `mixed-port` 的值覆盖

    |            | config.yaml | Dashboard > Setting | Help > Port |
    | ---------- | ----------- | -------- | ----------- |
    | port       | Unset        | 0        | 7890        |
    | socks-port | Unset      | 0        | 7890        |
    | mixed-port | 7890       | 7890     | No display  |

    <details>
    <summary>截图</summary>
    
    ![image](https://user-images.githubusercontent.com/38807139/126368106-c447cf00-4c6e-4167-95bd-976f014389f4.png)
    </details>

6. 不进行任何设置，行为上看起来像是 mixed-port 会被默认设置为 7890，并覆盖 `port` 和 `socks-port` 的值

    |            | config.yaml | Dashboard > Setting | Help > Port |
    | ---------- | ----------- | -------- | ----------- |
    | port       | Unset        | 0        | 7890        |
    | socks-port | Unset      | 0        | 7890        |
    | mixed-port | Unset       | 7890     | No display  |

    <details>
    <summary>截图</summary>
    
    ![image](https://user-images.githubusercontent.com/38807139/126368812-3c1bc2c2-9021-404b-9f11-1b68e362b376.png)

    </details>


因此结合下面这句话：
> 默认帮忙开启mixed port了。clashx 会转换配置文件开启mixed port

我的问题是：
1. 在没有设置 mixed port，只设置 `port` 和 `socks-port` 或它们其中之一的情况下，如何不被 mixed port 覆盖？
2. 在同时设置 `port` , `socks-port` 以及 `mixed-port` 的情况下，可以做到不被 mixed port 覆盖吗？

期待您的回复🙏
