### ISSUE TITLE
mac上最新版的clash x 1.6.7 规则不起作用，日志显示：

### ISSUE THREAD

**Issue by flipphos** [yichengchen/clashX#56]
安装了最新版1.6.7， 导入的是Hackl0us/SS-Rule-Snippet下的懒人规则

全局试用没问题，证明ss接入是正常的。

开启了『规则判断』模式时，所有网站都不能命中规则：

Google相关网站根据geoip应该走代理的，但是并没有：
2018/11/28 22:30:19:103  [info] www.google-analytics.com match GEOIP using DIRECT
2018/11/28 22:30:20:081  [info] live.github.com doesn't match any rule using DIRECT
2018/11/28 22:30:22:413  [info] api.github.com doesn't match any rule using DIRECT
2018/11/28 22:30:26:291  [info] clients4.google.com doesn't match any rule using DIRECT

fc2.com是在走proxy的规则中的，却没有命中。
2018/11/28 22:26:51:810  [info] fc2.com doesn't match any rule using DIRECT
2018/11/28 22:26:52:093  [info] fc2.com doesn't match any rule using DIRECT
2018/11/28 22:26:52:360  [info] fc2.com doesn't match any rule using DIRECT

**Comment by yichengchen** [comment]
Final 规则设置不正确 检测final指定的proxy是否真的存在（启动应该有弹窗提醒？
