### ISSUE TITLE
如何不排除10，172网段的代理？

### ISSUE THREAD

**Issue by seryte** [yichengchen/clashX#560]
我的内网网段也需要代理 ，但 clash x 默认将其排除在代理外，尝试在 config.yml 里边将10，172网段填加到了 proxy 规则，但无效，在网络设置里边，仍显示10，172网段是排除掉的
```
  - IP-CIDR,10.0.0.0/8,PROXY
  - IP-CIDR,172.16.0.0/12,PROXY
```

**Comment by yichengchen** [comment]
配置proxyignore.plist

**Comment by seryte** [comment]
> 配置proxyignore.plist
好的，多谢！
我在全盘搜索这个文件proxyignore.plist，没有找到，是要手动创建一个吗？手动创建的话，放哪个路径呢？有模版参考吗？
