### ISSUE TITLE
telegram 为啥登录不上去，那位彦祖解决过这个问题呀

### ISSUE THREAD

**Issue by eachann1026** [yichengchen/clashX#561]
试了挺多次了，也重启过，修改过端口，总是无法登陆

**Comment by YOYO-1996** [comment]
+1

**Comment by amoyyean** [comment]
我也是Mac系统(Catalina)的Telegram通过ClashX的Proxy无法登录成功，提示timeout。即使设置socks5代理成功了还是登录连接失败。请问如何调查问题根源？
