### ISSUE TITLE
[Feature] 希望添加针对虚拟网络接口的自动代理, 或增加手动代理模式

### ISSUE THREAD

**Issue by lihaoyun6** [yichengchen/clashX#566]
### 环境 Environment

* 使用者的操作系统 (the OS running on the client)
macOS Big Sur 11.4
* 网路环境或拓扑 (network conditions/topology)
办公内网 > VPN > 广域网
* iptables，如果适用 (if applicable)
无
* ISP 有没有进行 DNS 污染 (is your ISP performing DNS pollution?)
未知
* 其他
暂无

### 说明 Description

我们单位实施内外网隔离, 访问广域网需要通过VPN连接到单位的网关服务器. 也就是说我的出站接口是一个虚拟接口(VPN), 这个虚拟接口基于物理连接(WiFi), 且处于全转发模式, 所有出站流量都从网关服务器发出.
但是每次我点击软件中"设为系统代理"的按钮之后, ClashX只会给我的物理接口(WiFi)设置上代理配置, 而并没有为我实际用来访问广域网的虚拟接口(VPN)配置代理. 这就导致了即使开启系统代理, 也无法访问google之类的网站...因为VPN是全转发模式, 出站流量只走VPN, 不走WiFi.

### 可能的解决方案 Possible Solution
添加强制指定配置应用到哪个网络接口的设置项. 或者增强自动检测的能力, 加入对虚拟接口的检测, 检测到首选网络为虚拟接口时则为虚拟接口配置代理信息.
亦或者增加一个"手动模式"(或"仅启动模式"), 即仅在指定端口上启动代理, 但是不强制配置系统代理信息, 允许用户对网络进行手动配置以连接到本地代理端口

### 更多信息 More Information
暂无

**Comment by yichengchen** [comment]
这个当时尝试过，对虚拟接口设置代理后经常出现各种奇怪现象导致系统无法上网。后来又取消了。ClashX 只要启动，代理端口就是打开的，可以手动配置
