### ISSUE TITLE
[Feature] 流量统计功能

### ISSUE THREAD

**Issue by zfben** [yichengchen/clashX#569]
### 环境 Environment

* 使用者的操作系统 (the OS running on the client)

macOS 11.4

### 说明 Description

希望能够看到流量统计信息，可以按域名、日期（或其它时间维度）统计和查询

**Comment by yichengchen** [comment]
clashx 目前没有打算加入这个功能。可以参照https://github.com/Dreamacro/clash-tracing 来自行收集相关数据
