### ISSUE TITLE
无法对telegram代理

### ISSUE THREAD

**Issue by driftingdream** [yichengchen/clashX#57]
在使用clash时，无法对telegram代理，打开日志，没有看到相关信息，仿佛程序没有系统全局代理。使用surge正常使用。使用surge直连情况下，用surge的dashboard分析，telegram应用直接是direct，没有通过代理。

**Comment by yichengchen** [comment]
telegram 不遵循系统代理 需要在设置中手动设置代理

**Comment by hexd2019** [comment]
如何设置，就一个127001:1086啊

**Comment by hexd2019** [comment]
最新版控制台出不来

**Comment by zzzgit** [comment]
> telegram 不遵循系统代理 需要在设置中手动设置代理

手動添加的也是不行


![image](https://user-images.githubusercontent.com/1060733/82617299-3a49bc80-9c02-11ea-8a14-158dfed1aac3.png)


![image](https://user-images.githubusercontent.com/1060733/82617398-8d237400-9c02-11ea-9e5b-41a947a34dcc.png)


![image](https://user-images.githubusercontent.com/1060733/82617433-a0364400-9c02-11ea-9c38-2e47496cf232.png)
