### ISSUE TITLE
添加一条公司内网，直连规则，控制台规则栏已能够看到新家的域名，但是实际打不开网页，必须要关闭代理，才能打开

### ISSUE THREAD

**Issue by jacinzhang** [yichengchen/clashX#571]
感谢你向 ClashX 提交 issue！
在提交之前，请确认：

- [x] 我已经在 [Issue Tracker](……/) 中找过我要提出的问题
- [ ] 这是 ClashX UI层面的问题，并非 Clash Core 的问题(例如xx软件连不上，无法连接特定服务器等)。其他 Clash 衍生版本没有次问题。
- [ ] 如果你可以自己 debug 并解决的话，提交 PR 吧！

请注意，如果你并没有遵照这个 issue template 填写内容，我们将直接关闭这个 issue。

我都确认过了，我要继续提交。

------------------------------------------------------------------

请附上任何可以帮助我们解决这个问题的信息，如果我们收到的信息不足，我们将对这个 issue 加上 *Needs more information* 标记并在收到更多资讯之前关闭 issue。

### clashX config

```
……
```

### ClashX log

```
……
```

### ClashX Crash log

```
……
```

### 环境 Environment
……
* 使用者的操作系统 (the OS running on the client)
……
* 网路环境或拓扑 (network conditions/topology)
……
* ISP 有没有进行 DNS 污染 (is your ISP performing DNS pollution?)
……
* 其他
……

### 重现问题的具体布骤 Steps to Reproduce

1. [First Step]
2. [Second Step]
3. ……

**我预期会发生……？**

**实际上发生了什麽？**

**Comment by jacinzhang** [comment]
配置信息如下：
![image](https://user-images.githubusercontent.com/9859965/123400238-1f513500-d5d8-11eb-8d18-05f61b0f4481.png)
默认配置文件 config.yaml 里改的配置

**Comment by spacexnasa** [comment]
看下 wifi 的那个代理里面的 Bypass proxy settings 参数 ，先确保内网 ip 下，是否能够打开

**Comment by jacinzhang** [comment]
> 看下 wifi 的那个代理里面的 Bypass proxy settings 参数 ，先确保内网 ip 下，是否能够打开

这个是啥？在哪里设置？

**Comment by jacinzhang** [comment]
`内网 ip 下，是否能够打开？`
是什么意思？
现在描述是这样，挂上 clashX 内网打不开，退出 clashX 可以打开

**Comment by samllLuck** [comment]
就是clashX设置代理后，访问公司内部的一个网站，无法访问。关闭代理后，就可以访问了，如果做到既可以用clashX，也可以正常访问公司的内部网站？

**Comment by jacinzhang** [comment]
> 就是clashX设置代理后，访问公司内部的一个网站，无法访问。关闭代理后，就可以访问了，如何做到既可以用clashX，也可以正常访问公司的内部网站？

是的，就是要这样。

**Comment by spacexnasa** [comment]
wifi 图标那里点下，然后切换到代理，看下，给内网的那个代理去掉,或者修改
 ~/.config/clash/proxyIgnoreList.plist 
按照格式自己整理下

**Comment by yichengchen** [comment]
是不是配置了dns规则 删掉试试
