### ISSUE TITLE
使用咨询 - 是否可以在不开启系统代理的前提下使用http/socks5代理

### ISSUE THREAD

**Issue by 61t** [yichengchen/clashX#575]
你好, 我在使用macbook air m1 Big Sur latest update + ClashX open-source latest update. 请问是否可以在不开启系统代理的前提下使用http/socks5代理. 我已经成功设置好代理, 但是必须要开启系统代理的前提下, 才可以正常使用http/socks5 proxy.

**Comment by dev4u** [comment]
为什么不可以？用curl测试下就知道了。
```shell
curl -x socks5h://localhost:8001 http://www.google.com/
```

**Comment by 61t** [comment]
curl测试socks5成功
`curl -x socks5://127.0.0.1:7891 http://www.google.com`

vlc配置socks5
![image](https://user-images.githubusercontent.com/13398892/123891589-230df000-d927-11eb-9955-a03be1aadd2b.png)

vlc访问网络URL
![image](https://user-images.githubusercontent.com/13398892/123891762-65373180-d927-11eb-9585-925925736ebb.png)

vlc不经过socks5 :(
![image](https://user-images.githubusercontent.com/13398892/123891833-80a23c80-d927-11eb-9389-b492941785bd.png)

**Comment by 61t** [comment]
@dev4u

**Comment by ysc3839** [comment]
估计是你写错服务器格式了，可能并不需要 `socks5://`，建议看看相关文档。

**Comment by 61t** [comment]
IINA使用http proxy没有问题, VLC去掉socks5://后仍然不行. 鉴于curl正常, 应该是VLC自己软件的问题. 非常感谢. 如果有其他发现和进展, 我会在这里更新.
