### ISSUE TITLE
[Feature]添加系统代理的代理服务器ip地址设置

### ISSUE THREAD

**Issue by drizzl4** [yichengchen/clashX#576]
### 环境 Environment

* 使用者的操作系统 (the OS running on the client)
macOS Monterey

### 说明 Description

我在clash_for_windows的issue中发现有与我一样的需求，而且描述的非常详细  
而我这人又比较嘴笨，链接：https://github.com/Fndroid/clash_for_windows_pkg/issues/1987  

其实之前就有这个需求，然后上网搜一直没有找到解决方案，也是突然再一搜发现有人前几天在clash_for_windows提到  

另：我开启clashx pro之后，再去系统修改代理服务器ip地址，clash会失效，好像现在clashx  pro只能代理127.0.0.1的样子？

**Comment by yichengchen** [comment]
clashx目前不会添加这些功能。配置文件更新有点快。
是的，clashx 监听在127.0.0.1
