### ISSUE TITLE
国内网站加载变慢

### ISSUE THREAD

**Issue by liuzhaoo** [yichengchen/clashX#581]
使用校园网时，出站模式使用规则的时候国内有些网站比如B站和斗鱼加载会很慢，视频都看不了，只有选择全局的时候才会正常。尝试修改了DNS也无法解决。
但是我把wifi换成手机热点，在规则模式下也能正常访问上述网站了，有大佬能给出建议吗

**Comment by confuseder** [comment]
你是否正确获取了规则列表？
