### ISSUE TITLE
关于clash和代理的疑问

### ISSUE THREAD

**Issue by ZihaoZheng98** [yichengchen/clashX#588]
哈喽，大佬好，我开启了clash代理后，我的git不能正常push到远程仓库了，于是我去设置http代理，yaml如下，可见代理端口是7890,于是我使用git的代理设置命令：
git config --global http.proxy socks5://127.0.0.1:7890，结果显示无法访问这个端口，
fatal: 无法访问 'https://github.com/ZihaoZheng98/MLMM.git/'：Failed to connect to 127.0.0.1 port 7890: Connection refused
但我使用git config --global http.proxy socks5://127.0.0.1:1080 就没有问题

port: 7890
socks-port: 7891
redir-port: 7892

能给我解释一下这是因为什么吗

**Comment by gqbre** [comment]
git config --global http.proxy socks5://127.0.0.1:7891

**Comment by gqbre** [comment]
端口在自带的 config.yaml 文件修改，在自己的配置文件改没用

**Comment by imotoboy** [comment]
使用 clashX Pro 增强模式
