### ISSUE TITLE
您好clashx会被clean my mac 识别为恶意软件该怎么办呢

### ISSUE THREAD

**Issue by yyqxjwxy** [yichengchen/clashX#594]
![image](https://user-images.githubusercontent.com/17972392/125880558-4077733b-db91-40ba-925c-1e9832aee421.png)

**Comment by CoderKwong** [comment]
我也碰到同样的问题，不过我是clashX pro
![image](https://user-images.githubusercontent.com/12517739/125880865-5d06b47f-c494-492c-b14c-76d26c543914.png)

**Comment by xbdsky** [comment]
吓得我已经删了

**Comment by invictus555** [comment]
我也是遇到这个问题

**Comment by dev4u** [comment]
忽略就是了

**Comment by protector-yue** [comment]
我也遇到同样的问题，请问还能安全地使用吗？

**Comment by smomop** [comment]
我也遇到了，慌的很

**Comment by LongTaiJun** [comment]
我也遇到了。。。

**Comment by netdong** [comment]
换ClashX Pro就不会有提示了！

**Comment by CoderKwong** [comment]
主要是为什么突然会有这个问题，不是说没有提示就行了

**Comment by LongTaiJun** [comment]
> 换ClashX Pro 不会提示了！
> 版本：ClashX Pro 1.65.0.2

https://install.appcenter.ms/users/clashx/apps/clashx-pro/distribution_groups/public
这个版本吗？这个版本和x的区别是什么？是同一个作者么~

**Comment by CoderKwong** [comment]
希望作者可以回应下是什么问题，不是忽视了事
另外贴个可能是和这个相关的文章，也是偶然在公众号推送看到的![Screenshot_20210725-211749.jpg](https://user-images.githubusercontent.com/12517739/126900694-f144d35b-21fe-45a6-98de-d4884ac93d5b.jpg)

**Comment by nb5p** [comment]
本人尝试本地编译clashX，通过CleanMyMac扫描并未发现该问题。包括闭源版本ClashX Pro，也未扫描到该问题。
