### ISSUE TITLE
[Bug]华硕路由器的后台地址默认走的路由，建议改成直连

### ISSUE THREAD

**Issue by ioudove** [yichengchen/clashX#599]
如果我开启软件访问华硕路由器的后台的时候，根本就加载不出来，如果退出软件就可以正常访问后台了。建议把华硕路由器的后台地址改成直连

**Comment by ioudove** [comment]
补充：我把clashX调整成了“直连模式”也还是不能访问路由器后台

**Comment by ioudove** [comment]
版本：ClashX 1.65.0.2（1.65.0.2）
系统：big sur11.5（20G71）

**Comment by dev4u** [comment]
就靠你提供的这点信息，不清楚能让大家怎么帮你。

**Comment by wtuyp** [comment]
就是打不开 路由器 管理后台，一般是 192.168.1.0 那个

**Comment by ioudove** [comment]
> 就是打不开 路由器 管理后台，一般是 192.168.1.0 那个
> 
> > 就靠你提供的这点信息，不清楚能让大家怎么帮你。

嗯，这才是懂的！！！
