### ISSUE TITLE
无法让Apple M1 MacBook Air正常显示ROC旗子

### ISSUE THREAD

**Issue by chillyond** [yichengchen/clashX#600]
已经正确修改了`/Library/Preferences/.GlobalPreferences.plist`文件，并且其它地方都可以正常显示国旗，唯独菜单那里显示的是叉叉。
同样的配置文件和ClashX Pro版本，我在另外一台Intel芯片的Mac Mini上则完全没问题，系统环境都是macOS Big Sur。
ClashX版本号：8e7380
<img width="625" alt="image" src="https://user-images.githubusercontent.com/11400674/126968052-4c83c599-0165-45e0-97ea-90a636688715.png">
菜单无法显示国旗

<img width="625" alt="image" src="https://user-images.githubusercontent.com/11400674/126968566-588f7c45-415d-4dd4-8a5d-57aad9a2eea3.png">
控制台里却可以正常显示

**Comment by dreamingchow** [comment]
/Library/Preferences/.GlobalPreferences.plist要改些啥呀？

**Comment by chillyond** [comment]
请问有解决的办法吗？看到那个叉叉很难受...

**Comment by chillyond** [comment]
会是电脑硬件问题吗？

**Comment by yichengchen** [comment]
国行系统无法显示
