### ISSUE TITLE
[Bug]打开控制台，莫名黑色。还有vscode，是调试版本？

### ISSUE THREAD

**Issue by jsLWQ** [yichengchen/clashX#601]
![image](https://user-images.githubusercontent.com/49663358/127090309-95b862e5-6275-4fa5-9b90-c09c90a68d15.png)

1.65版本。mac本

![image](https://user-images.githubusercontent.com/49663358/127090392-ec8a6682-7dcb-44ce-8074-4e86819dde03.png)

**Comment by klyment** [comment]
我也遇到类似的问题，Big Sur 11.4

**Comment by yichengchen** [comment]
看起来网页没用正常加载。需要邮件 审查元素 查看具体信息。先close。
或者尝试执行 defaults delete com.west2online.clashx  清除clashx配置后再尝试
