### ISSUE TITLE
[Bug] 在mac os big sur 上无法正常进行代理

### ISSUE THREAD

**Issue by confuseder** [yichengchen/clashX#602]
# 在mac os big sur 上无法正常进行代理
除outline之外的所有代理软件都不能正常使用
设为系统代理没有作用

**Comment by confuseder** [comment]
问题已解决，给后人一个忠告，请不要在chorme中启用任何和代理有关的插件。

**Comment by 1635414810** [comment]
讲讲.配置文件加载失败.chroma没有任何和代理相关的插件
