### ISSUE TITLE
DNS 劫持问题

### ISSUE THREAD

**Issue by winkee01** [yichengchen/clashX#607]
我是 macOS，本地安装了 dnsmasq，劫持了 53 端口，然后把 dns 请求转发给 clash，clash 启用了 DNS 监听 0.0.0.0:853 端口。
问题：clash 无法正确按照从 dnsmaq 那里收到的 dns 请求来进行正确的访问。比如我在 dnsmasq 中禁用 baidu.com 这个域名，也就是 dnsmasq 劫持了这个 dns 请求直接返回一个空地址，不转发给上游的 clashX 853 端口。那么正常来说，我浏览器打开 baidu.com 的时候，就无法打开。但是 Clash X 并非按照 853 端口收到的请求来正常工作，而是直接帮我把 baidu.com 的请求发送出去。所以导致我 dnsmasq 中任何设置都无效。

clashX 版本：1.65.0
macOS 版本：Big Sur 11.4

**Comment by winkee01** [comment]
如果 Clash X 不能按照 DNS 侦听的端口来工作，而是一律把 http 请求往外发，那提供 DNS 侦听有啥用？实在不理解这种设计。

**Comment by yichengchen** [comment]
需要到clash core提问
