### ISSUE TITLE
[Bug]增强模式下proxyIgnoreList.plist无效

### ISSUE THREAD

**Issue by stimw** [yichengchen/clashX#612]
我希望ssh下对某些ip不走代理，创建了proxyIgnoreList.plist

但是似乎增强模式下proxyIgnoreList.plist无效，依然走了代理

---

只有自己改config才有效，但这影响了机场订阅自动更新，每次更新都要手动去改的话比较麻烦

希望可以修复下

**Comment by yichengchen** [comment]
proxyIgnoreList.plist 对应的是系统代理，增强模式使用tun不走系统代理。建议了解ProxyProvider的写法 创建自己的配置文件。可以把机场的配置作为provider，保留自动更新功能
