### ISSUE TITLE
手机qq发送文件至mac qq 我的电脑这里，接收不了文件，mac这里显示传输中断

### ISSUE THREAD

**Issue by lockontan** [yichengchen/clashX#614]
关闭clashx又可以接收到文件，clashx规则我只写了一个 MATCH,DIRECT。但是我用手机发送给我的qq小号，又可以接收文件，暂时排查不出问题，问下各位有遇到这种情况吗
[![61-E49-A6-F-53-E2-4-B6-C-8-EFF-5-FC66-C39-E45-A.jpg](https://i.postimg.cc/d35FsGPQ/61-E49-A6-F-53-E2-4-B6-C-8-EFF-5-FC66-C39-E45-A.jpg)](https://postimg.cc/4HHqw7xj)

**Comment by zhixuans** [comment]
我觉得可能是clash内核问题，因为我用clash for windows也是这样，只有换成5月份的内核才正常，7月份的内核就会这样

**Comment by yichengchen** [comment]
需要到 clash 内核提issue
