### ISSUE TITLE
[About Source Code] Confusing about fetching remote config

### ISSUE THREAD

**Issue by jctaoo** [yichengchen/clashX#619]
Hi, clashX is the perfect Tools on macOS, thanks for your work.

But I encountered some difficulties in the following code when I started debugging clashX.

https://github.com/yichengchen/clashX/blob/6696217d385e2263b894da848e7f9d44c8cc9998/ClashX/General/Managers/RemoteConfigManager.swift#L141-L154

I make a breakpoint at line 152, and type the command `print try? res.result.get()` in lldb console. I received a large YAML string including rules. But I will only receive a base64 string if I request my subscription URL by curl like this:

```bash
curl -s https://example.com/subscribe/xxx
```
This is why I am confused. Even if I use base64 decoding, there is only node information, but no rules information.

**Comment by ysc3839** [comment]
I guess it's user agent affects the response from server.

**Comment by yichengchen** [comment]
It's just a normal request in ClashX, maybe server had done some trick to prevent you using the curl
