### ISSUE TITLE
[Feature]状态栏速率可以显示本机的整体网速吗？而不仅仅是走代理的速率

### ISSUE THREAD

**Issue by polin-x** [yichengchen/clashX#624]
感谢你向 ClashX 提交 Feature Request！
在提交之前，请确认：

- [x] 我已经在 [Issue Tracker](……/) 中找过我要提出的请求

请注意，如果你并没有遵照这个 issue template 填写内容，我们将直接关闭这个 issue。

我都确认过了，我要继续提交。

------------------------------------------------------------------

请附上任何可以帮助我们解决这个问题的信息，如果我们收到的信息不足，我们将对这个 issue 加上 *Needs more information* 标记并在收到更多资讯之前关闭 issue。

### 环境 Environment

* 使用者的操作系统 (the OS running on the client)
……Mac os
* 网路环境或拓扑 (network conditions/topology)
…… WIFI
* iptables，如果适用 (if applicable)
……
* ISP 有没有进行 DNS 污染 (is your ISP performing DNS pollution?)
……
* 其他
……

### 可能的解决方案 Possible Solution

状态栏速率可以显示本机的整体网速吗？而不仅仅是走代理的速率

**Comment by yichengchen** [comment]
暂时不可以，建议使用类似istat menu的软件实现
