### ISSUE TITLE
如何开启对IPV6的支持？

### ISSUE THREAD

**Issue by f2sky** [yichengchen/clashX#626]
在个人的配置文件里面修改吗？还是软件自带的配置文件？
尝试了几个：config.yaml、cfw-settings.yaml 添加 ipv6: true 都无效。

**Comment by yichengchen** [comment]
在~/.config/clash/config.yaml文件中添加应该是有效的。不在个人配置文件中修改。

**Comment by shikkoku** [comment]
> 在~/.config/clash/config.yaml文件中添加应该是有效的。不在个人配置文件中修改。
`mixed-port: 7890
ipv6: true
allow-lan: false
external-controller: 127.0.0.1:58498`

ClashX Pro 1.71.0.4

没有效果，规则选全部直连，开启系统代理或者增强模式都检测不到本地网络的IPv6地址，关掉ClashX的代理功能可以检测出来。

**Comment by hongyou3** [comment]
修改~/.config/clash/config.yaml文件后需要重新启动软件才生效

**Comment by shikkoku** [comment]
> 修改~/.config/clash/config.yaml文件后需要重新启动软件才生效

重启系统都无效。只有修改本地订阅文件的配置才生效。
