### ISSUE TITLE
DNS 代理忽略本地 host 的问题

### ISSUE THREAD

**Issue by iahu** [yichengchen/clashX#627]
感谢你向 ClashX 提交 issue！
在提交之前，请确认：

- [x] 我已经在 [Issue Tracker](……/) 中找过我要提出的问题
- [ ] 这是 ClashX UI层面的问题，并非 Clash Core 的问题(例如xx软件连不上，无法连接特定服务器等)。其他 Clash 衍生版本没有次问题。
- [ ] 如果你可以自己 debug 并解决的话，提交 PR 吧！

请注意，如果你并没有遵照这个 issue template 填写内容，我们将直接关闭这个 issue。

规则里设置过 DNS 服务器代理后，会忽略本地 Host 文件，从而导致本地指定的 host 失效。

希望可以按正常流程，优先使用本地 host 

有可能是内核的问题，但是我不能确定

MacOS  ClasX v1.65.1

**Comment by yichengchen** [comment]
这个是内核问题，需要在内核提问
