### ISSUE TITLE
initial rule provider erro 

### ISSUE THREAD

**Issue by WHaveFun** [yichengchen/clashX#629]
使用 clash pro Mac 版本1.6.5.1。1
订阅github 规则报错
参考了 这个issue https://github.com/DivineEngine/Profiles/issues/1 也未能解决问题

<img width="329" alt="image" src="https://user-images.githubusercontent.com/13980779/131617589-164ae717-4758-4f4e-9374-44fb5f1063c8.png">

非 GitHub  的 没问题
订阅配置片段如下：
# 规则列表订阅
rule-providers:
  AdBlock:
    type: http
    behavior: classical
    path: ./ruleset/Advertising.yaml
    url: https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/Advertising/Advertising.yaml
    interval: 3600
  Apple:
    type: http
    behavior: classical
    path: ./Filter/Apple
    url: https://cdn.jsdelivr.net/gh/Semporia/Clash-X@master/Filter/Apple.yaml
    interval: 3600

**Comment by xiao-baii** [comment]
我也遇到这个问题，你可以通过退出clashx重新打开试试

**Comment by WHaveFun** [comment]
> 我也遇到这个问题，你可以通过退出clashx重新打开试试

thanks
