### ISSUE TITLE
为什么terminal里面还是得自己设代理

### ISSUE THREAD

**Issue by coolicer** [yichengchen/clashX#64]
socks那里不是做了代理吗？

**Comment by VincentSit** [comment]
You need [Proxifier](https://www.proxifier.com/), bro.

**Comment by magaofei** [comment]
@coolicer copy this command to terminal. change port from you configuration.
复制命令到terminal执行，更改一下端口
`export https_proxy=http://127.0.0.1:6152;export http_proxy=http://127.0.0.1:6152;export all_proxy=http://127.0.0.1:6152`

**Comment by ky0nch3ng** [comment]
http://www.renyujie.net/articles/article_os_general_1.php
