### ISSUE TITLE
求优化，对VPS用户不太友好[Feature]

### ISSUE THREAD

**Issue by bdhwrsh** [yichengchen/clashX#642]
自己搞了几个机场使用体验非常不错，梯子因为以前用商用机场的习惯使然，长期依赖clashx，但是由于clashx完全依赖一个yaml文件，这给不太懂yaml语言的小白用户带来了很多困扰。   自己试着修改了一下yaml文件（直接把商用订阅自动配置的规则复制粘贴到本人vps的yaml文件里，但是总是配置错误，不想折腾了）

建议可以借鉴一下 trojan-qt5的做法，让节点的订阅和pac规则相分离，就会便当很多。
上网搜了一圈，据说clash for windows的版本有相当丰富的自定义规则，包括可以自己选取启用哪个pac规则，希望能学习一下。

可能描述不是特别专业，大佬一定能看懂。请多多关注一下小白用户的需求～！

**Comment by bdhwrsh** [comment]
> 自己搞了几个机场使用体验非常不错，梯子因为以前用商用机场的习惯使然，长期依赖clashx，但是由于clashx完全依赖一个yaml文件，这给不太懂yaml语言的小白用户带来了很多困扰。 自己试着修改了一下yaml文件（直接把商用订阅自动配置的规则复制粘贴到本人vps的yaml文件里，但是总是配置错误，不想折腾了）
> 
> 建议可以借鉴一下 trojan-qt5的做法，让节点的订阅和pac规则相分离，就会便当很多。
> 上网搜了一圈，据说clash for windows的版本有相当丰富的自定义规则，包括可以自己选取启用哪个pac规则，希望能学习一下。
> 
> 可能描述不是特别专业，大佬们一定能看懂。请多多关注一下小白用户的需求～！

**Comment by yichengchen** [comment]
可以使用proxy provider功能进行自定义，也可以使用clash for windows 的mac版本
