### ISSUE TITLE
托管配置下载问题

### ISSUE THREAD

**Issue by KngEast** [yichengchen/clashX#65]
我是cfw和clashx1.7.7都用的
把cfw里的config.yml复制一份到clashx里，完全没问题。
同样把这份config.yml放到web端通过托管下载下来，会出现
\U0001F39E️ Netflix  《------这段通过更新回来会变成
 \U0001F39Eï¸ Netflix
多出来3个字符，然后clashx就会提示xxx不被允许
同一份文件，托管下载为什么会多出3个字符？

**Comment by beyondkmp** [comment]
should fix in [556c2ec65](https://github.com/yichengchen/clashX/commit/556c2ec658d99cd69af5b2c4558d0cd5f789384b)
