### ISSUE TITLE
[Feature] Clash Core 1.7.0配置选项存在严重Bug，最新版1.7.1中已修复，期望发一版1.7.1

### ISSUE THREAD

**Issue by lochuan** [yichengchen/clashX#651]
Bug: https://github.com/Dreamacro/clash/issues/1620

VMESS+WS这种连接方式在Clash Core 1.7.0中因上述Bug会存在配置选项读不到的问题，采用这种连接方式的朋友都会因为配置选项读不到而无法连接

期待作者可以发一版1.7.1

**Comment by yichengchen** [comment]
会在这两天更新

**Comment by lochuan** [comment]
辛苦啦
