### ISSUE TITLE
谷歌必须要全局连接才能访问 ，无法通过规则判断

### ISSUE THREAD

**Issue by PokerXu** [yichengchen/clashX#69]
谷歌必须要全局连接才能访问 ，无法通过规则判断，自己编辑配置文件把- DOMAIN-SUFFIX,google.com,Proxy添加进去也是一样无法访问

**Comment by beyondkmp** [comment]
你是不是访问了google.cn了？或者你直接用domain-key， google

**Comment by jxgu1016** [comment]
> 谷歌必须要全局连接才能访问 ，无法通过规则判断，自己编辑配置文件把- DOMAIN-SUFFIX,google.com,Proxy添加进去也是一样无法访问

请问解决了吗？我这儿也遇到了这个问题。clashX版本 1.8.2

**Comment by jxgu1016** [comment]
这个[issue](https://github.com/yichengchen/clashX/issues/56#issue-385296669)里面也是这个问题。

**Comment by jxgu1016** [comment]
@Latias94 我知道问题在哪了, final 规则里面的Proxy需要对应到服务器配置中的```name: "Proxy"```。如果你不配置 Proxy Group ，而是把“ss1”或者“ss2”改成“Proxy”也可以。
