### ISSUE TITLE
Unable to update apps in MAS when ClashX is set as system proxy

### ISSUE THREAD

**Issue by mugkid** [yichengchen/clashX#72]
Currently running ClashX 1.8.1 on macOS 10.14.2, found that apps in the Mac App Store won't update(the circle spins fast without actually updating the app).
This issue occurs whenever ClashX is set as system proxy, no matter it is under 'Global', 'Rule' or 'Direct'. However, once unselect, the update process works fine.

**Comment by yichengchen** [comment]
will be fixed in next version which is cause by a bug in current version in golang
