### ISSUE TITLE
Couldn't generate default config file when `USER\.config` did not exist

### ISSUE THREAD

**Issue by bitkwan** [yichengchen/clashX#73]
When `.config` folder did not exist, it will always ask for `Install for the system`, but always failed.

The solution is creating a folder named `.config` in the User's root folder.

Just a suggestion, adding a tip or step to create the folder will more user-friendly.

**Comment by yichengchen** [comment]
great idea

**Comment by yichengchen** [comment]
this should be a bug in 1.8.0 will fix in next version
