### ISSUE TITLE
10.11.6 依然打开控制台一片空白

### ISSUE THREAD

**Issue by luanwulin** [yichengchen/clashX#74]
才升级的1.8.2，用cleanmymac卸载重装过。现在还是打开控制台就一片空白。是不是需要删除什么东西？
![image](https://user-images.githubusercontent.com/16553854/50586736-dfe97800-0eb5-11e9-8efb-28e48d101903.png)

**Comment by yichengchen** [comment]
尝试右键刷新？还是白屏的话右键控制台看看错误提示什么

**Comment by luanwulin** [comment]
@yichengchen 这个页面闪得厉害。。。感觉一直在重新加载，点任何按键没来得及反应又被刷新了

![image](https://user-images.githubusercontent.com/16553854/50670198-da4e7800-1004-11e9-8254-f93f0586e9bb.png)

**Comment by luanwulin** [comment]
要不然把error给write到html上面，不然完全没法看，一直在闪😂

**Comment by yichengchen** [comment]
> 要不然把error给write到html上面，不然完全没法看，一直在闪😂

一直再闪的话应该是还没更新到最新版？

**Comment by luanwulin** [comment]
@yichengchen 只有按钮hover有效果，点击都不行，所以没法独立出控制台来吗，不知道是怎么回事呢。等你新版本☺️
