### ISSUE TITLE
Files missing while trying to build the app

### ISSUE THREAD

**Issue by Artwalk** [yichengchen/clashX#78]
Hi, thanks for you wrote this app.

I pulled the code and tried build it out to do some debugging, after `pod install`, I found that:

- `ProxyMenuItemView.swift` is set by `Absolute Path` 
- ClashX.h, Country.mmdb are missing

Hope you can added them in repo.

**Comment by yichengchen** [comment]
ClashX.h ClashX.a comes from go build -buildmode=c-archive
Country.mmdb is download from maxmind
Readme for building will be update in my free time

**Comment by Artwalk** [comment]
Thanks for the feedback, I can build it out now.
Maybe these steps can be helpful when you update Readme.

- `pod install`
- `cd ClashX;go build -buildmode=c-archive`
- download [Country.mmdb](http://geolite.maxmind.com/download/geoip/database/GeoLite2-Country.tar.gz), unzip, rename, move it to 'ClashX/Support Files/'
