### ISSUE TITLE
Enhance mode supported like surge?

### ISSUE THREAD

**Issue by Kilerd** [yichengchen/clashX#81]
is there any plan for clashX to implement the enhance mode like surge with using the virtual network. 
the proxy using a virtual network is totally transparent for users. what's more, it can handle all network in ur laptop. so that users do not need to set up proxies for each application and terminal. 

Surge's enhance mode can also handle all network connection sending form terminal, you know that a lots CLI commands do not use http_proxy and https_proxy so clashX cannot handle them even it was set as System Proxy. 

One more, some applications cannot set proxy manually and use system proxy neither.

So is there any plan for doing this stuff?

**Comment by yichengchen** [comment]
in planning

**Comment by liuzuil** [comment]
老板，Enhance mode模式什么时可以上线啊，这个太有用了

**Comment by 0njzy0** [comment]
在clash的tun没有出来之前，可以试用一下这个。[mellow](https://github.com/0njzy0/Mellow/releases)

**Comment by boyeye** [comment]
等了很久很久了，不说超越surge吧，至少要打平手啊，大佬加油💪
