### ISSUE TITLE
规则判断

### ISSUE THREAD

**Issue by SunoAries** [yichengchen/clashX#82]
内网无法访问

**Comment by KinJ** [comment]
DNS 里写上内网 DNS 服务器试试

**Comment by wangxin6** [comment]
# LAN
- DOMAIN-SUFFIX,local,DIRECT
- IP-CIDR,127.0.0.0/8,DIRECT
- IP-CIDR,172.16.0.0/12,DIRECT
- IP-CIDR,192.168.0.0/16,DIRECT
- IP-CIDR,10.0.0.0/8,DIRECT
- IP-CIDR,17.0.0.0/8,DIRECT
- IP-CIDR,100.64.0.0/10,DIRECT
