### ISSUE TITLE
网易云音乐不能播放

### ISSUE THREAD

**Issue by chuhaibo** [yichengchen/clashX#85]
规则模式下，网易云音乐客户端无法播放

**Comment by beyondkmp** [comment]
我的没有问题

**Comment by bi-kai** [comment]
应该怎么配置呢？我的也无法播放。
config.yaml中修改如下：
cfw-bypass:
  - localhost
  - 127.*
  - 10.*
  - 172.16.*
  - 172.17.*
  - 172.18.*
  - 172.19.*
  - 172.20.*
  - 172.21.*
  - 172.22.*
  - 172.23.*
  - 172.24.*
  - 172.25.*
  - 172.26.*
  - 172.27.*
  - 172.28.*
  - 172.29.*
  - 172.30.*
  - 172.31.*
  - 192.168.*
  - <local>
  - 'music.163.com' # 网易云域名1
  - '*.music.126.net' # 网易云域名2
  - '*.kuwo.cn' #酷我音乐
  - '*.iqiyi.com'  #爱奇艺
  - '*.microsoft.com'  #微软商店

还是不行，该怎么配置呢？

**Comment by bi-kai** [comment]
> 应该怎么配置呢？我的也无法播放。
> config.yaml中修改如下：
> cfw-bypass:
> 
> * localhost
> * 127.*
> * 10.*
> * 172.16.*
> * 172.17.*
> * 172.18.*
> * 172.19.*
> * 172.20.*
> * 172.21.*
> * 172.22.*
> * 172.23.*
> * 172.24.*
> * 172.25.*
> * 172.26.*
> * 172.27.*
> * 172.28.*
> * 172.29.*
> * 172.30.*
> * 172.31.*
> * 192.168.*
> * 
> * 'music.163.com' # 网易云域名1
> * '*.music.126.net' # 网易云域名2
> * '*.kuwo.cn' #酷我音乐
> * '*.iqiyi.com'  #爱奇艺
> * '*.microsoft.com'  #微软商店
> 
> 还是不行，该怎么配置呢？

刚试了下，不用修改chash配置，直接在系统代理设置里加上`music.163.com;*.music.126.net`即可。
![image](https://user-images.githubusercontent.com/15070379/104829804-5c3f3000-58b2-11eb-877d-68506131d9ac.png)
