### ISSUE TITLE
v2ray的shadowsocks cipher 兼容性问题

### ISSUE THREAD

**Issue by OxygenLiu** [yichengchen/clashX#86]
服务器上运行的是v2ray内置的shadowsocks，Cipher用的是[chacha20-ietf-poly1305](https://www.v2ray.com/chapter_02/protocols/shadowsocks.html)，没有obfs。

ClashX客户端应该选择哪个Cipher? 测试了AEAD_CHACHA20_POLY1305, CHACHA20-IETF, xchacha20-ietf-poly1305，都不行。

请指教？多谢！

**Comment by wangxin6** [comment]
ClashX客户端AEAD_CHACHA20_POLY1305匹配服务器段chacha20-ietf-poly1305，正常使用中。
