### ISSUE TITLE
10.11.6还是一片空白，是不是需要删除什么？

### ISSUE THREAD

**Issue by luanwulin** [yichengchen/clashX#87]
已经升级最新版，控制台还是不能用呢。用cleanmymac卸载了，又重新安装还是这样。要删除什么初始化一下不？
![image](https://user-images.githubusercontent.com/16553854/51448437-b065b700-1d61-11e9-8bcb-36ebe2d7ed5e.png)

**Comment by yichengchen** [comment]
看看那个红色感叹号里面写什么？

**Comment by luanwulin** [comment]
@yichengchen 还是和以前一样，闪的厉害，没法点

**Comment by uniway** [comment]
Same problem under same environment (10.11.6) here.

**Comment by luanwulin** [comment]
升级了1.9.0也不行 /(ㄒoㄒ)/~~

**Comment by yichengchen** [comment]
没有控制台错误无法修改= =

**Comment by luanwulin** [comment]
@yichengchen 这个页面有没有路径，可以拿到浏览器里面打开？

**Comment by luanwulin** [comment]
@yichengchen 这个页面有没有路径，可以拿到浏览器里面打开？

**Comment by dirtytao** [comment]
![image](https://user-images.githubusercontent.com/15953077/52915973-34856d00-3315-11e9-90b5-9ce5a46a392d.png)

**Comment by yichengchen** [comment]
诶 上面dashboard这个情况的时候 切节点什么的正常吗

**Comment by yichengchen** [comment]
> @yichengchen 这个页面有没有路径，可以拿到浏览器里面打开？

对吼 其实可以直接访问 http://clash.razord.top

**Comment by yichengchen** [comment]
或者浏览器访问 http://127.0.0.1:api端口(在帮助里面有)/ui/#/proxies

**Comment by luanwulin** [comment]
@yichengchen 用浏览器打开了，出现了这些报错
![image](https://user-images.githubusercontent.com/16553854/53059947-baf7a580-34f3-11e9-90e5-f8ccf342b60c.png)

**Comment by yichengchen** [comment]
这看起来是没报错的，是不是之前执行过调试指令呢？
尝试执行
```
defaults delete com.west2online.ClashX webviewUrl
```
重置一下

**Comment by luanwulin** [comment]
不行，打开控制台有一个报错，但还是闪的厉害，没法点击进去看

**Comment by JennyYu01** [comment]
问下clashX 1.9.9版本为什么规则导不进去

**Comment by benjaminv** [comment]
Dashboard 至今还是进不去，开inspect 就狂闪。但是不影响使用就是了。

**Comment by yichengchen** [comment]
closed. create a new issue if problem continue exists
