### ISSUE TITLE
how to add websocket's header host in vmess

### ISSUE THREAD

**Issue by tanpengsccd** [yichengchen/clashX#88]
![image](https://user-images.githubusercontent.com/13959880/51459264-eec79a00-1d92-11e9-8a27-2ad4c2b400a5.png)
like v2rayx

**Comment by ConnersHua** [comment]
`- { name: "vmess", type: vmess, server: server, port: 443, uuid: uuid, alterId: 32, cipher: auto, network: ws, ws-path: /path, ws-headers: { Host: v2ray.com } }`

**Comment by yichengchen** [comment]
post an issue to clash core https://github.com/Dreamacro/clash
