### ISSUE TITLE
Socks port 偶尔显示为 0

### ISSUE THREAD

**Issue by Sunnyhp** [yichengchen/clashX#89]
ClashX 版本：1.8.4
系统：MacOS Mojave 10.14.3
问题：Socks port 用的是默认的 7891 端口，但是 Dashboard 的设置里面 Socks port 偶尔显示为 0。
![](https://i.imgur.com/OBgln2z.png)

**Comment by yichengchen** [comment]
dashboard的问题在这里提出： https://github.com/Dreamacro/clash-dashboard
