### ISSUE TITLE
Missing dashboard

### ISSUE THREAD

**Issue by xujialiang** [yichengchen/clashX#92]
编译时，缺失 resource/dashboard

**Comment by c3ll256** [comment]
已提交PR，可以自行删除 Resources 下的 dashboard 然后新建一个同名的 group

**Comment by yichengchen** [comment]
会加一个编译脚本或者git keep或者git submodule来做这个事情
在resource 目录下clone http://github.com/Dreamacro/clash-dashboard 的gh-page分支
