### ISSUE TITLE
Mac OS 10.12.6 无法开机启动，但是每次都无法自动启动，需要手动打开

### ISSUE THREAD

**Issue by MuMaxxx** [yichengchen/clashX#97]
Mac OS 10.12.6 设置为开机自启动，但还是需要手动打开，才能启动软件

**Comment by yichengchen** [comment]
10.14正常 不知道是不是系统兼容原因

**Comment by MuMaxxx** [comment]
> 10.14正常 不知道是不是系统兼容原因
应该是，10.14的MacBook Pro 正常

**Comment by MuMaxxx** [comment]
应该是，运行10.14的MacBook Pro 正常。

很喜欢你这个软件，功能好用，UI精致，请一定坚持维护。
可否考虑开通捐赠渠道？一定尽力支持～

Yicheng <notifications@github.com> 于2019年2月16日周六 下午7:32写道：

**Comment by yichengchen** [comment]
> 应该是，运行10.14的MacBook Pro 正常。 很喜欢你这个软件，功能好用，UI精致，请一定坚持维护。 可否考虑开通捐赠渠道？一定尽力支持～ Yicheng <notifications@github.com> 于2019年2月16日周六 下午7:32写道：
> […](#)

支持上游Clash开发者呀 https://github.com/Dreamacro/clash
https://www.buymeacoffee.com/Dreamacro

**Comment by MuMaxxx** [comment]
OK，多谢
2019年2月19日 +0800 20:21 Yicheng <notifications@github.com>，写道：
