### ISSUE TITLE
编译报错 'ClashX.h' file not found

### ISSUE THREAD

**Issue by fxxkscript** [yichengchen/clashX#98]
`/Users/ray/Dev/clashX/ClashX/ClashX-Bridging-Header.h:4:9: error: 'ClashX.h' file not found
#import "ClashX.h"
        ^
1 error generated.
<unknown>:0: error: failed to emit precompiled header '/Users/ray/Library/Developer/Xcode/DerivedData/ClashX-fnqqtxwjczkispfyvtziuzxvzjxs/Build/Intermediates.noindex/PrecompiledHeaders/ClashX-Bridging-Header-swift_1Q51TBNS7UCV7-clang_2R07UPV97G866.pch' for bridging header '/Users/ray/Dev/clashX/ClashX/ClashX-Bridging-Header.h'
`

**Comment by yichengchen** [comment]
go build -buildmode=c-archive

**Comment by smoothdvd** [comment]
@yichengchen The command only produced ClashX.a file, there is no ClashX.h file generated.
My go version is go1.12 darwin/amd64, macOS 10.14.3
